### ISSUE TITLE
Retexturing

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#1]
At a point where I think we can start doing a little work on assets.

Obviously not intended to be all done by one person (but I'm not stopping ya if you really want to), just make a comment here before you start work to make sure people aren't working on the same task. For those that need a refresher on jappa style, take a look at [this](https://www.blockbench.net/wiki/guides/minecraft-style-guide/#hsv).

## Microminer stuff
- [x] Gemstone Sensor
- [x]     Universal navigator
- [x]     Warp engine
- [x]     Quantum Flux
- [x]     Basic Mining Laser
- [x]     Reinforced Mining Laser
- [x]     Supercharged Laser Array
- [x]     Microminer Guidance System
- [x]     Advanced MGS
- [x]     QFEHP (T9MM plates)
- [x] Microminers

The microminers themselves will be done after all of the above is done, to make sure that the MMs are visually consistent with the things used to craft them.

 ## Blocks
- [x]     Sophisticated Storage teired barrels
- [x]     Dust block

## Widgets
- [x]     Wood
- [x]     Stone
- [x]     Alloy
- [x]     Ender

## Items
- [x]     KubeJS thermal dusts (Cryotheum, Aerotheum, etc)
- [x]     Sophisticated Storage Barrel upgrades and Stack upgrades
- [x]     KubeJS clathrates
- [x]     Solidified Elements
- [x]     Stablized Elements (maybe different texture than solidified to reflect the recipe?)
- [x]     Dense Hydrogen, Ultra Dense Hydrogen
- [x]     Dilithum crystal
- [x]     Unprepared Space Suit
- [x]     Misc space suit stuff
- [x]     Pulsating dust and Mesh
- [x]     Ender, Endest Star
- [x]     Radium salt, Moon dust, Grains of innocence (prob just tint the base GTm dust texture lol)
- [x]     Smores
- [x]     Nomicoins
- [x]     Nether Star parts
- [x]      Eternal and Exotic Catalyst
- [x]       HoTU
- [x]  Creative Storage Component (I guess just make a pulsating storage upgrade or something)
- [x] Mote of Omnium
- [x] Ultimate Material

The following items do not have textures in NFm currently, so refer to Nomi CEu

- [x]    Control Unit, empty and filled
- [x]     Glowstone Elevation Unit (can prob just recolor the above)

## New Posttank Items

- [x] Tier 11, 12 Microminer
- [x] Corrupted Universe Data
- [x] Scrap, ruined capacitor, ruined sensor, ruined emitter
- [x] Holmium Oxide Glass Dust, Holmium Compound, Magnetic Capacitor Dust
- [x] Complex SMDs
- [x] Matter, Dimensional Processing Unit
- [x] Creative Datas
- [x]  Omnic Pulsar Compound
- [x] Shattered Star data
- [x] Singularity containment unit, contained singularity
- [x] QSoCs

## DE Removal Related Items
- [x] Deep Dark Data, Lair of the warden
- [x] The cores
- [x] Compound, Fusion Casings
- [x] Warden Heart
- [x] Warden Tendril
- [x] Abyss shard
- [x] Solars
- [x] Conduits
- [x] DE reactor stuff (feel free to rename/redesign)
- [x] Energy Cores (can prob just use the regular cores as a base)
- [x] Particle Generator (could do with a rename as well)
- [x] HI casings

## HM stuff
- [x] magnetron 
- [x] Microminers 4.5 and 8.5 (dont make them look silly like the OG ones lol)
- [x] Pristine Microverse Matters
- [x] Dense Magma
- [x] Omnic Data

**Comment by JuiceyBeans** [comment]
- [ ] #38 Pulsating polymer clay

**Comment by Kikismine** [comment]
I did the catalyst textures, so check that. It is now pushed to the repo

**Comment by JuiceyBeans** [comment]
- [ ] Microminers 4.5 and 8.5
- [ ] Pristine Microverse Matters

**Comment by JuiceyBeans** [comment]
Block of Monium and Monium Frame don't have the animated textures

**Comment by JuiceyBeans** [comment]
Dense Magma texture is required as well

**Comment by IamNotBrianZ** [comment]
Omnic matric coil block don't have glowing texture
![2024-06-28_21 30 49](https://github.com/ThePansmith/Monifactory/assets/74340257/67f1df16-0adb-4d98-9033-3b1e2b82332e)
