### ISSUE TITLE
[Feature]: Replace Infinity Armor set with an Infinity Tool set, gregtect style

### ISSUE THREAD

**Issue by WithersChat** [ThePansmith/Monifactory#100]
### Suggestion

Crafting the best item should require the best tools.
Not to mention, there's just as much potential for nested crafting and material cost as an armor set + sword.

**Comment by ThePansmith** [comment]
I do like the idea of having infinity tools, I wonder if it could be possible to make a mod to give them some fittingly silly effects (like a infinity soft hammer could mute everything in the whole chunk or something)

**Comment by WithersChat** [comment]
> I do like the idea of having infinity tools, I wonder if it could be possible to make a mod to give them some fittingly silly effects (like a infinity soft hammer could mute everything in the whole chunk or something)

This is way above my skill level lol.
