### ISSUE TITLE
[Bug]: Mining Hammer voids Energy Conduits

### ISSUE THREAD

**Issue by Necromantic98** [ThePansmith/Monifactory#1009]
### Issue Summary

If you mine more than 1 conduit with the mining hammer, only 1 conduit returns.

### Reproduction steps

1. get a mining hammer and set area of effect to 3x3
2. place two or more conduits next to each other (they dont have to be the same type)
3. mine the middle conduit, so that both conduits (or more) get mined
4. you only get the item, that you looked at

**Comment by alexMcGarity** [comment]
when breaking a block in which the primary is not an energy conduit, it completely voids them. adjacent conduits still appear to be connected to where the conduits were formerly

**Comment by Xefyr0** [comment]
This is not an issue we can resolve. Report it to the either the EnderIO repository, the GregTech CEu modern repository, or both:
[EnderIO](https://github.com/Team-EnderIO/EnderIO/issues)
[GregTech CEu Modern](https://github.com/GregTechCEu/GregTech-Modern/issues)
