### ISSUE TITLE
[Bug]: Large Combustion Engine Overclocking 

### ISSUE THREAD

**Issue by LindowSasaki** [ThePansmith/Monifactory#1018]
### Issue Summary

The Large Combustion Engine overclocking does not modify the intake of fuel to match expected tag (using oxygen to overclock should consume 2x fuel). It does however still produce the overclocked amount while consuming the same amount of fuel. It seems to take it a step farther by not even applying the normal overclock, meaning that currently gasoline in a LCE will run the recipe at the LV combustion generator rate of 2.5s while outputting 6144eu/t. 
Example; in game the expected output from 1B of gasoline in an overclocked LCE should be ~2.4 million EU - actual value = ~307.2 million EU

### Reproduction steps

* Create an LCE
* Supply Oxygen, Lubricant and Gasoline
* See as the recipe still displays 2.5s per operation and you fill up an entire 16x EV Battery Buffer with Lapotrons with 1.5 buckets

### Relevant log output
Found on Monifactory version 0.9.10
_No response_

**Comment by Xefyr0** [comment]
This is an issue with GregTech CEu: Modern that was already fixed in dev:
https://github.com/GregTechCEu/GregTech-Modern/commit/c74f36dbd87bf7142abc96841ea9bd5ca64ea01f
