### ISSUE TITLE
Replace Effortless Building w/ Effortless Structure once is it on Curseforge

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#1024]
Does the same job, but better and bugless.

https://github.com/huskcasaca/effortless/issues/179

**Comment by WithersChat** [comment]
Should cover #948 hopefully

**Comment by WithersChat** [comment]
Should also cover #856 hopefully

**Comment by Xefyr0** [comment]
The decision was made to nuke EB in #1056 instead:
https://discord.com/channels/914926812948234260/1229929078547550238/1302280405688520714
