### ISSUE TITLE
[Bug]: Warp Engine cannot be crafted on Dimensional Superassembler

### ISSUE THREAD

**Issue by XNFu233233233** [ThePansmith/Monifactory#1027]
### Issue Summary

Warp Engine cannot be crafted on Dimensional Superassembler
Everything works fine when making with Assembly Line
I am in expert mode and I don't know if this problem exists in all modes.

### Reproduction steps

https://github.com/user-attachments/assets/0aaa38c8-a70c-4fd9-953b-88602324f997

**Comment by KePiadina** [comment]
+1, happens on Normal mode as well

**Comment by Xefyr0** [comment]
Resolved in #1175.
