### ISSUE TITLE
[Bug]: Redstone Clock Dupe

### ISSUE THREAD

**Issue by metzdan** [ThePansmith/Monifactory#1035]
### Issue Summary

Details:
Block: Redstone Clock
Mod: Redstone Clock

Item: Diamond Axe
Mod Gregtech

When breaking the redstone clock with the diamond axe it ended up creating a duplicate Redstone clock.

This seems to happen during the redstone pulse.

### Reproduction steps

1. Place down Redstone Clock'
2. Break Clock while standing with Diamond Axe from Gregtech
4. This works less than 100% of the time but it works 4/5

**Comment by esmenard** [comment]
I already reported this bug to Redstone Clock devs back in May (it happened systematically when breaking the block during a pulse, not just with the GregTech Diamond Axe, however I didn't get a redstone clock but a block that was always active), they told me that they fixed it but apparently not.

Also another bug that might be related : sometimes when exiting and coming back to the world the redstone clock stops clocking, and starts again when broken and replaced

**Comment by ThePansmith** [comment]
smh they claimed that they fixed that
