### ISSUE TITLE
[Bug]: Fluid Rig not mining fluid

### ISSUE THREAD

**Issue by Hacobboi** [ThePansmith/Monifactory#1036]
### Issue Summary

I tried to set up a fluid rig using a battery buffer and the fluid rig is getting power but no fluid is being extracted. The output hatch says it only has air in it but the controller says the structure is valid and is mining at it's normal pace.

### Reproduction steps

Build fluid rig using guidebook
Use both ulv, lv, and mv battery buffer with mv batteries
Use different levels of wires and increased power input to mv level
Moved fluid rig both to surface and to bedrock
No fluid is mined at any power level or Y level.

**Comment by vsn4ke** [comment]
which energy hatch did you use? Mv hatch works but not 2 lv

**Comment by Hacobboi** [comment]
> which energy hatch did you use? Mv hatch works but not 2 lv

I used both the recommended ulv energy hatch and then upgraded to lv and mv energy hatches, but I’ll try the hv next
That might be something to add to the guidebook to warn it needs hv if that’s the intended level
