### ISSUE TITLE
[Bug]: Higher tier transformers are uncraftable

### ISSUE THREAD

**Issue by KePiadina** [ThePansmith/Monifactory#1038]
### Issue Summary

UHV, UEV, UIV, and UXV Hi-Amp (4x) transformers have no recipe whatsoever

Broken assembler recipes (all of them convert 64A <-> 16A):
- ULV requires a Small Red Alloy Spring
- EV requires a Platinum Spring
- UHV, UEV, and UIV require an Europium Small Spring

Corollary: 64A Substation hatches, both Dynamo and Energy, are uncraftable as they require transformers.
Example:
![image](https://github.com/user-attachments/assets/f7558824-d28e-4d75-ba8e-7d6ae065c3a2)

### Reproduction steps

1. Try to craft transformers using Assembler recipes

**Comment by Yokoharu** [comment]
I think that was fixed in #1032
