### ISSUE TITLE
[Bug]: GCYR Rocker Scanner - No UI

### ISSUE THREAD

**Issue by kwbrooks373** [ThePansmith/Monifactory#1047]
### Issue Summary

After creating the multi-block for the GCYR Rocket Scanner, when I click on the block to open the GUI, the GUI does not show the interface. It's like a texture is hiding the interface buttons.
![Interface](https://github.com/user-attachments/assets/730d7443-9fa0-46cf-a8a0-70cc62b0e723)

### Reproduction steps

1. Create a new world in creative.
2. Build the Rocket Scanner multi-block
3. Open the GUI - GUI shows, but is not interactive except for bottom button that says 'Save Launch Platform Position...'

Steps used on two separate computers with fresh installs of Monifactory. No Resource Packs Installed.
![SelectedTextures](https://github.com/user-attachments/assets/36283f75-25e2-48ee-9d0a-c9e5dda9a266)

**Comment by ThePansmith** [comment]
Report to GCYr
