### ISSUE TITLE
[Bug]: Black Concrete Powder to Black Concrete recipe on EnderIO fluid tank  voids the powder.

### ISSUE THREAD

**Issue by krakendev35** [ThePansmith/Monifactory#1048]
### Issue Summary

In this recipe, instead of producing Black Concrete, it voids the powder. If I refresh the game, the recipe works properly, but after some time, it becomes corrupted again.

### Reproduction steps

![Adsız](https://github.com/user-attachments/assets/96c3b906-8e2b-4287-9bb2-0d6946119526)

**Comment by ThePansmith** [comment]
Report to EnderIO
