### ISSUE TITLE
[Bug]: Pointing an Me Export Bus into a Gregtech Multiblock 'Me Input Bus' crashes the Game

### ISSUE THREAD

**Issue by mustermann-max** [ThePansmith/Monifactory#1053]
### Issue Summary

It just so happened that i pointed an me export bus into a normal input bus then switched that for a Gregtech Multiblock Me Input Bus and forgot to remove the export bus. After i supplied the items days later, the game crashed and broke the save.

### Reproduction steps

1. build ebf (gegtech multiblock) and use Me Input Bus as part of the ebf (offline, unconfigured)
2. setup ae2 storage system  disk drives/storage bus
3. point export bus into me input bus, set item to be exported
4. put item into ae2 storage

**Comment by ThePansmith** [comment]
Report to Gtm
