### ISSUE TITLE
[Feature]: Distilled water to steam recipe

### ISSUE THREAD

**Issue by S19TealPenguin** [ThePansmith/Monifactory#1054]
### Suggestion

Gregtech boilers won't process distilled water to turn in into steam.

Steam turbines output distilled water, it would be nice to be able to feed that output directly back into the boiler for a closed loop. Instead, I have to import normal water and store/void the excess distilled water in my power setup.

**Comment by Xefyr0** [comment]
This is something that GregTech: CEu Modern would have implemented if it were planned.
You should therefore make the report to them instead:
https://github.com/GregTechCEu/GregTech-Modern/issues
