### ISSUE TITLE
[Feature]: Replace Redstone Clock with a less buggy alternative

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#1060]
### Suggestion

In addition to #1035 which is related to an old bug that was partially fixed but not fully, there is also a bug where the redstone clock sometimes stops working when leaving and reentering the world. I told the devs on discord a week ago, but didn't get any answer. I guess it is quite easy to replace (i remember there was an other redstone clock mod in a past version), so I suggest that the mod gets replaced if these issues are not fixed soon.

**Comment by ThePansmith** [comment]
I might just remove it and just tell people to use observers at this rate lol

**Comment by ThePansmith** [comment]
> Not sure if you saw my discord DM. 

Oh joy, another case of "message requests" hiding a DM from me. Thanks for telling me here.

**Comment by desagas** [comment]
The new clock is horrible, very very bad ... yes, it allows you to specify exactly what you want for pulses, but must be activated, and can only be activated from below via a level or conduit. The old clock was automatically active without input, which was so so very much better.

**Comment by desagas** [comment]
Nope, you can not. You can absolutely attach a level to any side you want, eventhe red dot as you mentioned, but not if you want the clock to work ... try it, I dare you, lol. If you put a level directly on this clock, the clock will no longer work, you will only get a solid output.

**Comment by MightyPiggie** [comment]
> Nope, you can not. You can absolutely attach a level to any side you want, even the red dot as you mentioned, but not if you want the clock to work ... try it, I dare you, lol. If you put a level directly on this clock, the clock will no longer work, you will only get a solid output. But, I think you replied before I updated my comment.

But I don't see a problem with having an extra block instead of directly attaching it? What are you creating that makes it unusable if you don't have that extra block to your disposal?

**Comment by desagas** [comment]
All I’m saying is that you have take what should be a 1 block thing, and mandated that it now take up 3 blocks (7 blocks total with no other red stone interference). That was it. You can go back and forth all you want, but that is my complaint. There has to be a better mod out there.

**Comment by MightyPiggie** [comment]
> There has to be a better mod out there.

If you can find one, please let me know.
