### ISSUE TITLE
[Feature]: Allow all dyes to work with Xtones Reworked

### ISSUE THREAD

**Issue by teh-banana** [ThePansmith/Monifactory#1061]
### Suggestion

Currently Xtones Reworked only allows vanilla dyes. It would be nice if they could be replaced with GT Chemical Dyes or anything else that has the `forge:dyes/<color>` tag.

**Comment by ThePansmith** [comment]
Worth bringing that up to the xtones devs

**Comment by teh-banana** [comment]
This has been updated upstream.. [XTones-Reworked/10](https://github.com/TobsenD/XTones-Reworked/issues/10#issuecomment-2480474732) and available on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/xtones-reworked/files/5907303)
