### ISSUE TITLE
[Feature]: More Gem Lenses

### ISSUE THREAD

**Issue by CyaniideDrive** [ThePansmith/Monifactory#1062]
### Suggestion

Adding a couple more lenses made by gems for the Laser Inscriber.

In order:
Quartzite for Basic Glass
Spessartine for orange
Amethyst for Magenta
Yellow Garnet for Yellow
Olivine for Lime
Cinnabar for Pink
Coke for Gray
Nether Quartz for Light Gray
Apatite for Cyan
Flux instead of Amethyst for Purple
Rutile for Brown
Black Quartz for Black

Some of these have alternative gems that would also make sense, but I think having at least one for every required color would be enough, even if I'd love every gem to have a lens and work for their closest match.

If every gem had their own lens it would bring even more options.
Possible alternate gems would be:
Salt or Opal for Basic Glass
Charged/Normal Certus Quartz or Blue Topaz for Light Blue
Andradite, or Topaz for Yellow.
Green Sapphire or Uvarovite for Lime.
Rock Salt or Pyrope for Pink.
Malachite for Cyan.
Lazurite, Sodalite, or Lapis for Blue.
Grossular for Brown.
Fluorite for Green.
Almandine, Realgar, or Red Garnet for Red.
Echo Shards for Black.

**Comment by CyaniideDrive** [comment]
If this would be better off over in the GTCEU Github I can toss it there instead, but I think it would be fine as a KubeJS addition.

**Comment by Xefyr0** [comment]
Yes, this is something you'd want to contact the GTCEu developers about. As fortune has it, however, I've asked this myself and was told that there are no plans to add more gem lenses currently.
If more people ask then perhaps they'll change their mind, but do not expect any more success there than you'll find here.
