### ISSUE TITLE
[Bug]: Distillery Tower not working

### ISSUE THREAD

**Issue by Hacobboi** [ThePansmith/Monifactory#1069]
### Issue Summary

I set up my distillery tower to start breaking down light fuel but it won't start breaking it down.

### Reproduction steps

I set up my distillery using an MV energy hatch, two LV output hatches, and one LV input hatch. The machine is forming a multi block and is drawing power, but it won't begin processing the light fuel and just says "Idling". I have tried adding more output hatches to match the number of outputs i would get from the cracking, but then it won't form a multi block.

**Comment by MightyPiggie** [comment]
Make sure the output hatches are ontop of each other, as shown in the multiblock preview in EMI. If you don't match the amount of output hatches with the amount of fluids you will get, it won't work.

**Comment by Xefyr0** [comment]
The issues page of this GitHub is for issues with Monifactory itself.
Based on your report and observations of other players' gameplay as of the latest update, It seems that there is no issue with Monifactory to begin with, and you simply need some help.

For that, you'll want to join either the GregTech CE Unofficial Discord server, or Pansmith's Kitchen discord server.

For what it's worth, you _do_ need as many output hatches as there are fluid types in the recipe, and each of them must be large enough to hold the whole of the recipe's output. MightyPiggie's comment is also helpful.
