### ISSUE TITLE
[Feature]: Add Parallel Control Hatches to Subatomic Digital Assembly

### ISSUE THREAD

**Issue by KePiadina** [ThePansmith/Monifactory#1071]
### Suggestion

Shattered Universe Data and Shattered Star Data are commonly crafted recipes in the endgame, and they have a max throughput of 20/s (due to tick limit). Adding Parallelization to the Subatomic Digital Assembly multiblock could help increasing throughput instead of having to build dozens of them to keep up with the rest of blocks

**Comment by Xefyr0** [comment]
Alternative approach taken in [this commit.](https://github.com/ThePansmith/Monifactory/commit/fa61955393c6d5aa0f285e6a40f5a66245d446a9)
