### ISSUE TITLE
[Bug]: Unknown recipe serializer

### ISSUE THREAD

**Issue by RRKS101** [ThePansmith/Monifactory#1088]
### Issue Summary

When connecting to a monifactory server that I host, I get an `Internal Exception: java.lang.IllegalArgumentException: Unknown recipe serializer Minecraft:` exception. 

Both the server and client are running 0.10.0 modpack and a 0.9.1 world. The client was updated via curseforge and the server was reinstalled from scratch with the world then being moved forward.

I have tested the server generating a new world but I still get the same error. The server is running on a headless alpine linux on an x64 CPU with more than enough memory.

### Reproduction steps

1. Download ForgeInstaller 47.3.7 for minecraft 1.20.1 and run with `java -jar forge-1.20.1-47.3.7-installer.jar --installServer`
2. Download Monifactory 0.10.0 release with `wget https://github.com/ThePansmith/Monifactory/releases/download/0.10.0/Monifactory-Beta.0.10.0-server.zip -O server.zip`
3. Extract the server with `unzip -q server.zip .`
4. move files out from the `overrides` folder with`mv overrides/* .`
5. Run the server with the provided `run.sh` script, agreeing to EULA and setting port settings as required
6. Start 0.10.0 monifactory client and connect to the server.

### Relevant log output
[latest.log](https://github.com/user-attachments/files/17700973/latest.log)

**Comment by LalraenOd** [comment]
I am having the same issue, and also when connecting to a server.

**Comment by IzzyBizzy45** [comment]
Confirming same issue, only seems to occur when logging into a server, single player functions fine (even with a world generated on the server)

Client Logs - https://pastebin.com/uZhqjYTH
Server Logs - https://pastebin.com/vcyvGQ4E

**Comment by Dankrid** [comment]
Same issue immediately after update, nor problems creating a new single player world. Sorry for no logs, I'm lazy

**Comment by Bonesy122** [comment]
Same issue all fresh installs

**Comment by MightyPiggie** [comment]
Known issue.

Try removing `nuclearcraft` from the regex located on line 32 of the file `kubejs/startup_scripts/_intial.js`. Do this on the server and client side. Or wait for the hotfix.

**Comment by RRKS101** [comment]
This fixed it.
Has this already been patched in main or would you like me to open a PR?
