### ISSUE TITLE
[Bug]: Sorting Inventory while inside of LaserIO Card UI causing inventory deletion!

### ISSUE THREAD

**Issue by HowdareyouBass** [ThePansmith/Monifactory#1089]
### Issue Summary

I just deleted all of my inventory because of this thing. Very annoying! I think title is pretty explanatory, so i'll just provide a video proof.

https://github.com/user-attachments/assets/3dc2dd99-ca42-4b39-8db8-5c9ee71acc92

### Reproduction steps

1. Take LaserIO Item Card
2. Right click on it
3. Press sorting key
4. See items disappear from your inventory
5. Be sad

**Comment by robinxb** [comment]
If you press middle mouse button in Iron Furnace UI, things also got messed up.
Maybe this is related to the sorting mod itself?
