### ISSUE TITLE
[Feature]: Replace mod

### ISSUE THREAD

**Issue by AngryUnp** [ThePansmith/Monifactory#1090]
### Suggestion

Replace to Essential or delete cherished worlds
To play in a party - we installed Essential, but this mod conflicts with it, crashes the game
yes, we can just remove it, but for convenience I would like to have Essential in the build by default

**Comment by PunchmadeDav** [comment]
Do NOT use essential. It is bloated, incompatible with many mods, and used 3rd party installers, instead use [World Host](https://modrinth.com/mod/world-host) or [e4mc](https://www.curseforge.com/minecraft/mc-mods/e4mc)

**Comment by ThePansmith** [comment]
Agreed with above. Along with the aforementioned issues, iirc essential has issues with some mods as well.

Consider looking into either renting a server (Code "Pansmith" for 25% on bisect servers :trollface:), or learning to selfhost. Along with just being more reliable, they are neat ways to learn more about how server hosting works if you have never done it before.
