### ISSUE TITLE
[Feature]: Effortless Building

### ISSUE THREAD

**Issue by LCoolJT** [ThePansmith/Monifactory#1092]
### Suggestion

Somehow [effortless building](https://www.curseforge.com/minecraft/mc-mods/effortless-building) was removedin the latest version. Can't find any dev-notes about it.

**Comment by MightyPiggie** [comment]
> ### Suggestion
> 
> Somehow [effortless building](https://www.curseforge.com/minecraft/mc-mods/effortless-building) was removedin the latest version. Can't find any dev-notes about it.

https://github.com/ThePansmith/Monifactory/issues/1024

**Comment by Xefyr0** [comment]
This change is most certainly in the changelog under "Nuke EB", and under "Removed Effortless Building" in the discord annoucement:
https://discord.com/channels/914926812948234260/914926812948234268/1305375915336798228
