### ISSUE TITLE
[Bug]: Sophisticated Storage containers do not appear in EMI 

### ISSUE THREAD

**Issue by Gollomre** [ThePansmith/Monifactory#1094]
### Issue Summary

When I try to craft any barrel (iron, gold, etc.), I don’t get a recipe. Also, the quest doesn’t work. In the Creative menu, there are only acacia wood barrels

### Reproduction steps

Started the quest and tried to open the crafting recipe, but there is no recipe. Looked it up in NEI and didn’t find any "basic barrel", only copper and upwards

**Comment by ThePansmith** [comment]
The recipes are craftable, but they do not appear in EMI
![image](https://github.com/user-attachments/assets/95d8ee8f-05fa-4d5b-8831-f8068537c181)
