### ISSUE TITLE
[Bug]: Monicoin recipes show differently in JEI than the actual recipe

### ISSUE THREAD

**Issue by Dabvexx** [ThePansmith/Monifactory#1095]
### Issue Summary

Monicoin recipes show differently in JEI than the actual recipe
for example:
what JEI says galena ore is: 
![image](https://github.com/user-attachments/assets/749e2aa0-4974-452d-8df3-0f43ec17bd19)
what the actual recipe for the item is: 
![image](https://github.com/user-attachments/assets/d26e07ea-2cb6-4504-ab10-9fa5261a292c)

### Reproduction steps

1. find a monicoin recipe
2. check its JEI recipe
3. click fill recipe

**Comment by Dabvexx** [comment]
Another example is pentlandite ore
what JEI says it is: 
![image](https://github.com/user-attachments/assets/2d15c960-a635-4bcc-bee6-43a6ddd2736b)
what it actually is: 
![image](https://github.com/user-attachments/assets/04edb728-1dc2-4137-83c6-a755021399eb)

**Comment by Xefyr0** [comment]
This is an issue with EMI, not Monifactory.
See https://github.com/emilyploszaj/emi/issues/798
