### ISSUE TITLE
[Bug]: Breaking ender IO conduits with a mining hammer only gives the conduit mined and none of the others.

### ISSUE THREAD

**Issue by Dabvexx** [ThePansmith/Monifactory#1097]
### Issue Summary

When breaking a ender IO conduit with a mining hammer (untested with other area of affect mining), the conduit that was targeted is returned, but the other conduit isn't and is deleted. other pipes also act as if the conduit is still there: 
![image](https://github.com/user-attachments/assets/d913392c-42b9-4741-a49f-1163070ff896)
![image](https://github.com/user-attachments/assets/8a6676d2-9ff0-4a63-a480-e87937c6f0ca)

### Reproduction steps

Break an ender IO conduit with a mining hammer

**Comment by Xefyr0** [comment]
This is an issue with EnderIO, so it's not something we can fix. Make an issue there instead:
https://github.com/Team-EnderIO/EnderIO/issues
