### ISSUE TITLE
[Bug]: Client failing to connect to dedicated server with "Unknown recipe serializer minecraft:"

### ISSUE THREAD

**Issue by InfinitiesLoop** [ThePansmith/Monifactory#1103]
### Issue Summary

I was attempting to upgrade our 0.9 server to 0.10. Multiple players got this error trying to log in. So I also tried a fresh install of Monifactory 0.10.0 (on the same dedicated server), and it still happens. I am able to play locally with the same world save on 0.10, so might be a server-specific issue.

### Reproduction steps

1. Install Monifactory 0.10 per the server instructions (forge --installServer, etc)
2. Start the server
3. Try to connect to the server from a 0.10 client
4. Immediately after the connection is established -> "Internal Exception: java.lang.IllegalArgumentException: Unknown recipe serializer minecraft:"  (note the trailing colon is part of the message)

![image](https://github.com/user-attachments/assets/db7dd800-6e0c-4168-bcbf-69d4e51116aa)

server log:
[monifactory-server-log-0.10.0.log](https://github.com/user-attachments/files/17722928/monifactory-server-log-0.10.0.log)

client log:
[monifactory-client-log-0.10.0.log](https://github.com/user-attachments/files/17722934/monifactory-client-log-0.10.0.log)

### Relevant log output

```shell
See the attached server and client log files
```

**Comment by sillysimon** [comment]
Same issue here, although for me, it manages to get to "Loading Terrain" before displaying the error

**Comment by ThePansmith** [comment]
Report to NuclearCraft Neo

**Comment by igentuman** [comment]
Ok. I'll check it on monifactory pack

**Comment by igentuman** [comment]
Detailed error
Error reading recipe nuclearcraft:assembler/glowstone_dust-dusts_quartz-redstone-dusts_emerald from packet. Trace: java.lang.IllegalArgumentException: ItemStackIngredients cannot be created using the empty ingredient

**Comment by InfinitiesLoop** [comment]
fwiw I get it with 0.10.2 as well. I noticed there was a NC update and a mention of a fix/revert related to a NC recipe. But it's the same issue (the 'cannot be created using the empty ingredient' error sometimes happens even on 0.9.10, but it's rare, so not sure if that's a different issue).

**Comment by ryanz4475** [comment]
0.10.2 does not include the new version of NCNeo (released 11/17, 1.1.0-rc.2), which introduces the fix. Writing this so devs are aware and can add to the next update.
