### ISSUE TITLE
[Bug]: Iron downgrades in compacting drawers result in wrong storage caps

### ISSUE THREAD

**Issue by RolaRoul** [ThePansmith/Monifactory#1105]
### Issue Summary

Compacting drawers with an iron downgrade should be able to store a max of 64 of the most compacted item (block of coal, etc).
However, for most items, the max is larger, and for some combinations the downgrade actually increases the storage.
Coal in 3-slot drawer: Max 4.6k blocks (without downgrade) -> max 576 blocks (with downgrade)
Coal in 2-slot drawer: Max 512 blocks -> max 576 blocks
Iron in 3-slot drawer: Max 512 blocks -> max 64 blocks, can't insert downgrade if there are more than 64 nuggets in the drawer
Iron in 2-slot drawer: Max 512 blocks -> max 576 blocks
Certus in 3-slot drawer: Max 10.4 blocks -> max 1.3 blocks
Certus in 2-slot drawer: Max 1.2 blocks -> max 1.3 blocks

### Reproduction steps

1. Place compacting drawer.
2. Insert compactable item (coal, ingots, etc).
3. Insert iron downgrade

**Comment by Xefyr0** [comment]
This behavior is controlled by Functional Storage.
Report the bug to them instead:
https://github.com/Buuz135/FunctionalStorage/issues
