### ISSUE TITLE
[Bug]: Better P2P not opening

### ISSUE THREAD

**Issue by LCoolJT** [ThePansmith/Monifactory#1107]
### Issue Summary

When aquering the Better P2P Memory card you can not use it on P2P tunnels like stated in the description.
Can be replicated in new worlds as well.
Applies to current version 0.10.
Uninstalling the modpack and reinstalling didnt fix it. 
The mod also has no keybinds.

### Reproduction steps

1.Have a AE2 Network with P2P
2.Click on the P2P Tunnel with the Better P2P Memory Card
3.It should open a gui but it does not

**Comment by Preladon** [comment]
I have this problem with EU P2P buses, but assumed it was because those come from the Modern AE2 Additions mod.

**Comment by LCoolJT** [comment]
Thanks, I just noticed that all my buses where EU as well so that explains the problem. Normal P2P works!

**Comment by ThePansmith** [comment]
Report to applicable devs
