### ISSUE TITLE
[Bug]: Release PSA for dedicated server 0.10.0 being broken

### ISSUE THREAD

**Issue by sillysimon** [ThePansmith/Monifactory#1111]
### Issue Summary

Hi,

this is a followup to #1103 . 
As the issue established, it is currently not possible to join a Server running Monifactory 0.10.0 due to an issue with Nuclear Craft Neo.
This applies to at least @InfinitiesLoop and me, possibly everyone.

Apart from the mentioned issue, I have not found any mention of this anywhere in this repo, except a vague "Nuclear Craft Neo is buggy" in the [Known Issues](https://github.com/ThePansmith/Monifactory/blob/main/KNOWN-ISSUES.md#other-issues-with-mods) .

I would greatly appreciate some kind of hint somewhere, ideally on the releases page of the update and Curseforge or just outright deleting the server release (given that it does not work).
Otherwise, other people might end up with a broken server.

Something like `Attention. The server for 0.10.0 is currently broken. See issue #1103 for further information.` would do the trick.

If this isn't as widespread as I thought, I would love to hear from people who managed to get the 0.10.0 server running (with being able to join) without any workarounds. If there is a workaround, it would be great to have a hint somewhere nonetheless.

Kind regards,
Simon

### Reproduction steps

see #1103 

### Relevant log output

see #1103

**Comment by ThePansmith** [comment]
Added to FaQ, report to NCN
