### ISSUE TITLE
[Bug]: Basic Extractor w/ ULV Conveyor Module Cover Crash (Expert mode)

### ISSUE THREAD

**Issue by Slickify** [ThePansmith/Monifactory#1118]
### Issue Summary

Basic Extractor w/ ULV Conveyor Module Cover closes single player world. (Playing on Expert Mode)

### Reproduction steps

1. Place Basic Extractor Above Basic Chemical Reactor
2. Go into Basic Extractor and place ULV Conveyor Module as Cover on Bottom face using the GUI
3. Press Gear symbol next to ULV Conveyor Module slot 
4. World closes, "Connection Lost, Server Closed" (playing on single player world)

**Comment by yamijuan** [comment]
happens as well in normal mode with fluid covers
