### ISSUE TITLE
[Bug]: Fluid Filter for Electric pumps / fluid regulator not working

### ISSUE THREAD

**Issue by yamijuan** [ThePansmith/Monifactory#1119]
### Issue Summary

After the update to 0.10.1 the fluid filters are not working, the GUI does not work
![image](https://github.com/user-attachments/assets/979e16fd-4fc0-4b89-86b3-a33ef9ab678d)

### Reproduction steps

1. Place a MV electric pump / fluid regulator as cover on top of an HV chemical reactor
2. Open GUI with Screwdriver
3. Add a fluid filter
3.1 Filter GUI does not work
4. close the GUI and it cannot be opened again with screwdriver

**Comment by circuitgamer77** [comment]
I'm experiencing a similar thing, but with the robot arm cover and no filter.  It crashes the game if I try to open the GUI by clicking on the icon in the machine, and if I access it with a screwdriver instead I can modify values but no settings are saved after closing the GUI.  I don't know if I should make a new issue for it, or assume it's the same issue as you found.

**Comment by ThePansmith** [comment]
Report to applicable mod devs
