### ISSUE TITLE
Lostcities loot table work

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#112]
- [x] First and foremost, the issue of it not consistently generating loot in chests needs to be fixed, may be an issue with the mod itself.
- [ ] Past that, I'm thinking the loottable could do with a couple of additions to better round it out. ULV Covers, spider eyes (for HNN crafting), silk touch books and such could be useful additions

**Comment by JuiceyBeans** [comment]
What do you think of adding small sodium batteries to the Lost Cities loot table?

**Comment by WithersChat** [comment]
The loot failing to generate is 100% a mod issue and not a modpack issue. Has been there since the 1.12 version of the mod.
