### ISSUE TITLE
[Bug]: Unable to change machine cover modes 

### ISSUE THREAD

**Issue by Sliverfish7584** [ThePansmith/Monifactory#1124]
### Issue Summary

When applying a cover to a machine, you are unable to change the cover's mode from export to import or import to export. 
This applies to all covers, such as conveyors, pumps and robot arms. It affects all machines 

Pack Version 0.10.1
### Reproduction steps

**Reproduction Steps**
1. Place a machine down and apply a cover to a face 
2. open cover GUI with screwdriver 
3. change cover mode from export to import
4. exit the cover GUI 
5. Cover will not work as expected, no items are pulled into the machine 
6. when re-entering the GUI, the mode has switched back to export

**Comment by MrRofl93** [comment]
I'm having the same problem.
Also when going to the input/output settings of a machine and click a surface where the robot arm is and click on the settings of the robot arm, it logs me out of single player and it shows me the server list.

**Comment by Sliverfish7584** [comment]
I didn't have an issue where the game crashed, it just won't let me change the export/import mode of the covers. it works perfectly fine on 0.10.0

**Comment by atj14** [comment]
I can change the ulv fluid pumps between export/import modes but it won't let me change the lv fluid pumps (version 1.10.1).

**Comment by atj14** [comment]
Updating to version 0.10.2 fixed the problem. Seems to have been a problem fixed with gtm v1.5.3.
