### ISSUE TITLE
{Server join Issue}

### ISSUE THREAD

**Issue by jirisek3** [ThePansmith/Monifactory#1133]
I am setting up a server for me and my friends and when I try to join I get this issue

internal exception java.lang.illegalArgumentException: unknown recipe serializer minecraft
client log from joining process
https://pastebin.com/YrdDNSKk
server log from joining process
https://pastebin.com/Ps54wdxp

**Comment by Preladon** [comment]
Take a look at the Known Issues page - it's the first one there. You make a change to one of the kubejs files to make this work.

https://github.com/ThePansmith/Monifactory/blob/main/KNOWN-ISSUES.md

**Comment by Preladon** [comment]
Yes, that's right. You modify line 34 (I think!) of the file kubejs/startup_scripts/_initial.js from

`global.unificationPattern = new RegExp(`^(?!(${global.UnificationExcludedItems.join('|')})).*(nuclearcraft|thermal|enderio):(powdered_.*|.*(_block|_plate|_ingot|_nugget|_gear|_dust))`, 'i')`

to

`global.unificationPattern = new RegExp(`^(?!(${global.UnificationExcludedItems.join('|')})).*(thermal|enderio):(powdered_.*|.*(_block|_plate|_ingot|_nugget|_gear|_dust))`, 'i')`

But be aware of the documented side effect, that some things that shouldn't be smelted in a furnace can now be.
