### ISSUE TITLE
[Bug]: Cant See Recipe (clicking r in nei) On Multiblock Projections

### ISSUE THREAD

**Issue by TonyBaloney2** [ThePansmith/Monifactory#1143]
### Issue Summary

 Cant See Recipe (clicking r in nei) On Multiblock Info Screen

**Comment by TonyBaloney2** [comment]
not a major issue just a little annoying when build multiblocks inside of a crafting terminal

**Comment by ThePansmith** [comment]
Report to applicable mod devs
