### ISSUE TITLE
[Bug]: Sophisticated Storage Storage Controller partially uncraftable

### ISSUE THREAD

**Issue by nidgithm** [ThePansmith/Monifactory#1144]
### Issue Summary

There are recipes for the Storage Controller from Sophisticated Storage, but the block in the middle is unobtainable. If this is intentional I would recommend removing the recipe.

### Reproduction steps

1. Look at the Storage Controller recipe in JEI
2. Click the block in the middle of the recipe.
3. See that it is unobtainable.

**Comment by MatthiasMann** [comment]
Huh - I crafted a lot of these - the block in the middle is just any drawer from this mod.
It should open a window when clicked showing all possible items which belong in that tag.
