### ISSUE TITLE
[Bug]: Fluids from JEI don't work reliable in level emitters

### ISSUE THREAD

**Issue by MatthiasMann** [ThePansmith/Monifactory#1149]
### Issue Summary

When setting up a level emitter for fluids (eg emit if less than 10B of chlorine is in the system) keeps emitting redstone even when hundreds of buckets are in the system.

The work around is to look up the recipe for chlorine from fluid stored in the ME system via an AE2 terminal - and then drag this fluid from the JEI/EMI history window into the level emitter.

### Reproduction steps

1. Place a machine making fluids (eg extractor, chemical reactor etc)
2. attach a machine controller and set it to inverted (requiring redstone to run)
3. put a level emitter on the machine and a ME interface (set the machine to export to the ME interface)
4. drag a fluid into the level emitter (eg from looking up electrolyzing salt), set the limit to eg 10B
5. put a stack of salt in the machine
6. watch it continue working after more than 10B are in the ME system

**Comment by ThePansmith** [comment]
Report to applicable mod devs
