### ISSUE TITLE
[Bug]: Quark hotbar swapper not functioning

### ISSUE THREAD

**Issue by rocketjohn** [ThePansmith/Monifactory#1172]
### Issue Summary

I have enabled it via quark config on client side, and it also seems to be enabled on the server - I have also de-conflicted the 'z' keybind, but the swapper is still not working.

### Reproduction steps

1. Enable hotbar swapper in quark settings in the mod options menu.
2. Sort out key conflicts so that there is a unique button for swapper
3. Press the button - no swapper interface appears.

**Comment by Xefyr0** [comment]
The hotbar swapper is disabled by default in Monifactory.
If you're having an issue with functionality managed by Quark, report the issue to them instead:
https://github.com/VazkiiMods/Quark/issues
