### ISSUE TITLE
[Feature]: Put the pack on modrinth

### ISSUE THREAD

**Issue by Correlander** [ThePansmith/Monifactory#1173]
### Suggestion

I very much dislike Curseforge as a launcher and IMO Modrinth is just better at being a launcher, this feature request is me humbly requesting this pack gets hosted on Modrinth.

**Comment by ThePansmith** [comment]
> I very much dislike Curseforge as a launcher
Install prism launcher

Past that, getting the modpack on modrinth logistically isnt a option
