### ISSUE TITLE
[Bug]: Problem with EnderIO conduits not transferring power

### ISSUE THREAD

**Issue by MoniIssues** [ThePansmith/Monifactory#1184]
### Issue Summary

Version 0.10.4
When i replace lumium EnderIO conduits with signalum EnderIO conducts by right clicking the lumium conduits, the signalum conduits that replace the lumium conduits DO NOT transfer any power. however when signalum conduits are placed normally they transmit power as they should, i have not tested this with other tiers of conduits. My pack is not modified

### Reproduction steps

Replacing conduits

**Comment by Xefyr0** [comment]
Yes, this is an issue with EnderIO and not Monifactory.
Report the issue to them instead:
https://github.com/Team-EnderIO/EnderIO/issues
