### ISSUE TITLE
[Bug]: editing nuclearcraft fission reactor while running makes it consume no fuel

### ISSUE THREAD

**Issue by minecrafterseppe** [ThePansmith/Monifactory#1186]
### Issue Summary

when u edit a nuclearcraft fission reactor while it is running, and then turning it on and off after reassembling, makes it run without using fuel without producing depleted fuel but it still produces energy 

https://youtu.be/b9NkNi4OQyA

### Reproduction steps

construct fission reactor

feed it fuel

break any block on it (no ports or controller)

replace them

turn reactor on off

boom infinite energy with no fuel consumption

**Comment by ThePansmith** [comment]
Is this monifactory specific?

**Comment by minecrafterseppe** [comment]
mostlikely not and just relating to nuclearcraft

**Comment by ThePansmith** [comment]
Report to NCN
