### ISSUE TITLE
[Bug]: Smart filter resets when used with robotic arm inside an input bus

### ISSUE THREAD

**Issue by DrUse1** [ThePansmith/Monifactory#1191]
### Issue Summary

Everything is explain in the title,
I have a large centrifugal unit, I put a robotic arm with the smart filter set to "centrifuge", when I reconnect on my world, the smart filter resets to the default setting which is the electrolyzer.

### Reproduction steps

- Put robot arm with smart filter set to Centrifuge on an input bus
- Disconnect
- Reconnect
- Check the robot arm

**Comment by ThePansmith** [comment]
Is this monifactory specific?

**Comment by Xefyr0** [comment]
Not likely.
I'm convinced it's really an issue with Gregtech: Modern instead. Report the issue to them:
https://github.com/GregTechCEu/GregTech-Modern/issues
