### ISSUE TITLE
[Bug]: Unintended magnetic iron foil recipe 

### ISSUE THREAD

**Issue by breck768** [ThePansmith/Monifactory#1192]
### Issue Summary

Iron foil recipe results in magnetic iron foil, this is the only magnetic iron foil recipe and normal iron foil seems to be disabled
Expert mode and the addition of the latest create version are the only changes ive made
![Screenshot 2024-12-01 095346](https://github.com/user-attachments/assets/fba1c2a9-a4b2-4fd9-aa61-261d2d593fa3)

### Reproduction steps

iron plate and hammer in crafting grid lol

**Comment by Xefyr0** [comment]
This issue is called by Gregicality Rocketry. Report the issue there:
https://github.com/Argent-Matter/gcyr
