### ISSUE TITLE
[Feature]:Holmium is too expensive

### ISSUE THREAD

**Issue by XNFu233233233** [ThePansmith/Monifactory#1195]
### Suggestion

Since I got Creative Energy Data, I have been producing holmium, but it is still not enough. UIV needs a lot of holmium.
Using EMI to calculate the materials required for Creative Quantum Chest, only looking at the number of Monium Ingots, it needs 1200+, which requires 20 level 12 microminers, and an additional 10 level 12 microminers, a total of 30 units.
A level 12 microminer requires 3000 holmium. 9 level 11 microminers can almost get this much holmium. This means that just to make the required level 12 microminers, 270 level 11 microminers are needed.
Adding the remaining approximately 12,000 holmium, a total of 34 level 12 microminers are needed. That is, a total of 306 level 11 microminers are needed.
This amount does not seem to be much in expert mode, but in the later stage, there is only this one thing, constantly making holmium. It is too boring, not to mention that various bugs in gtm and ae cause synthesis to get stuck, and there is only one way to get holmium.
The above only calculates the holmium required for the Creative Quantum Chest. UIV requires a lot of holmium. A 2a energy input warehouse requires 88 holmium, and a 16a requires 198 holmium.
The output probability of holmium should be slightly increased, or other ways to obtain it should be added to enrich the later content.

**Comment by Xefyr0** [comment]
Holmium output of T11MM increased by 50% in [this](https://github.com/ThePansmith/Monifactory/commit/fa61955393c6d5aa0f285e6a40f5a66245d446a9) commit.
