### ISSUE TITLE
[Feature]: Surface Ore Indicators sucks ass.

### ISSUE THREAD

**Issue by wwwname** [ThePansmith/Monifactory#1208]
### Suggestion

**Surface Ore Indicators** looks bad and makes world look worse. Especially because of starting with prospector these Surface Ore Indicators becomes completely obsolete. 
Here thing you might be interested in: https://gregtechceu.github.io/gtceu-modern-docs/Modpacks/Examples/Removing-Ore-Piles/

**Comment by ThePansmith** [comment]
Monifactory removed surface ore piles at one point, but we changed our mind on it.

You are welcome to do it in your own instance, though.
