### ISSUE TITLE
[Bug]: Tooltip from GregTech machines overlaps with EMI UI

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#121]
### Issue Summary

![2024-04-27_12 09 12](https://github.com/ThePansmith/Monifactory/assets/53749130/9abc704d-65c5-4731-8860-e2c1c974f025)

### Reproduction steps

Open a GregTech Machine and hover the mouse on the i at the top right of the interface

**Comment by ThePansmith** [comment]
GTm issue, please report it to them.
