### ISSUE TITLE
Crystal Matrix Overhaul

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#1211]
## To be done on the posttankmats branch 

Overhaul Crystal Matrix from being a simple diamond sink into a line focused around nanotubes. 

I've attached some of the responses from the feedback form (GPT'd to look better with markdown) to use/work off of/etc.

<details> 
  <summary>Community Submitted Idea A</summary>
  
### Plastic:

- **144mB Liquid PE** = 1 plastic  
- **144mB Liquid PVC** = 2 plastic  
- **144mB Liquid Epoxy** = 4 plastic  
- **144mB Liquid PTFE** = 8 plastic  
- **144mB Liquid PBI** = 16 plastic  

---

### Crystal Matrix Process:

- **32 plastic tiny pipe + IV Field Generator** → **32 Matrix Tubing**  
- **4 Matrix Tubing + 4 IV Circs + 1 LuV Emitter** → **Prepared Matrix Frame**  
- **1 Perfect Diamond + 16 Sapphires (or Green Sapphires) + 32 Diamonds + 1 Frame** → **1 Unfired Crystal Catalyst**  
- **1 Unfired Crystal Catalyst** in **EBF** (ZPM Trinium, optional Krypton for speed boost) → **1 Fired Crystal Catalyst**  
- **1 Fired Crystal Catalyst (NC) + 1 LuV Sensor + 4 LuV Electric Motors + 8 IV Circs** in a **ZPM Assembler** for 30 sec → **1 Uncut Crystal Matrix**  
- **Uncut Crystal Matrix + Red Lens (NC)** in **EV Precision Laser Engraver** → **1 Prepared Crystal Matrix**  
- **1 Prepared Crystal Matrix + 1 Crystal CPU** in **LuV Cutting Machine** → **32 Crystal Matrix Plates**

---

### Total Cost for 32 Plates:

- **1 Perfect Diamond**  
- **16 Sapphires**  
- **1 IV Field Generator**  
- **32 plastic**  
- **1 LuV Emitter**  
- **12 IV Circs**  
- **1 LuV Sensor**  
- **4 LuV Electric Motors**  
- **1 Crystal CPU**
- **NC: Red Lens**

---

### Benefits:
- More circ parts  
- Fewer diamonds  

---

### Downsides:
- Requires solid **HSS-S production** for the large number of **LuV parts** needed for **32 Crystal Matrix Plates**.  
- **Red Lens** isn’t a problem since players need it for **Integrated Logic Circs**, and at worst, it’s discarded after early-MV.
</details>
<details> 
<summary>Community Submitted Idea B</summary>
You could have multiple ways of making them, such as:

- **Arc Furnace**:  
  - Lower energy cost/tier  
  - Lower yield

- **Laser Engraver**:  
  - Higher energy cost/tier  
  - Higher yield

---

Carbon refining and compressing, similar to the process used for industrial diamonds in the past, would be cool. It could also serve as a use for the millions of carbon I produce. The process might look something like:

1. **Centrifuging** for purified carbon.
2. **Bathing in distilled water** for refined carbon.
3. **Autoclaving** liquid refined carbon with graphene dust.
4. **Compressing** the mixture into a raw graphite target.
5. Using the raw graphite target to make **nanotubes**.
 </details> 
<details> 
  <summary>Community Submitted Idea C </summary>
There's a ton of physical chemistry you could draw on in this area. The process could work like this:

1. Start with a **quartz plate with nichrome coating** (chem reactor recipe).
2. Place the plate into a **blast furnace** or a new **multi-block furnace** as a catalyst.
3. Use **acetylene** or **ethylene** to cook up the nanotubes directly, or:
4. Add another process to **collect** the nanotubes.
 </details> 
<details> 
  <summary>Community Submitted Idea D</summary>
  
### 1. Preparing the Substrate:
- The first step is to prepare a substrate for the carbon nanotubes. While various materials could be used, for thematic consistency with the ingot, the initial material could be **perfect diamonds** mixed with any metal dust (commonly, **nickel**, **cobalt**, or **iron** are used in industry).
- If you want a more expensive approach, you could use **naquadah** instead.

### 2. Turning Metal Dust into Nanoparticles:
- The metal dust needs to be converted into **nanoparticles** with a  **atomic reconstructor** 

### 3. Adhering Nanoparticles to the Substrate:
- Once the nanoparticles are ready, they must be adhered to the substrate.
- This process involves **annealing** the metal catalyst onto the substrate. A **thermal centrifuge** would be more suited to this task than an **arc smelter**.

### 4. Growing the Nanotubes:
- After the substrate is prepared, it should go into an **arc furnace**, where two gases need to be pumped in:
  - A **noble gas** (I recommend **Krypton**)
  - A **hydrocarbon gas** (such as **ethylene**)
- This is the longest step in the process and, instead of producing a crystal matrix, it will yield a **grown nanotube substrate**.

### 5. Aligning the Nanotubes:
- The next step requires the **circuit assembler**, which is the only machine capable of working at the small scale needed.
- The nanotube substrate must be processed into an **aligned nanotube substrate**.

### 6. Adhering and Compressing the Nanotubes:
- Once the nanotubes are aligned, they need to be adhered together using **liquid nether stars** in a **chemical bath**. This will create a **porous crystal matrix precursor**.
- The precursor then goes through an **implosion compression** process, turning it into a **dense crystal matrix precursor**.

### 7. Final Step - Blast Furnacing:
- Finally, the precursor is blast-furnaced to produce the final **crystal matrix**.
 </details>

**Comment by Lasrer** [comment]
Here's what I came up with: https://github.com/ThePansmith/Monifactory/pull/1239
