### ISSUE TITLE
[Bug]: Thermal Element Data Model unintended recipe?

### ISSUE THREAD

**Issue by AbhijeetMankani** [ThePansmith/Monifactory#1226]
### Issue Summary

Thermal Element Data Model unintended recipe?!
It seems like the Thermal Element Data Model can be crafted in a peaceful mode without ever making the Elemental Reduction Fluid when playing in normal mode. However, the questbook seems to want you to either make it or not be playing in peaceful mode.

[Unintended Recipe Tree](https://github.com/user-attachments/assets/2c57d116-8370-4e9e-8d76-1149acf53824)
[Quest](https://cdn.discordapp.com/attachments/1314654296318541875/1314654297316659240/image.png?ex=67548eb9&is=67533d39&hm=a7be34ae10bc8f5353c6c3c4d028159594c81a487fa681256157ae249b7476a9&)

Normal mode
0.10.5wants

### Reproduction steps

It seems like the Thermal Element Data Model can be crafted in a peaceful mode without ever making the Elemental Reduction Fluid when playing in normal mode. However, the questbook seems to want you to either make it or not be playing in peaceful mode.wants

**Comment by ThePansmith** [comment]
Actually, gonna work that into being a feature instead.

**Comment by AbhijeetMankani** [comment]
Glad I could help. 🙇
