### ISSUE TITLE
[Bug]: The feedback button on the main menu leads to a broken screen

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#1233]
### Issue Summary

I don't believe it's what it's supposed to look like
![2024-12-07_11 09 33](https://github.com/user-attachments/assets/9aa890b9-39df-4eea-b6ce-dcaaea20a933)

### Reproduction steps

Ckick on the feedback form button

**Comment by ThePansmith** [comment]
That's an easteregg to view the Main Menu images in full screen. You can't click on the link.
