### ISSUE TITLE
[Bug]: Recipe overlap between resin printed circuit boards and large wood fluid pipes in the assembler [Modpack version 0.10.4]

### ISSUE THREAD

**Issue by Darktemplarx** [ThePansmith/Monifactory#1235]
### Issue Summary

Both resin PCBs and large wood fluid pipes require wood planks, glue, and programmed circuit 2, leading to the assembler crafting pipes when I'm trying to craft circuits.

### Reproduction steps

1. Insert glue, wooden planks, and copper foil into a LV assembler programmed with circuit 2.
2. The insertion order determines what it starts crafting. If you put in the wood planks first then it starts making wood pipes. However resin PCBs also require copper foil, so if the foil is in the machine before the planks then it crafts PCBs properly.

Suggestion: change the programmed circuit required for one of the recipes. 
That is unless this was already fixed in 0.10.5, but I didn't see it in the detailed change log.

**Comment by Xefyr0** [comment]
Fixed in [this commit.](https://github.com/ThePansmith/Monifactory/commit/835222463e236e96e467a7f6655c00ad927a8d94)
