### ISSUE TITLE
[Bug]: Manual I/O resets after world save.

### ISSUE THREAD

**Issue by DadoPF** [ThePansmith/Monifactory#1254]
### Issue Summary

![2024-12-14_16 30 23](https://github.com/user-attachments/assets/06d4c675-1896-43e9-8dd3-8a3aa6d77d26)
As stated, manual I/O filter resets after world save.

### Reproduction steps

1. Put a cover in a machine.
2. Toggle manual I/O filter.
3. Open and close world/game.
4. Check machine cover and see it reset itself.

**Comment by ThePansmith** [comment]
Report to applicable devs
