### ISSUE TITLE
[Bug]: Advanced Microverse Projector does not take input hatches

### ISSUE THREAD

**Issue by dreed-sd** [ThePansmith/Monifactory#1261]
### Issue Summary

It's unclear to me if this is intentional. If so the quest book maybe should mention it.

I had the Basic Microverse Projector, and upgraded it to Advanced. Now I can no longer run most Tier 1, 2, and 3 missions, because they require Rocket Fuel as an input.

### Reproduction steps

1. Setup a Basic Microverse Projector multiblock
2. Enjoy being able to run a tier 1, 2, and 3 mission that takes Rocket Fuel
3. Upgrade your Microverse Projector multiblock to an Advanced One. The structure will not be complete if there are any input hatches.
4. --> You can run Tier 4, 5, and 6 missions, but no longer Tier 1, 2, or 3 recipes which require Rocket Fuel (since you can't provide Rocket Fuel without an input hatch)

**Comment by Xefyr0** [comment]
Higher-tier microverse projectors aren't able to run lower-tier missions.

The only exception to this rule is the Hyperbolic Microverse Projector, which you can manually switch to a mode that lets you run lower-tier recipes faster.
