### ISSUE TITLE
[Bug]: tool-tips of GT ore veins in JourneyMap overlap on one another

### ISSUE THREAD

**Issue by ZnxTech** [ThePansmith/Monifactory#1265]
### Issue Summary

Prospecting 2 or more GT ore veins in a single ore chunk makes it so the tool-tip in JourneyMap is hard to, to practically impossible to read.

example:
![screenshot](https://github.com/user-attachments/assets/d10950d6-be62-4aa5-b01b-33f55fa0d89b)

### Reproduction steps

1) enter a world
2) use the prospector starter tool and prospect 2 veins in a single ore chunk
3) open JourneyMap and enable GT ore veins
4) hover over the 2 veins
5) tool-tips overlap

**Comment by ekconcordian** [comment]
I'll second this - on generating a new world on an unmodified 0.10.4 / 0.10.5 Curseforge instance, it looks like every ore chunk is affected by this issue. I believe this is Overworld only; Nether is unaffected as only one vein spawns per ore chunk. You can see the icons for the veins overlapping each other. Two veins per ore chunk is a cool idea but I'd guess we'd want both the icon & the text to be separated out in some way for visibility.
![image](https://github.com/user-attachments/assets/2f74a301-4dbc-43c2-b490-b4f6f7aca0a9)

**Comment by anoldshoe** [comment]
Same issue shown above

**Comment by dominikh** [comment]
This is fixed by #1259
