### ISSUE TITLE
[Bug]: AE2 pattern encoding misscounts

### ISSUE THREAD

**Issue by 4dam3k** [ThePansmith/Monifactory#127]
### Issue Summary

Whenever I try to encode circuit pattern:
- Fluid does not transfer (idk if it's supposed to or not)
- Some items are in wrong counts, from what I see its because of "#gtceu:resistors" instead of exact type of resistor

![image](https://github.com/ThePansmith/Monifactory/assets/66412368/ba8b6ff0-884b-4843-8a23-4e5eb665d90e)
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/659b1f14-922f-4e29-99dc-2462db5f1564)

### Reproduction steps

1. Open recipe of circuit (tried with MV and HV circuit)
2. Fill the recipe into ae2 pattern encoder
3. Cry and fix the recipe manually

**Comment by 4dam3k** [comment]
When filling this recipe: 
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/f5657cd7-5bab-4a87-98bb-5ef246ae00ff)
The fluid fills too, so the fluid problem is because of #forge:tin

**Comment by Blackalf14** [comment]
We could make sure every fluids are well unified to remove stuff like the molten tin tag in recipes but we can't do much for the tags that are actually relevant and let you use different type of a component. It is up to the player choice in the end and they will very likely have to change the recipe by themself. It's still weird that they don't get the right amount in the first place however, maybe an EMI bug?

**Comment by ThePansmith** [comment]
Seems to be a GTm issue, please report it to them.
