### ISSUE TITLE
[Bug]: Prism Launcher (and curseforge) show 10.4 despite updating to 10.5

### ISSUE THREAD

**Issue by arjunivor** [ThePansmith/Monifactory#1272]
### Issue Summary

Updating from prism launcher still incorrectly shows that the version of the modpack is 10.4 even though it might be running 10.5. The same issue happens using the curseforge launcher. This bug might prevent you from properly joining your own server because the server thinks you have a different version. Deleting and starting from scratch doesn't fix this issue, and manually downloading the file and updating from file does not fix this issue either. 

### Reproduction steps

1. in prism launcher, right click on Monifactory and hit edit -> go to curse forge -> update version to latest(10.5 as of this writing). after updating, the launcher will still show that the version is 10.4 despite updating. Same issue persists on curseforge.

**Comment by AkiVonAkira** [comment]
I think the manifest.json version is still 0.10.4.
