### ISSUE TITLE
[Bug]: Cannot use Any Integral Component for Thermal machines.

### ISSUE THREAD

**Issue by TianmuLong** [ThePansmith/Monifactory#1283]
### Issue Summary

Any Tier of Integral Components don't work and can't be placed in machine.

### Reproduction steps

Using PrismLauncher 9.1
Download MoniFactory 0.10.5(But it's displayed as 0.10.4 in PrismLauncher?)
Boot and Try.

**Comment by Bromhir84** [comment]
Are you using a crafted Integral Component?
Or did you spawn one from EMI? <-- These will not work, something about the nbt data seems to be messed up when spawning them

**Comment by TianmuLong** [comment]
> Are you using a crafted Integral Component? Or did you spawn one from EMI? <-- These will not work, something about the nbt data seems to be messed up when spawning them

You're right.
I just spawn them in EMI to test and though it would work fine.
