### ISSUE TITLE
[Bug]: 4a energy hatch does not allow next tier recipes

### ISSUE THREAD

**Issue by RLeendertz** [ThePansmith/Monifactory#1291]
### Issue Summary

A multiblock machine with 1 4a energy hatch, can overclock to the next tier of power, but not run recipes of that tier.

The same machine with 2 2a energy hatches can run the next tier recipes.

![afbeelding](https://github.com/user-attachments/assets/22f7debb-8fc0-4ec7-8204-3829518e3f5a)

### Reproduction steps

1. Build an LCR with a 4a EV energy hatch
2. try to run an IV recipe.
3. ...

Here are some test examples of an EBF with EV energy hatches:

![afbeelding](https://github.com/user-attachments/assets/4ade67a2-160d-4450-be44-524df8b1a3e1)
![afbeelding](https://github.com/user-attachments/assets/6ebd20d2-3f6f-4c71-a091-222c5ca5ec8a)
And with 2 2a energy hatches they work fine:
![afbeelding](https://github.com/user-attachments/assets/304d0def-ef04-408f-9865-26de174f954e)
![afbeelding](https://github.com/user-attachments/assets/3cf6a00a-d95d-4f52-945c-812edee77fb6)

After testing with different tiers of energy hatches and also 16a ones, they all just allow overclocking, not recipes of higher tiers.
![afbeelding](https://github.com/user-attachments/assets/df250428-5d74-4baa-a8fb-eeba6360662b)

**Comment by jtuc** [comment]
Sorry, not a bug; this is by design. The TLDR version is that you must always have 2 hatches to tier skip.

The long version, from the GTCEu discord:

> ### Overclock vs. Recipe Tier Skip
> Recipe Tier Skip and Overclock are easily conflated especially since overclock cannot be triggered independently before EV. However, understanding the difference can save you time and resources!
> #### Recipe Tier Skip
> Recipe Tier Skip refers to the ability of a multiblock to perform recipes of the next tier. For example, using LV Energy Hatches in an Electric Blast Furnace to smelt Aluminium. To trigger this, you MUST have two hatches of the same tier. Amperage of these hatches does not matter, you must have TWO of them. Additionally, you are limited to ONE recipe tier skip, regardless of the amps you have.
> #### Overclock
> For multiblocks, overclock refers to their ability to run at a higher voltage tier than their energy hatches, given enough amps. If your hatches total 4A you get one overclock, and if they total 16A you get two overclocks. Doing this before EV requires the use of two hatches (each supporting 2A), and therefore will also involve a Recipe Tier Skip. However, using a single 4A or 16A hatch is enough to trigger one or two overclocks respectively, and will not trigger a Recipe Tier Skip, as that strictly requires TWO hatches.
> #### Hatch Sharing
> Given the conditions of overclocking, if a multiblock only has a single 2A hatch or has two 4A/16A hatches, there will be unused amps since multiblocks will not attempt to draw 2A, 8A, or 32A. If you do not want tier skip OR overclock, you can share a single 2A energy hatch between two multiblocks to give each one 1A. Post-EV, if you want tier skip AND overclock, then share a pair of 4A/16A hatches between two multiblocks. This fulfills the "two hatch" requirement for recipe tier skip and provides 4A or 16A to each multiblock. Note however that you should avoid sharing a pair of 2A or a single 4A/16A between multiblocks because that will not leave any unused amps for the second multiblock in the pair to run.
