### ISSUE TITLE
[Bug]: ULV Robot Arm and Fluid Regulators only accept Vacuum Tubes

### ISSUE THREAD

**Issue by MoltonMontro** [ThePansmith/Monifactory#1292]
### Issue Summary

Unlike other ULV-tier items, the Robot Arm and Fluid Regulator can _only_ accept Vacuum Tubes. NAND Chips and ULV Universal Circuits aren't accepted.

### Reproduction steps

1. Try and craft one of these (e.g. ULV Robot Arm) with a ULV Universal Circuit (or NAND Chip).
2. Be sad that this fails.

**Comment by ThePansmith** [comment]
Report to mod dev
