### ISSUE TITLE
Nuclearcraft Sulfuric acid is useless

### ISSUE THREAD

**Issue by CestQuoiUnPseudo** [ThePansmith/Monifactory#131]
### Issue Summary

![image](https://github.com/ThePansmith/Monifactory/assets/96011112/02b234a3-de24-403a-8bdf-c896146d4f82)
No recipe, less uses than gregtech's, and as Aubrey said on the discord:
![image](https://github.com/ThePansmith/Monifactory/assets/96011112/46c5516b-bb7f-473a-b981-f05d9b4e9030)

Also wondering what other liquids from NC are duplicates. I haven't checked much
EDIT: Liquid Glowstone? 3 different ones?

### Reproduction steps

1. Look at a recipe using sulfuric acid
2. Realize that, as a player, there's only one real sulfuric acid

**Comment by 4dam3k** [comment]
Same with tin, as it messes craftings
