### ISSUE TITLE
[Feature]: Rubber Drawers

### ISSUE THREAD

**Issue by JuiceyBeans** [ThePansmith/Monifactory#134]
### Suggestion

Rubber drawers does not exist for Functional Storage on Modern, either make a recipe that uses rubber planks and gives an oak drawer or wait until Pansmith eventually makes Rubber Drawers Modern

**Comment by ThePansmith** [comment]
Being worked on

**Comment by ThePansmith** [comment]
Forgot to update this; rubber drawers are done
