### ISSUE TITLE
[Bug]: Sky changes colors

### ISSUE THREAD

**Issue by FooterManDev** [ThePansmith/Monifactory#135]
### Issue Summary

The sky appears to be switching from a darkish look to the normal MC look when I'm sprinting around my world:
https://imgur.com/a/xMHmMbx
I'm not running any commands, it just happens. And its not when switching biomes, I've seen the sky spazz out before, while running in a Plains.

### Reproduction steps

Load a default world (I have LostCities mod disabled because I couldn't turn them off manually)
Sprint around. It didn't happen for me until 10 minutes in.

**Comment by ThePansmith** [comment]
Report to mod dev
