### ISSUE TITLE
[Feature Request]: Replace Rechiseled with any other chisel mod 

### ISSUE THREAD

**Issue by Leclowndu93150** [ThePansmith/Monifactory#139]
### Suggestion

Im just saying this because the mod by itself adds about 1.7GB more to the ram usage which makes the modpack not run on 5gb of ram anymore. even worse my 8gb of ram allocation was maxed out

**Comment by WithersChat** [comment]
Uh... when's the last time you updated the pack? The mod has been taken out of the pack quite a while ago by now. Replaced with Chipped.

**Comment by Leclowndu93150** [comment]
> Uh... when's the last time you updated the pack? The mod has been taken out of the pack quite a while ago by now. Replaced with Chipped.

Like 3 days ago..
