### ISSUE TITLE
[Bug]: Effortless building Elastic Hand not actually consumed after use

### ISSUE THREAD

**Issue by CosmicFyre** [ThePansmith/Monifactory#144]
### Issue Summary

After using the Elastic hand, going into inventory and clicking the slot it was in will pick it up again when it should be consumed, it may then be re-inserted and used again in this way

### Reproduction steps

Obtain an Elastic hand then right click while holding it to consume it and increase the relevant stat by 1 level. Go into your inventory and click the slot where the hand was, and it will reappear. Place back into inventory and repeat

**Comment by ThePansmith** [comment]
Likely a EB issue, report it to them.
