### ISSUE TITLE
[Proposal]: Add Pipez as an alternative to EIO conduits/GT pipes

### ISSUE THREAD

**Issue by Jaymus3** [ThePansmith/Monifactory#149]
### Suggestion

Currently EIO conduits are in a pretty unfinished state compared to older versions of the game and do not support item filtering and upgrading.  GT pipes support this and are very scalable but they are relatively complicated compared to the simplicity of an item or fluid conduit.  [Pipez](https://www.curseforge.com/minecraft/mc-mods/pipez) is simple yet effective and isn't as generally buggy as EIO conduits right now.  Example:

This is a simple brewery into a Super Tank setup and the fluid conduit is just incapable of sucking the fluids out.
![2024-05-02_10 48 07](https://github.com/ThePansmith/Monifactory/assets/1351081/e6bdeaef-8b76-45c9-9ebd-bd7687e3a841)
Pipez can actually pull the fluids out properly:
![2024-05-02_10 48 00](https://github.com/ThePansmith/Monifactory/assets/1351081/80363371-b519-4459-b24c-c64a2058f2e1)

I also set up a basic system to produce vinyl chloride, which makes hydrochloric acid as a byproduct.  Pipez destination filters can filter the GT fluids and send them where you want:
![CleanShot 2024-05-02 at 11 01 58](https://github.com/ThePansmith/Monifactory/assets/1351081/9b25160b-9462-41f7-b120-e329ff9eafe2)
Additionally, the transfer rates of items and fluids can be configured to your liking to put the pipes in a spot that feels appropriately balanced when compared to Gregtech pipes.  

**Known Limitations:**
-Energy pipes don't send energy into GT energy converters, and should probably just be disabled as they'd cause balance issues with energy conduit progression anyway.
-The ultimate pipes seem to be a little finicky in this version.  I had inconsistencies using the destination tool with them and would suggest that they're just disabled, especially since I think the energy pipes should just be disabled and it wouldn't be easy to remove them from the ultimate pipes.
-Upgrades work for all pipes, so upgrades would have to be balanced around affecting all pipes from the mod (not a big deal if energy pipes are disabled).

Thanks for taking the time to review my proposal.

**Comment by 4dam3k** [comment]
I think the biggest issue with playing on 1.20 compared to 1.12 is lack of proper mechanic that conduits did, one block transfer
The state that enderio is currently in is worse than bad, lack of filters, lack of speed upgrades (and overall bugginess of conduits)
The gregtech pipes are upgradable, however there is no option to move items and fluids in the same block
We should find a way to make that possible, one option is to use Pipez (however, as the Jaymus said, energy pipez mess with progression). Maybe we can find other solutions to this problem

**Comment by ThePansmith** [comment]
The conduits are currently getting their upgrades ported, but if this stalls out I'll consider it
