### ISSUE TITLE
[Feature]: Add "Monazite" Jade addon to the pack

### ISSUE THREAD

**Issue by 4dam3k** [ThePansmith/Monifactory#151]
### Suggestion

It's a Jade Addon for GregTech

Link here: https://modrinth.com/mod/monazite
From what I see it's not on curseforge (idk if that's an issue)

![image](https://github.com/ThePansmith/Monifactory/assets/66412368/203e8b36-3f50-40e0-820c-9c74c48898b9)
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/e880f75d-cf8d-42e2-abe1-13926203fdf8)

It shouldn't conflict as it's just a Jade Addon

**Comment by JuiceyBeans** [comment]
Should be closed, added in #115
