### ISSUE TITLE
Machine and multi stuffs

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#156]
General
- [x] Set minimum required casings on all multis

Resonator
- [x]  Remove, merge its recipes into the Atomic Reconstructor

Atomic Reconstructor 
- [ ] Custom front face texture

Creative tank replicator 
- [x]  Being expanded into the matter replicator, also allowing it to dupe Creative data hatches and storage upgrades
- [x] New Multiblock shape to match

**Comment by WithersChat** [comment]
I can do points 2, 4, possibly 5, I can learn how to do 1 and I can get our pre-existing MBs to have connected textures.

(Also, you sure you want it to be a replicator and not to construct stuff from data like you mentioned before?)

**Comment by WithersChat** [comment]
In other words, you can assign this to me if you want.

**Comment by WithersChat** [comment]
Everything here is done except the Atomic Reconstructor texture

**Comment by ThePansmith** [comment]
Just gonna move that to issue 1 lole
