### ISSUE TITLE
Updating Draconic Evolution

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#157]
- [ ] Update the mod
- [ ] Add fusion recipes

**Comment by WithersChat** [comment]
Wait, DE got Fusion back in?

**Comment by ThePansmith** [comment]
> Wait, DE got Fusion back in?

Yes, DE has been updated, will need to build it from source though.
https://github.com/Draconic-Inc/Draconic-Evolution

**Comment by JuiceyBeans** [comment]
Are we going to continue using the Fusion Reactor multiblock or use DE?

**Comment by ThePansmith** [comment]
Closing this for now as we are unable to build DE.
