### ISSUE TITLE
Updating GTM

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#158]
- [x] Update GTM, GCYR, GTSA
- [ ] Finish #4
- [x] Remove rubber wood related temp recipes

**Comment by ThePansmith** [comment]
Please report that to GTM

**Comment by 4dam3k** [comment]
> Also: new GTM have tanks and fluid hatches locking broken, using pipe or autoexport bypasses the blocking feature in tank, and LCR still puts fluid how it wants

Got fixed in 1.2.1-build_631
