### ISSUE TITLE
[Feature]: Increased Ore Density in Veins

### ISSUE THREAD

**Issue by vinni57** [ThePansmith/Monifactory#162]
### Suggestion

Presently, the ore density in veins is very sparse, and it takes a long time to dig them out only for a limited amount of raw ore. Eg, 45 minutes of nonstop mining provided only 8 stacks of various ores.

This results in several other unexpected problems that arise from the lack of ore density:

1. Mining out an entire vein is harder. When manually mining out a vein, it's common to try and dig out the entire thing. However, when there is so much stone between occurrences of ores, it is incredibly difficult to judge the boundaries of an ore vein when large swathes of stone separates occurrences of ores.
2. More time will be spent mining than actually progressing. The 45 minutes I spent mining overshadowed the 15 minutes I spent smelting the ores, and using them to craft 8 diamond furnaces. I had a stack each of coal, iron, copper, silver, gold, and diamond, and I spent them all in an instant once they were smelted. Even in LV, 8 stacks of materials can easily be consumed within 30 minutes when crafting components and the required machines.
3. It brings back a level of tedium that Omni/Nomi worked to remove. Even with the starting diamond hammers (and using cheats to give them Efficiency 5), mining feels like an utter chore with how minimal the gains were, especially compared to this modpack's predecessors.

Please consider increasing ore density, by at least a factory of 2.5, to improve this aspect of the pack.

**Comment by matcool** [comment]
Somewhat related to this, in my early game experience copper was much more tedious to mine in this pack than in NomiCEu, due to the veins being much smaller in size compared to in 1.12

**Comment by vinni57** [comment]
Agreed matcool. The veins seem to be like actual veins (long and stringy) instead of the circles that are easy to mine out. Once again, this makes it hard to judge boundaries and mine out the entire thing without accidentally collecting tons of another unneeded vein's ores.

**Comment by WithersChat** [comment]
I am 100% in agreement with this, but actually implementing this might be much harder than just changing a number in a config file, so there's that.

**Comment by matcool** [comment]
> I am 100% in agreement with this, but actually implementing this might be much harder than just changing a number in a config file, so there's that.

I think it's doable with just kubejs, at least this seems to work:
```js
event.remove("gtceu:magnetite_vein_ow")
event.add("gtceu:magnetite_vein_ow", vein => {
    vein.clusterSize(30)
    // vein.density(0.15)
    vein.density(0.5) // make it more ores or whatever
    vein.weight(80)
    vein.layer("stone")
    vein.dimensions("minecraft:overworld")
    vein.biomes("#minecraft:is_overworld")
    vein.heightRangeUniform(10, 60)
    vein.layeredVeinGenerator(generator => generator
        .buildLayerPattern(pattern => pattern
            .layer(l => l.weight(3).mat(GTMaterials.Magnetite).size(2, 4))
            .layer(l => l.weight(2).mat(GTMaterials.VanadiumMagnetite).size(1, 1))
            .layer(l => l.weight(1).mat(GTMaterials.Gold).size(1, 1))
        )
    )
})
```
Put this in: https://github.com/ThePansmith/Monifactory/blob/main/kubejs/server_scripts/gregtech/Custom_Ore_Veins.js
Based off: https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/common/data/GTOres.java#L604-L619
