### ISSUE TITLE
[Bug]: Moon stone has no drops

### ISSUE THREAD

**Issue by ToasterDan** [ThePansmith/Monifactory#168]
### Issue Summary

**Moon stone** seemingly doesn't drop anything when mined with a pickaxe or any other tool. 
No tools make mining **moon sand** or **moon stone** any faster. 
Tools with larger mining areas than 1x1 don't use their respective areas when targeting **moon sand** or **moon stone** blocks.

### Reproduction steps

1. Find/place moon stone
2. Mine it with a pickaxe
3. It takes just as long as mining it with a fist, and it doesn't drop any items.

**Comment by ThePansmith** [comment]
Report to GCYr, ill make a temp fix for now
