### ISSUE TITLE
[Bug] and/or [Feature] Multi Smelter

### ISSUE THREAD

**Issue by 4dam3k** [ThePansmith/Monifactory#171]
### Issue Summary

I really don't know if it's either bug or no (if that's GTM issue I will submit it there, just say so) but:
My multi smelter setup: 4a EV + RTM alloy Coils
Recipes work only when there is 2^n stacks inside input bus

It should be changed so it works 2 stacks at a time but still works when there is less so I can use the speed of multi smelter for 1 stack recipes
If I would want to use the 2 stacks at the time I would set up a recipes that way, because now I can't use the multi smelter for ingots that I don't really have in such quantities
And I know I can downgrade the coils to make it 64 at a time but the problem persists, it still won't work when I put 63 sand instead of 64

The problem is the same when Alloy Smelter mode is on

### Reproduction steps

![image](https://github.com/ThePansmith/Monifactory/assets/66412368/59def44f-7407-4e29-94eb-f1c95f866613)
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/64f9ee32-f4ac-4cd9-97f2-8f982a613f90)
or
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/cff39214-7691-4603-b230-e6ed20b31dd8)
![image](https://github.com/ThePansmith/Monifactory/assets/66412368/d83be583-ad17-47eb-9a87-d41f3fdb377e)

**Comment by 4dam3k** [comment]
The same thing probably is with the Parallel control hatch
It's waiting for exactly 4 recipes to run :c

**Comment by ThePansmith** [comment]
Report to GTM
