### ISSUE TITLE
[Bug]: Snad is broken

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#173]
### Issue Summary

Sugar Cane doesn't grow on Snad when it recieves a block update or redstone update

### Reproduction steps

Plant Sugar Cane on Snad
Give a block update or redstone update to the Snad block
The Sugar Cane should grow, but nothing happens

**Comment by JuiceyBeans** [comment]
Report to https://github.com/Leclowndu93150/Snad-Redstone-Edition
