### ISSUE TITLE
[Bug]: Water Collector keeps pushing water into nearby water-consuming blocks even when they are full and inactive

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#175]
### Issue Summary

When a block that consumes water is put next to a Water Collector, the water transfers from the Water Collector into it, but water keeps getting removed from the Water Collector once the tank is full even if the block is deactivated

### Reproduction steps

Put a block that consumes water next to a Water Collector and deactivate it (tested with boiler and Phytogenic Insulator from Thermal)
Wait until the tank on the block next to the Water Collector is full
See that the Water Collector doesn't fill with water

**Comment by JuiceyBeans** [comment]
Report to https://github.com/Leclowndu93150/Water-Collector

**Comment by esmenard** [comment]
It doesn't seem to have any way to report issues unfortunately
