### ISSUE TITLE
[Bug]: Non-existent ingredients in EMI

### ISSUE THREAD

**Issue by CestQuoiUnPseudo** [ThePansmith/Monifactory#178]
### Issue Summary

![image](https://github.com/ThePansmith/Monifactory/assets/96011112/27353a1f-331d-452a-8521-7728debedbfe)

I first saw it on this recipe
However the usual recipe work: glass + oxygen. Dunno if it's just my install

I also saw the same "invisible glass" problem on other recipes. 

### Reproduction steps

1. EMI tempered glass
2. "How do I craft it?"

**Comment by CestQuoiUnPseudo** [comment]
In 0.2.4 i'm still seeing some recipes with no ingredients (100mB). Here are a couple more examples:
![image](https://github.com/ThePansmith/Monifactory/assets/96011112/4127cb50-60b0-4f1b-b802-fb5fcd8a91a4)
Centrifuging recipe for SiO2, MgO, CaO, Gold, Al2O3 and Tantalite

![image](https://github.com/ThePansmith/Monifactory/assets/96011112/05d664dd-5e83-440e-b447-e284fc7263d0)
Drilling fluid recipe. No other ways to make it, could be a game-breaking problem.

**Comment by CestQuoiUnPseudo** [comment]
![image](https://github.com/ThePansmith/Monifactory/assets/96011112/34424871-6e29-4151-9871-8ba7abce82d3)
Ore washer, Impure pile of Salt into Salt
Most Ore Washer recipes actually. Maybe it's a special brand of water?

**Comment by ThePansmith** [comment]
Likely a GTm or EMI issue, as those recipes are not custom, please report it to them.
