### ISSUE TITLE
[Bug]: Steam grinder only grinds one item at the time

### ISSUE THREAD

**Issue by CestQuoiUnPseudo** [ThePansmith/Monifactory#179]
### Issue Summary

Should grind eight! 

0.2.3, but I think it did it in 0.2.2 also

### Reproduction steps

1. Send a lot of items at the grinder
2. only get one recipe done at a time

**Comment by ThePansmith** [comment]
Likely a GTM issue, bring it up with them.

**Comment by CestQuoiUnPseudo** [comment]
Might be related to [this issue](https://github.com/GregTechCEu/GregTech-Modern/issues/1221). Seems to be fixed in the latest versions
