### ISSUE TITLE
Multiblock Shapes & Recipes

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#191]
- [x] Advanced Microverse Projector 3
- [x] Draconic Fusion Reactor
- [x] Advanced Assembly Line

**Comment by WithersChat** [comment]
Aubrey said it would do the Draconic reactor, and I can do one of the other 2 or both.

**Comment by ThePansmith** [comment]
Just make a PR draft so we dont have people working on the same thing.
