### ISSUE TITLE
[Bug]: effortless building reappearing consumables

### ISSUE THREAD

**Issue by minecrafterseppe** [ThePansmith/Monifactory#201]
### Issue Summary

![image](https://github.com/ThePansmith/Monifactory/assets/13523046/777cac1f-9512-4dd1-ad52-39ef183cc175)
 both these items can be consumed upgrading your player
 and once updating your inventory these items re appear in your inventory 
 
 item id's
 effortlessbuilding:muscles
  effortlessbuilding:elastic_hand

### Reproduction steps

simply right clicking the item to consume it

**Comment by ThePansmith** [comment]
Does this issue happen with EB on it's own, or only within monifactory?

**Comment by minecrafterseppe** [comment]
can confirm does happen on a clean install with just EB alone
