### ISSUE TITLE
[Hardmode] Posttank stuff

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#208]
- [ ] Universal Crystalizer
- [ ] Stabilized MMs
- [ ] Disable Creative Tank Data
https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/scripts/multiblocks_expert.zs

**Comment by WithersChat** [comment]
Better than disabling creative tank data, replacing it with Omnium data because Motes of Omnium are **insane** to get in HM (give the SDA a very quick recipe for them too since I'm not sure CWU/t recipes can OC).
