### ISSUE TITLE
[Bug]: Jetpack voiding

### ISSUE THREAD

**Issue by AcrylicCombat** [ThePansmith/Monifactory#210]
### Issue Summary

Whenever you equip a jetpack with another one already on, the one you are equipping will be voided.

### Reproduction steps

1. Equip a jetpack
2. Hold a separate jetpack in your main hand
3. Right click
The jetpack you had in your main hand will now disappear

**Comment by AcrylicCombat** [comment]
Update: The jetpack reappears when you die...? Which is strange, because I checked each slot in my inventory for a ghost item.

**Comment by JuiceyBeans** [comment]
Tested it, issue is Moni-specific and doesn't exist in a blank instance

**Comment by ThePansmith** [comment]
Did you check your baubles slot?
