### ISSUE TITLE
Decrease ore density a little

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#219]
Maybe down to like 70 or 80 for most viens. Would still be 3-4x greater than normal, without looking too silly.

**Comment by WithersChat** [comment]
No :3 

I can reduce air exposure tho, would make it look less uncanny when in caves.
(Also, reminder that a poll was held on the issue that received an overwhelming majority of "yes, 100%")

**Comment by ThePansmith** [comment]
Thats great and all but 100% looks goofy af
