### ISSUE TITLE
Questbook Cleanup

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#233]
Normal Mode:
- [x] Quests related to sculk (see #228)
- [x] Endgame quests
- [x] Anything that hasnt been done in #28
- [x] Just kinda double check things ig

**Comment by hgjensen** [comment]
- [ ] Quest for Small Microverse Projector requires a Maint. Hatch, but the multi requires none
- [ ] "Moon Turf" does not exist. Change to "Moon Stone" and "requires silk touch"
- [ ] Quest for rocket should mention the east/west requirement and also the you should remember to hold space as soon as you change dim
- [ ] Quest for "Fluid Rig" says Raw Oil deposits in the void does not deplete. Should be removed, or the void dim should actually have oil deposits
