### ISSUE TITLE
[Bug]: Water not shown as needed for "base" cutting recipes in EMI

### ISSUE THREAD

**Issue by SparkedTheorem** [ThePansmith/Monifactory#237]
### Issue Summary

Water is not shown as needed for any "base" slow cutter recipes but is still required in actuality.
![Screenshot_46](https://github.com/ThePansmith/Monifactory/assets/162088357/a3083e3d-3acf-403e-9ac9-3403b8396816)

### Reproduction steps

1. open EMI on any cutter recipe
2. check the slowest variant and see blank space in place of water

### Relevant log output

```shell
https://mclo.gs/LRfrHpK
```

**Comment by kalsandbrook** [comment]
Can't replicate on latest modpack ver
