### ISSUE TITLE
Endgame Recipe Finalization

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#240]
- [x] Finalize Circuit recipes 
- [x] Finalize MM recipes
- [ ] Finalize Creative Data recipes
- [x] Holmium require Omnium Coil EBF
- [x] Remove Creative Storage Component, give it's texture to the creative storage data.
- [x] #234 

Withers have said that they wanted to tackle 2 and 3.

**Comment by SparkedTheorem** [comment]
I intend to modify the Hyperdynamic RAM recipes to be more of an interesting recipe chain but I am on vacation rn so :trollface:
