### ISSUE TITLE
General Cleanup

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#241]
- [x] Remove unused KJS items (glitch armor, ultimate generator, etc)
- [ ] Remove unused config files
- [x] Remove unused textures
- [ ] JEI hide misc uncraftable/unusable items

**Comment by JuiceyBeans** [comment]
Personally I think the warp core, controller, etc. from KJS AdvRocketry should be replaced by equivalent items from GCyR

**Comment by ThePansmith** [comment]
Could be doable
