### ISSUE TITLE
[Bug]: Energetic and Vibrant Alloy take way too long to smelt.

### ISSUE THREAD

**Issue by FooterManDev** [ThePansmith/Monifactory#242]
### Issue Summary

![image](https://github.com/ThePansmith/Monifactory/assets/71946346/ac3fd695-ff6d-44b0-893e-b7003d2fe648)
![image](https://github.com/ThePansmith/Monifactory/assets/71946346/a7bdc3a3-6fba-49f8-a459-232178a46b3a)
The Energetic Alloy quest says it takes 20 seconds to smelt in an EBF, when actually it is 178 seconds. This is not what it was in Nomi, not by a longshot.
![image](https://github.com/ThePansmith/Monifactory/assets/71946346/a72193fd-422e-44c4-b320-97217d292e03)
Vibrant Alloy, while not stated to have a specific time, takes longer to smelt than normal, and *less* time to smelt than Energetic alloy, which does not seem right for a superior alloy.

### Reproduction steps

Try to smelt Energetic and Vibrant Alloy.

**Comment by ThePansmith** [comment]
Could turn it into a feature for harder mode :trollface:

**Comment by FooterManDev** [comment]
I like the idea 😄
