### ISSUE TITLE
[Bug]: Oregen's reduction from exposed faces not applied for water

### ISSUE THREAD

**Issue by Xefyr0** [ThePansmith/Monifactory#250]
### Issue Summary

When ore generates, there's a chance for the ore block to not generate if one or more faces of that ore block would be exposed. This is to make the generous oregen look better in caves. However, the check that does this reduction does not check for water, resulting in views like that in the attached screenshot.
![oregen_moment](https://github.com/ThePansmith/Monifactory/assets/78383477/d46ba769-841d-4bb4-bb51-bf03df8f1d18)

### Reproduction steps

1. Generate new world in Monifactory. 0.3.0
2. Find ore vein intersecting water-filled cave
3. Profit

**Comment by ThePansmith** [comment]
Please make a issue on the GTM repo with this
