### ISSUE TITLE
[Bug]: Building Technique workbooks is given to player again after use

### ISSUE THREAD

**Issue by phytopius** [ThePansmith/Monifactory#258]
### Issue Summary

I found the item "Building Technique Books" from Effortless Building  in a overworld "dungeon" chest and when I use the item I get it over and over again and can reuse it
![image](https://github.com/ThePansmith/Monifactory/assets/16293118/702236d8-cd86-4ba9-bb3d-447454085272)

### Reproduction steps

1. Use item.
2. Item appears in hotbar again
3. Item can be reused
4. Profit

**Comment by ThePansmith** [comment]
EB Issue
