### ISSUE TITLE
[Bug]: Elastic hand being duped after use.

### ISSUE THREAD

**Issue by caldeira04** [ThePansmith/Monifactory#260]
### Issue Summary

While looting a Lost City in Monifactory Alpha 0.3.0 I found the Elastic hand and used it, then quickly after I noticed it was back to my inventory.

<a href="https://youtu.be/jRfTBswDTlg">Link to a video reproducing the bug</a>

After installing the latest version of Effortless Building (effortlessbuilding-1.20.1-3.8-all.jar) the bug is gone. I think if there's no compatibility issues with any other thing (at least there's nothing reported on <a href="https://bitbucket.org/Requios/effortless-building/issues?status=new&status=open">Effortless Bitbucket Page</a>) updating the mod to the newest beta should be fine.

<i>by the way, if I'm doing something wrong in reporting this, please tell me in the comments, I'm pretty new to minecraft modding community :)</i>

### Reproduction steps

<ol>
<li>Grab the item
<li>Use the item
<li>Put another item in the place where the Elastic Hand used to be
</ol>

**Comment by caldeira04** [comment]
I really don't know how to use GitHub lol

**Comment by esmenard** [comment]
I had the same with muscles

**Comment by caldeira04** [comment]
probably a consumable item problem present in 3.7. Didn't test with muscles because had already updated the mod before finding one.
