### ISSUE TITLE
Hard (and harder) mode fixes

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#265]
Firstly, figure out how to localize quests depending on difficulty (normal/hard or harder) 
We could just add duplicate questbook chapters, but doing it this way could lead to decent storage savings.

Quests to localize:
- [ ] Lathe (uses the 5u recipe in harder)
- [ ] Systeams boilers (if i decide to keep it enabled)
- [ ] Anything else that mentions RF
- [ ] AE2 controller recipe (in harder, if i decide to keep channels enabled in harder)

Questbook fixes:
- [x] Second Genesis chapter seems to generate when server is restarted?
- [ ] Readd nomicoin quest, mainly for the wandering trader charm
- [x] Starter tools quest should iron tools instead of wrought
- [x] Nether cake quest dependencies

Recipe changes:
- [x] Disable gtm dye nerf config
- [x] Disable the harder config recipe for pbf bricks (maybe could keep enabled in harder)
- [ ] Add a hidden hardmode only recipe that accepts every single monicoin you could possibly gather, then gives a joke item or something (shitty fakepng of meowni? idk)

Recipe Fixes:
- [ ] Rubberwood plank recipe (GTM issue i think tho)

Other fixes:
- [x] Packmode switcher currently installs into wrong folder, should install into the minecraft folder
- [x] Disable Create Zinc ore (also needs to be fixed for NM)

**Comment by JuiceyBeans** [comment]
- [ ] A lot of microverse recipes change (for example, tier nine miner + neutron reflector) depending on the mode

**Comment by ThePansmith** [comment]
closed to split into its own issues
