### ISSUE TITLE
[Hardmode] Questbook Stuffs

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#280]
- [x] Lategame multis
- [x] Renewable MMs
- [x] T4.5 and T8.5
- [x] Alloy smelter quest
- [x] Remove SDA, Superfab, and Supercomp quests if HM is detected

**Comment by JuiceyBeans** [comment]
- [ ] Remove SDA, Superfab, and Supercomp quests if HM is detected
