### ISSUE TITLE
[Hard(er)mode] Recipe Fixes

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#281]
Stuff that is marked as should not appear in hardermode in hardmode.js still appears.

**Comment by Miner239** [comment]
![image](https://github.com/ThePansmith/Monifactory/assets/4686046/30a239a7-530b-41c0-8f00-06709adff8ca)

no uraninite -> pulsating dust in hardermode (notice no smelting tab), need to add it back

**Comment by ThePansmith** [comment]
Need to disable snad in harder

**Comment by 3x1t-5tyl3** [comment]
snad is already kinda disabled in "hard" rn, as "Pulsating dust" is not craftable. So is also the void world cake as-well as a result. Not sure if that's intended. As a sidenote this also makes "pulsating iron" not available which are required for item conduits.

Hard mode also disables HNN and as a result recipes with items from HNN also are still available but uncraftable.
For example a few items that mgiht be really nice to have even in the harder difficulties like the XP and vacuum chest.

The Ultimate Gem is also uncraftable and everything that evolves around it.
I could go on but I tihnk you get the idea.
