### ISSUE TITLE
[Bug]: Unable to put an item in the filter slot of Vacuum Chest

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#289]
### Issue Summary

When I try to put an item on the filter slot of a Vacuum Chest, nothing happens

### Reproduction steps

Try to put an item from the inventory inside the filter slot
Try to put an item from EMI inside the filter slot
Try to put an EnderIO Item Filter inside the filter slot

**Comment by ThePansmith** [comment]
EnderIOu issue
