### ISSUE TITLE
[Proposal] Add quest for Effortless Building range upgrades

### ISSUE THREAD

**Issue by JuiceyBeans** [ThePansmith/Monifactory#30]
Effortless Building has reach and power upgrades now (can't tell if this was the case in Nomi), perhaps an addition to the already existing EB quest or a new one entirely might be useful to players (unless of course, you want to remove these upgrades entirely)

![image](https://github.com/ThePansmith/Monifactory/assets/75553966/0caf6c92-8664-4134-ba33-edf802f14390)
![image](https://github.com/ThePansmith/Monifactory/assets/75553966/8e2c8591-ead4-44e6-8be1-3ad1fe1d3b96)
![image](https://github.com/ThePansmith/Monifactory/assets/75553966/eb3341a8-1386-4527-8280-845356392289)
![image](https://github.com/ThePansmith/Monifactory/assets/75553966/64682f7f-7c09-4939-92b0-6433f5a6c4d5)

**Comment by ThePansmith** [comment]
I'll make a note about them in the EB quest. Thanks for the suggestion!
