### ISSUE TITLE
Energy conduits do not correctly auto connect to Thermal Series dynamos 

### ISSUE THREAD

**Issue by ogmon1243** [ThePansmith/Monifactory#303]
### Issue Summary

When connecting any energy conduit to the output end of a dynamo, it shows as a blank plate (not inserting or extracting). You must manually click on the blank plate to set it to extract but in doing so, it disconnects all other connections. This makes it incredibly tedious to setup compact numismatic dynamo setups since you might have to manually setup hundreds of connections to dynamos. I've only seen this issue so far with thermal dynamos but it may be present for other machines.

Idk whether this is a bug with the pack or ender io unofficial but you manage both so I just posted it here.

### Reproduction steps

1) Place down any thermal series dynamo and place an energy conduit on the output side.
2) A blank (no input or output) connection should form
3) Open up the connection gui and exit and the plate should automatically disconnect.

### Relevant log output

```shell
N/A
```

**Comment by EdgeHallow** [comment]
Still encountering this issue with 0.9.3
![2024-09-30_11 15 57](https://github.com/user-attachments/assets/d92115e7-8f79-4b90-8e20-8546376d7222)
![2024-09-30_11 16 02](https://github.com/user-attachments/assets/4ac497ff-1627-4486-b4ed-26ab4035b968)
![2024-09-30_11 16 04](https://github.com/user-attachments/assets/a23e2159-f85f-4ae7-b084-ed1e7919bfb5)
![2024-09-30_11 16 07](https://github.com/user-attachments/assets/2cdbc766-82d4-4457-b5ca-99631a3dcd5e)

**Comment by ThePansmith** [comment]
Report to enderio
