### ISSUE TITLE
[Bug]: Multismelter doesnt smelt proper quantities during continuous operation

### ISSUE THREAD

**Issue by ogmon1243** [ThePansmith/Monifactory#312]
### Issue Summary

When using the multismelter to smelt continuous quantities of items (in my case glass and clathrate for prediction matrix automation), the smelter start smelting smaller and smaller amounts of items instead of smelting full stacks.

My input bus -
![image](https://github.com/ThePansmith/Monifactory/assets/83802482/a9e4f1bb-278b-47cf-8c3e-fc5b334b9e0c)

What it runs -
![image](https://github.com/ThePansmith/Monifactory/assets/83802482/d70894e2-865a-474b-8e3d-34e27d5623d4)

If I take everything out and put it back in to "reset" the smelter, it starts smelting full stacks again for a few seconds before it runs out of stuff. As sand keeps feeding in, it starts smelting less and less until it backs up again with full stacks but only small amounts get smelted at a time.

I am using Kanthal coil blocks at HV power btw.

### Reproduction steps

1) Build a multismelter and constantly feed in items with an item conduit
2) Eventually it should back up with items and smelt only a few at a time.

**Comment by ogmon1243** [comment]
sometimes it takes a while for the bug to start happening but its been happening pretty consistantly on my end

**Comment by ThePansmith** [comment]
And this only happens with Monifactory?

**Comment by Deepacat** [comment]
this is a gtm issue with multismelter parallel logic I believe

**Comment by Deepacat** [comment]
https://github.com/ThePansmith/Monifactory/assets/52133154/64401f90-109c-4982-9045-a246eeeafe82

**Comment by 3x1t-5tyl3** [comment]
Okay I got it to replicate under specific circumstances:
1) This is *kinda* user error. But only if you don't feed it full stacks at a time.
2) This is still a GTM and not a pack issue.
3) THis is easily circumvented by just feeding it stacks at a time.

**Comment by ogmon1243** [comment]
That makes sense. Unfortunately, I don't have that kind of processing power setup yet so back to arc furnaces for glass I guess lol.

**Comment by ogmon1243** [comment]
there we go
