### ISSUE TITLE
Adding chipped

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#32]
- [x] Add Chipped, Chipped Chisel Integration, and Chipped Express
- [x] Hide the chipped crafting stations and sophisticated storage upgrades (irreverent with chipped express, which lets you do them all in the stonecutter)
- [x] Hide the chipped crafting station EMI recipe tabs.

**Comment by JuiceyBeans** [comment]
- [ ] Replace unifyChisel in tags.js with Chipped variants
