### ISSUE TITLE
[Feature]: Adding create and some of his addons

### ISSUE THREAD

**Issue by deepwebSans** [ThePansmith/Monifactory#333]
### Suggestion

I think it would be pretty neat to integrate create and create: the factory must grow or even create: new age in the pack, and i think they definitely fit in the pack

**Comment by SparkedTheorem** [comment]
Create has an optional compatibility file that gregifies its recipes and removes most of the processing machines from the mod. I don't think Create is really intended to be in the pack, its Gregtech centric.

**Comment by deepwebSans** [comment]
Oh i didnt know that, thanks though

**Comment by deepwebSans** [comment]
sorry, but could you tell me the name of the compat file?

**Comment by SparkedTheorem** [comment]
its simply create.js

**Comment by deepwebSans** [comment]
thanks, i found it
