### ISSUE TITLE
[Bug]: Rubber Planks recipe not removed in Harder mode

### ISSUE THREAD

**Issue by BlueDinoKing** [ThePansmith/Monifactory#338]
### Issue Summary

![image](https://github.com/ThePansmith/Monifactory/assets/80439860/2eddd44d-d452-477c-8860-ad67d37caf98)
In harder mode, it is possible to use polymorph to craft 4 rubber planks instead of 2 in the crafting grid. This only happens with rubber logs as far as I am aware. I haven't tried in any other modes.

### Reproduction steps

1. Harder mode
2. Polymorph the log recipe and choose 4 planks

**Comment by ThePansmith** [comment]
GTM issue I believe, please report it to them.
