### ISSUE TITLE
[Bug]: Lootr and EffortlessBuilding dupe

### ISSUE THREAD

**Issue by xlandon203** [ThePansmith/Monifactory#340]
### Issue Summary

In a chest theres an item called an "Elastic Hand" that can be consumed to gain +1 reach for building blocks, upon consuming this and opening a chest it is given back to the player and is able to be consumed until the max amount is reached.

https://medal.tv/games/minecraft/clips/i82ujVLaoSdTg35VI/d1337JnZl71W?invite=cr-MSxBQlUsMjEyMTEyNzkxLA

### Reproduction steps

1. Consume Elastic Hand
2. Open Chest
3. Given another

**Comment by ThePansmith** [comment]
known issue, report it to EB
