### ISSUE TITLE
[Bug]: All recipes I use have dissapeared

### ISSUE THREAD

**Issue by mjles** [ThePansmith/Monifactory#349]
### Issue Summary

A bug happened! I joined my single player world and noticed that my power wasnt working. Numismatic with diamonds, it wouldn't take the diamonds. I look for the recipe and the only options for numismatic now are coins. I notice my polymer clay isnt working. I see glass isn't turning into quartz, I check and the recipe is gone. I check more machines and the recipes are just gone.

### Reproduction steps

N/A

**Comment by mjles** [comment]
I can give anything you need if needed.

**Comment by ThePansmith** [comment]
do /reload, do any errors come up?

**Comment by mjles** [comment]
No errors when reloading.
