### ISSUE TITLE
[Feature]: EMI bug

### ISSUE THREAD

**Issue by unaimh** [ThePansmith/Monifactory#387]
### Suggestion

I will repost this issue in the GTM GitHub repository if it belongs there.

It appears that the EMI integration is incomplete. When right-clicking a machine, it does not display all the recipes it can perform, for both single and multiblocks. This functionality works correctly with machines from other mods, such as EnderIO or the vanilla furnace. 

If it helps, there seems to be a difference in how they are handled. There is a noticeable difference at the bottom of the interface. In the first image, it shows the machines recognized to perform the craft, even if there is only one (second image), whereas for GTM machines (third image), there are none.

![imagen](https://github.com/user-attachments/assets/73c232e5-caf6-49fd-b4a9-e292cfa61775)
![imagen](https://github.com/user-attachments/assets/0e73f69e-662f-4042-aaa0-2288b0cd9264)
![imagen](https://github.com/user-attachments/assets/2ecffd6a-e26a-4f93-9923-40f0597975eb)

**Comment by ThePansmith** [comment]
GTM issue, please report it to them.
