### ISSUE TITLE
Cleanup: Extendedcrafting

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#389]
Lock recipes to the specific table, or find a way to have it only display the lowest tier of table for the given recipe. As is, it forms a decent bit of JEI clutter and looks ugly when dealing with shapeless recipes.

![Image](https://github.com/user-attachments/assets/0f260eb0-756b-4d52-8ead-e22bfd216044)

![Image](https://github.com/user-attachments/assets/3a27250d-1d12-478c-b85f-bccf7f535e44)

**Comment by WithersChat** [comment]
I could try to fiddle with the fork?
