### ISSUE TITLE
Implement Research

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#4]
- [x] Quests
- [ ] Recipes

**Comment by JuiceyBeans** [comment]
![image](https://github.com/ThePansmith/Monifactory/assets/75553966/70499757-6848-4c2a-9b0e-13d32ffd3767)
Going to have to wait until GTM 1.2.1 or something for Research unfortunately

List of missing data chips I found:
IV -> LuV motor
IV conveyor module -> LuV conveyor module
IV pump -> LuV pump
IV piston -> LuV piston
IV robot arm -> LuV robot arm
IV dynamo hatch -> LuV dynamo hatch

Empowered enori block -> Draconium fusion crafting injector
Draconic core -> Fusion crafting core
Empowered restonia block -> Particle generator
Wyvern energy core -> Energy core
Dislocation normalisation field projector -> Warp engine
Solar panel 7 -> 8

**Comment by JuiceyBeans** [comment]
### Missing research station recipes:
Dark Soularium Thruster -> Chestplate
Fluxed thruster -> Chestplate
EBF -> Rotary Hearth Furnace
Vacuum -> Bulk Blast Chiller assline
Naquadah bolt -> Naquadah reactor I
Clock -> Advanced World Accelerator II
Advanced World Accelerator II -> Advanced World Accelerator III

### Missing assembly line recipes:
Rotary Hearth Furnace
Bulk Blast Chiller
Advanced World Accelerator II
Advanced World Accelerator III

**Comment by zcarp7220** [comment]
You should close this

**Comment by ThePansmith** [comment]
forgot to
