### ISSUE TITLE
[Bug]: Hypogean Infuser refuses to craft + state not cleared on break and reforming + some minor other bugs

### ISSUE THREAD

**Issue by xilni** [ThePansmith/Monifactory#431]
### Issue Summary

The Hypogean Infuser has a few bugs:
- Bad Z-fighting on the sculk input bus (see video for last bug for example)
- The first tier casing (Mesol Voltic Casing) doesn't show up in JEI as a valid block to build the HI, only the inaccessible highest tier casing is shown.
![2024-07-31_23-40-59_javaw_screenshot](https://github.com/user-attachments/assets/1880cbf5-b8ea-4394-9ed1-96e5b2029181)
![2024-07-31_23-29-23_javaw_screenshot](https://github.com/user-attachments/assets/c2dc05ac-9c7d-47bb-b8be-8e7b3901bd62)
- The HI fails to fill up and doesn't seem to craft the Bathyal Core despite having two 4A UV energy hatches
- Weird state bug on breaking and re breaking the casings. See [video](https://youtu.be/9rblm-cEwvE).

### Reproduction steps

Make first tier Hypogean infuser.

**Comment by ThePansmith** [comment]
defacto fixed by removing the HI
