### ISSUE TITLE
[Feature]: Mod Suggestion: "Gregic Energistics" And "GTMThings"

### ISSUE THREAD

**Issue by FwFeiVan** [ThePansmith/Monifactory#448]
### Suggestion

GE adds ME hatchs and buffer hatchs. They are very useful and provide faster IO speed and easier automation construction.
And GTMthings provides a wireless EU network like GTNH witch can simplifer wiring. Also the mega hatchs that can storage 
the number of INT_MAX items in one slot can improve gaming experience.

link: GE mod https://github.com/EpimorphicPioneers/Gregic-Energistics
GTMthings mod https://github.com/liansishen/GTMThings

bigger AE2 is also a excellent mod that provides cheap, SUPER LARGE AE storage cells.
here's the link https://github.com/DancingSnow0517/BiggerAE2

**Comment by JuiceyBeans** [comment]
GE is getting merged into GTm
GTMThings is not on CurseForge and cannot be included in the manifest
