### ISSUE TITLE
[Bug]: Effortless Building Clears Contents and Upgrades of Functional Storage Blocks

### ISSUE THREAD

**Issue by Bereim** [ThePansmith/Monifactory#467]
### Issue Summary

When using Effortless Building to place Functional Storage blocks, their inventory and upgrades are cleared.

### Reproduction steps

1. Pick up Drawer with Inventory or Upgrades.
2. Enable any Effortless Building mode.
3. Place Drawer.

**Comment by ThePansmith** [comment]
Effortless building issue, report it to them
