### ISSUE TITLE
[Bug]: Can't use/open the GT terminal

### ISSUE THREAD

**Issue by LunaDziaba** [ThePansmith/Monifactory#471]
### Issue Summary

After obtaining the GT terminal from the questbook it would not open or do anything with right clicked. I also tried in creative mode, got the terminal from the creative inventory and EMI.

### Reproduction steps

1. Obtain GT Terminal
2. Try to use it

**Comment by KuramA-777** [comment]
its only purpuse now for a few versions is to auto complete multblocks if you shift rightclick a controller block, given you have enough blocks in survival, in Creative it does it regardless and uses minimum required blocks/hatches
