### ISSUE TITLE
[Feature]: Dont apply dark mode to Journey Map

### ISSUE THREAD

**Issue by LunaDziaba** [ThePansmith/Monifactory#472]
### Suggestion

While I love the addition of dark mode to the GUI, applying it to the map makes it very difficult to discern what is being shown as colors are kinda important for a map.
For Reference: This is what a snowy city looks like in dark mode:
![Screenshot 2024-08-09 205301](https://github.com/user-attachments/assets/1b169cec-53e1-49ee-b4fa-1eab283ba561)

**Comment by JuiceyBeans** [comment]
![image](https://github.com/user-attachments/assets/a890da46-976c-45cc-8602-700ebf01a6d7)
If someone wants to take a crack at this
