### ISSUE TITLE
[Bug]: Tooltips appear under EMI right item panel when in a gregtech machine GUI

### ISSUE THREAD

**Issue by antrobot1234** [ThePansmith/Monifactory#474]
### Issue Summary

Tooltips appear under EMI right item panel when in a gregtech machine GUI

![image](https://github.com/user-attachments/assets/b860bd5a-e917-45f8-b684-6fd9da8ec31c)

### Reproduction steps

1. open a gregtech machine (e.g. LV wiremill)
2. hover over an item on the righthand side of your inventory (e.g. sulfur dust)
3. the item tooltip appears under the item menu

**Comment by ThePansmith** [comment]
Likely a GTM issue, report it there.
