### ISSUE TITLE
[Bug]: Screen black while configuring EnderIO conduits and EMI highlight searching

### ISSUE THREAD

**Issue by tarzan1376** [ThePansmith/Monifactory#486]
### Issue Summary

When trying to configure a conduit while EMI highlight searching anything, the entire screen will go black. 

Thought it was a bigger issue, but probably not important, just wanted to let it be known since I panicked for 10 minutes till I figured it out since its hard to tell when you are highlight searching in dark mode so I didn't even realize I was. 

But it happens no matter what "brightness" mode the GUI is in.

### Reproduction steps

1. Highlight search with EMI anything
2. Open conduit configuration

**Comment by ThePansmith** [comment]
Report to mod devs
