### ISSUE TITLE
[Bug]: pack-mode-switcher doesn't exist in the build

### ISSUE THREAD

**Issue by jasonroelofs** [ThePansmith/Monifactory#488]
### Issue Summary

I would like to try out Hard mode, but I am not seeing the pack-mode-switcher file in either Curseforge or a GitHub Release file. I [found the commit](https://github.com/ThePansmith/Monifactory/commit/f2e0f44e351f91a6fbc293680a9539b832b70ded) that removed these files from the build due to Curseforge, but could they still exist if you download the pack directly from GitHub?

For now I guess we have to download the appropriate file and put it in our pack manually?

### Reproduction steps

1. Install the pack (I used Prism Launcher)
2. Open the folder of the pack
3. Cannot find the relevant files for switching the mode of the pack.

**Comment by ThePansmith** [comment]
Curseforge doesn't allow that file type
