### ISSUE TITLE
[Feature]: Several performance mods

### ISSUE THREAD

**Issue by CapitalismWouldveWorked** [ThePansmith/Monifactory#489]
### Suggestion

I've noticed the following performance mods could be added to stabilize and improve FPS:

DynamicFPS: Reduce resource usage while Minecraft is in the background or idle
Fastworkbench: Speeding up crafting operations
FastAsyncWorldSave: Asynchronous saving at five-minute intervals, reducing lag spikes
Fastload Reforged: Speeds up world loading
Krypton Reforged: Networking optimization mod
Modern Startup QOL: Gives you the startup time on the title
Noisium: Optimizes worldgen performance
Observable: Let's you check what's causing lag in a world
RuOK: Embedium mod
Saturn: Optimizes memory usage
ServerCore: Optimizes servers
Starlight: Rewrites lighting engine
StarlightxAE: Prevents AE2 crash with Starlight

Edit: Testing before and after adding these mods, FPS minimum went from 25 to 55.
Edit 2: The creator SomeAddon also has a variety of mods that can help with performance

**Comment by Leclowndu93150** [comment]
Starlight is useless in 1.20.1 as the light engine was rewritten
DynamicFPS already has an equivalent which is FPS Reducer
Saturn is pointless because FerriteCore and ModernFIx are installed
Fastload actually makes loading slower
RuOK seems like a cheap performance mod.
Fastworkbench is pointless since FastSuite is already in.

The rest is pointless imo, since ModernFix is a very well made mod and takes care of most optimisations.

but again that's just my opinion

**Comment by CapitalismWouldveWorked** [comment]
What exactly is the criticism here? That we shouldn't include these performance mods because ModernFix handles all of this? I don't see why we can't just include them even if they improve performance by like 5fps each.

Why was Starlight even ported to 1.20 if the lighting rework was supposedly so good? Why do any of these mods exist knowing ModernFix exists if they don't have an effect on performance?

I run ATM9 with these mod and get more fps than Monifactory on it's own, that alone says they help enough.

**Comment by Leclowndu93150** [comment]
because there are these things called "mixins", they are pieces of code that are injected in vanilla and can cause conflicts the more performance mods you add. It's not just a matter of slapping the most mods together and calling it a day.

**Comment by CapitalismWouldveWorked** [comment]
If the criticism is some of these mods simply do what other mods already do, then sure ignore installing them. But for the rest that are doing a better job than their counterparts, and the mods that do stuff the already included performance mods don't, then should they still not be included?

**Comment by JuiceyBeans** [comment]
Saturn was tested on earlier versions of the modpack and found to conflict with existing, better performance mods. It increased memory and CPU usage

**Comment by JuiceyBeans** [comment]
> Fastworkbench is pointless since FastSuite is already in.
From FastSuite mod page:
> This mod does not replace FastWorkbench or FastFurnace, though their benefits will be lessened if this is installed, as some of the work will be offloaded to FastSuite.  To receive maximum performance with regards to recipes, I still advise having both of them installed, but if you had to pick just one, it should be FastSuite over either of the others.

Adding the other wouldn't hurt the pack

**Comment by Leclowndu93150** [comment]
i don't understand why he did that
