### ISSUE TITLE
[Bug]: Effortless Building upgrades don't actually get used up

### ISSUE THREAD

**Issue by jasonroelofs** [ThePansmith/Monifactory#495]
### Issue Summary

I've seen this with both the elastic hand and the Building Techniques Book. I use the item, it gives me the upgrade point and "disappears" from my inventory however it's only hidden, and moving an item into that slot puts the upgrade item into my cursor, letting me re-use the item until max.

I'm on Hard mode configs.

### Reproduction steps

1. Have a Elastic Hand or Building Techniques Book in the currently selected quickbar slot.
2. Right click to use the item.
3. Gain point, item no longer visible in the slot. However the item is still there.

**Comment by ThePansmith** [comment]
Effortless building issue, report it to them.
