### ISSUE TITLE
Implement Draconic Fusion Reactor

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#5]
Post tank multiblock, basically works the same as the current draconic fusion multiblock, but parallelizable, and doesn't require the injectors in the recipe

**Comment by JuiceyBeans** [comment]
Personally I think draconic reactor deserves a new casing of its own instead of stainless steel, to keep with the style of GCy multiblocks having their own personal casing. I mean, that IS the power of the sun in a chamber, is stainless steel of all things to contain it?

**Comment by ThePansmith** [comment]
> Personally I think draconic reactor deserves a new casing of its own instead of stainless steel, to keep with the style of GCy multiblocks having their own personal casing. I mean, that IS the power of the sun in a chamber, is stainless steel of all things to contain it?

This is for the post tank variant, we can build bigger for it. The current iteration was made under the belief that it would get replaced quickly anyways, but seeing as that may not happen, it prob needs a redesign as well.
