### ISSUE TITLE
[Bug]: Cannot set 'open backpack' to a multi-key input

### ISSUE THREAD

**Issue by DannyDan4** [ThePansmith/Monifactory#503]
### Issue Summary

I cannot set the 'open backpack' hotkey from sophisticated backpacks to 'shift + i', which 'i' would be my open inventory key. What happens in return is pressing 'i' under any circumstance opens the backpack. Recreated with 'shift + e' as well.

### Reproduction steps

Assign 'shift + [something]' to 'open backpack', and then just press the aforementioned key without pressing shift. What should normally happen is whatever is usually bound to '[something]', but instead the backpack is opened.

**Comment by jaaaco-j** [comment]
weird, i have it on SHIFT+R, but also tested with shift+e and shift+i. works for me

 update to newest version of you haven't yet

**Comment by DannyDan4** [comment]
So: from further experimentation, I found it was because I had swapped over to Neoforge, which apparently breaks controlling. I'm making a bug report over with that mod, shortly.
