### ISSUE TITLE
[Bug]: Ores in walls

### ISSUE THREAD

**Issue by ZaharitIngot** [ThePansmith/Monifactory#504]
### Issue Summary

![image](https://github.com/user-attachments/assets/3f9783f7-546d-4bcd-930b-62c1de3e6f23)

### Reproduction steps

1.join world
2.see generation issue

**Comment by Mindstyler** [comment]
i guess it sees the normal stone of the structure as 'normal world stone' and generates ores into it. huh.

**Comment by ThePansmith** [comment]
What Mindstyler said, not really something that can be fixed outside of just removing all the building that have stone in them.

**Comment by jaaaco-j** [comment]
issue is that cities generate before ore veins, idk if its possible to change the ordering of worldgen

**Comment by ZaharitIngot** [comment]
😶

пн, 12 авг. 2024 г., 21:34 jaaaco-j ***@***.***>:
