### ISSUE TITLE
[Bug]: Effortless building infinte power

### ISSUE THREAD

**Issue by johnnyx453** [ThePansmith/Monifactory#514]
### Issue Summary

A bug happened! just started a new world, got a building techniques book (Effortless Building) from a chest, and used it. Whenever I open a chest after having used the book, a new one appears in my inventory, allowing for infinite use of the same book. Have not tested with other inventories/interfaces.

### Reproduction steps

1: Obtain book from  lootr chest
chest
2: Use book
3: Open chest again
4: Repeat steps 2 and 3 until you feel guilty
 - not entirely sure that it is repeatable, could be a one-time flook. Have Fun!

**Comment by Squawkykaka** [comment]
it works with muscles too, even opening your inventory suffices to make the muscles re-appear

**Comment by hamburger5003** [comment]
Also works with the elastic hand

**Comment by JuiceyBeans** [comment]
Known bug with Effortless Building, [report to dev](https://bitbucket.org/Requios/effortless-building/issues)
