### ISSUE TITLE
[Feature]: Alternative way(s) of getting paper and/or sugar cane in very early-game.

### ISSUE THREAD

**Issue by littleconnor1** [ThePansmith/Monifactory#518]
### Suggestion

With the current world gen, sometimes sugar cane can just kinda _not spawn_ for hundreds upon hundreds of blocks, more if you're unlucky. On normal mode, this is a non-issue because you can just "buy" them with monipennies, but on other difficulties, this is definitely a problem.

A book > paper recipe wouldn't be helpful here, so instead, perhaps allow us to make paper _very inefficiently_ by crafting using tools and logs or something? Failing that, adjusting world gen to make sugar cane spawn more often in most applicable biomes could help, or letting us harvest "cane seeds" from grass, or some other similar concept. Any process that's simple and is basically useless after early-game to prevent scenarios like this.

**Comment by jaaaco-j** [comment]
im pretty sure you can make paper with wood pulp

**Comment by ThePansmith** [comment]
Monicoin recipe was added at some point

**Comment by jaaaco-j** [comment]
> Monicoin recipe was added at some point

pansmith i feel like you didnt read the body of the post, they're asking for a hardmode alternative for some early game paper or sugar cane if world gen decides to screw you over
