### ISSUE TITLE
[Bug]: Treated Wood Planks Being Treated As Normal Wood Planks

### ISSUE THREAD

**Issue by chrispynachos** [ThePansmith/Monifactory#521]
### Issue Summary

When crafting Treated Wood Planks in a crafting table, Treated Wood Planks can be used to craft Treated Wood Planks. Treated Wood will also craft regular Sticks, essentially wasting the wanted usage of treated wood for its specific properties (Treated Sticks for Treated frames, etc) 

### Reproduction steps

1. Try and craft Treated Planks via Creosote Bucket in the crafting table. 
2. Try to craft Treated Sticks from EMI.
3. Pout as you have probably accidentally wasted a bucket or so of creosote you've waited for because you've either wasted a bucket of creosote to craft Treated Planks with Treated Planks, or normal, boring sticks with Treated Planks. :(.

**Comment by ThePansmith** [comment]
Report to gtm
