### ISSUE TITLE
[Bug]: Crash when generating superflat world: "Can't find a valid spawn position!"

### ISSUE THREAD

**Issue by visceralfield** [ThePansmith/Monifactory#523]
### Issue Summary

What the title says. See the attached crash log for the details, it appears to be an issue with finding a spawn position caused by Lost Cities.

[crash-2024-08-14_00.25.34-client.txt](https://github.com/user-attachments/files/16607580/crash-2024-08-14_00.25.34-client.txt)

### Reproduction steps

1. Open the game
2. Create a new superflat world
3. The game will crash somewhere around 60-80% of the way through world generation

**Comment by JuiceyBeans** [comment]
Known issue with LC https://github.com/McJtyMods/LostCities/issues/636
