### ISSUE TITLE
[Bug]: The game goes 0 fps after an amount of time

### ISSUE THREAD

**Issue by tengkuirfan** [ThePansmith/Monifactory#524]
### Issue Summary

I played the pack like normal on a server. The performance was good until after an amount of time, the game goes 0 fps and freezer like forever. It feels like I was on Monifactory free trial or something. 

Added mods: Create, CC: Tweaked, and Observable

### Reproduction steps

I allocated 5GB of RAM and just play like normal. Walk around in a non-void world, and the lag occurs.

**Comment by JuiceyBeans** [comment]
Attach your crash log

**Comment by tengkuirfan** [comment]
So I investigated the issue by reinstalling my Moni 0.7.6 instance and allocate 4GB of RAM. I monitored the task manager and I found that there's a memory leak in the instance by noticing it using more than allocated RAM.

**Comment by jaaaco-j** [comment]
> So I investigated the issue by reinstalling my Moni 0.7.6 instance and allocate 4GB of RAM. I monitored the task manager and I found that there's a memory leak in the instance by noticing it using more than allocated RAM.

install 0.7.9 and check if it still happens
