### ISSUE TITLE
[Bug]: Wrong Description for Golden Furnace

### ISSUE THREAD

**Issue by MilkSodaBag** [ThePansmith/Monifactory#526]
### Issue Summary

The description in MEI says "Cooktime: 60" but the quest book says it should only take 40

![Screenshot 2024-08-13 154957](https://github.com/user-attachments/assets/17291c48-b935-426d-8eb4-8cce338b88f1)

### Reproduction steps

1. open the modpack
2. hover your mouse over the item "golden furnace"
3. Read the description

**Comment by JuiceyBeans** [comment]
Can be closed

**Comment by ThePansmith** [comment]
whoops forgot to close
