### ISSUE TITLE
[Bug]: Various Steam Grinder/Foundry Multiblock issues

### ISSUE THREAD

**Issue by hamburger5003** [ThePansmith/Monifactory#533]
### Issue Summary

I'm just going to edit this issue and list a bunch of inconsistences and issues I've found with the Steam Foundry and Steam Grinder multiblock so as not to make a flood of issues.

- Steam Grinder multiblock has z-fighting issues for various I/O blocks both in-world and in the Multiblock Info tab of EMI
- Steam Foundry multiblock has z-fighting issues for various I/O blocks just in-world
- It seems that ULV input/output busses are allowed to work for the Steam Grinder/Foundry multiblock despite skipping a lot of the ULV stage. I see no reason to change that, nor for EMI to let you know that they can be used. However it would make more sense with the quests and be less confusing to have the default textures for the Multiblock Info tab and the in-world multiblock display to use just the (Steam) versions. Ie: shift-right clicking on the Steam Grinder/Foundry to show the interactive display should show the 'Output Bus (Steam)' texture instead of the 'ULV Output Bus' texture. Another area where it shows the ULV output bus are in the total block lists in the Multiblock Info tab of both.
- There is an inconsistency with the Steam Foundry quest required items and the amount of items actually needed to build it. The multiblock structure forces the Steam Input Hatch to replace one of the 'Bronze Firebox Casing' blocks, not the 'Steam Machine Casing' blocks. This brings the required firebox blocks from 9 to 8, and the required machine blocks from 13 to 14. Either the quest tasks should be changed to reflect this (makes more sense imo), or the multiblock should be changed to allow the hatch to be able to replace a machine block.

A screenshot of Steam Grinder z-fighting:
![2024-08-15_20 12 38](https://github.com/user-attachments/assets/da7b8ed3-82cc-4d86-bdbe-aefbef56b3e2)
Steam Foundry z-fighting
![2024-08-16_10 03 52](https://github.com/user-attachments/assets/9b7d1890-126b-4e6c-873a-c09aac946d5c)
Steam Grinder interactive display texture discrepancy
![2024-08-16_08 47 23](https://github.com/user-attachments/assets/81ccc454-0c67-4477-bc35-18223ea28584)

### Reproduction steps

N/A

**Comment by hamburger5003** [comment]
The Z-fighting also exists in the Multiblock Info tab of EMI for the Steam Grinder but with different blocks (Steam Grinder, Steam Input Bus, Steam Input Hatch)

**Comment by ThePansmith** [comment]
As stated above, test to make sure that issues are with the pack itself, and not with just a specific mod, and if so, report it to the applicable repo.
