### ISSUE TITLE
[Feature]: Modpack creates 2 folders on disk, not in instance

### ISSUE THREAD

**Issue by Icebodhi** [ThePansmith/Monifactory#539]
### Suggestion

Don't create folders or remove them
![image](https://github.com/user-attachments/assets/50007beb-a9ea-4fdc-b6eb-8468951baaf0)

**Comment by jaaaco-j** [comment]
where are these supposed to be exactly? cause i dont see anything that is outside of the instance folder

**Comment by glektarssza** [comment]
Please provide more information, specifically:

* What were you trying to do when this happened.
* What folders were created/removed.
* Where were they created/removed.
* Where you expected them to be created/removed from (or not as the case my be).
* Your operating system (though I suspect it's Windows).
* Whether you are using WSL if you're on Windows (or another `bash`-like environment).

**Comment by ThePansmith** [comment]
Closing until more info is provided
