### ISSUE TITLE
[Bug]: Main menu does not support ultrawide screen monitors

### ISSUE THREAD

**Issue by antrobot1234** [ThePansmith/Monifactory#540]
### Issue Summary

The main menu has the menu options offset on wide monitors
![image](https://github.com/user-attachments/assets/11d6da74-b36b-46d1-9e7d-517677f5bc22)

### Reproduction steps

open pack with ultrawide monitor (e.g. 5120 x 1440)

**Comment by Old-Man-D** [comment]
here is another at 3440x1440 
![image](https://github.com/user-attachments/assets/d280a019-d4b0-4433-99f9-80e27af8c20d)

**Comment by ThePansmith** [comment]
It's a issue with how fancy menu is done, theoretically this could be solved with some fancy logic to it have resize and move (with needed offset relative to anchor) elements depending on screensize x and y

**Comment by ThePansmith** [comment]
Just closing this as its kinda infesiable to fix w/out some maths and testers
