### ISSUE TITLE
[Feature]: 16A hatches for post uhv tiers

### ISSUE THREAD

**Issue by Deepacat** [ThePansmith/Monifactory#542]
### Suggestion

There is no recipes for 16A hatches that allow voltages beyond UHV, eg:
16a UHV, 16A UEV,
I think these should have recipes to reflect the higher tiers enabled

**Comment by IamNotBrianZ** [comment]
Isn't this intended to lock machine speed?
To force player to unlock higher tier circuit

**Comment by hgjensen** [comment]
It must be a bug. There are recipes for 64A UV Dynamo Hatches, but no recipe for 16A UV Dynamo Hatch which is required for the 64A version.

**Comment by glektarssza** [comment]
If you look at [Post_UV_Components.js (line 78)](https://github.com/ThePansmith/Monifactory/blob/main/kubejs/server_scripts/gregtech/Post_UV_Components.js#L78) you can see there ARE recipes for UEV, UIV, and MAX tier 4A and 16A energy input hatches via the assembly line but they're commented out. Not sure why.

**Comment by hgjensen** [comment]
@ThePansmith seems like it was added/commented in one of your commits. Can you comment as to whether it's intentional or not that the recipes are commented out?
https://github.com/ThePansmith/Monifactory/commit/2246c39a004bb1fdd79dff2ac6307a29b8748d04
