### ISSUE TITLE
[Bug]: The game often gets stuck and doesn't move at startup.

### ISSUE THREAD

**Issue by Allie424** [ThePansmith/Monifactory#544]
### Issue Summary

When I start Monifactory using the launcher, the game process gets stuck at the last step of loading.
![QQ截图20240819081310](https://github.com/user-attachments/assets/963d47ec-5db6-4ed1-a3a1-1a6d15177d4f)

### Reproduction steps

1.Launching the game
2.The game is stuck.

**Comment by glektarssza** [comment]
Please provide game logs if possible. A screenshot of the game is not particularly helpful in diagnosing the issue here.

Thank you.
