### ISSUE TITLE
[Bug]: There are no virtual oil fields in the Void Dimension in hard mode.

### ISSUE THREAD

**Issue by Allie424** [ThePansmith/Monifactory#546]
### Issue Summary

A bug happened!
![QQ截图20240819094800](https://github.com/user-attachments/assets/6585a72e-1c46-460a-a82f-c3bc0b0861c7)

### Reproduction steps

1.Hard Mode
2.See the Scanner

**Comment by Allie424** [comment]
ALSO IN NORMAL MODE

**Comment by Yokoharu** [comment]
fixed in gtm

**Comment by JuiceyBeans** [comment]
JAVD void is different from GTM void, might be why

**Comment by Aderixx** [comment]
fixed in 0.8.0 with the update to GTm

You might have to delete the file `gtceu_bedrock_fluid.dat` in `<your world save>/dimensions/javd/void/data` for the chunks that have already been generated
