### ISSUE TITLE
[Bug]: Machine explosion in Hard Mede

### ISSUE THREAD

**Issue by lunzbunz** [ThePansmith/Monifactory#551]
### Issue Summary

Machines break blocks when connected to too high volatge in Hard Mode. In the Hard/Harder Mode section of the readme it says bringing back machine explosion is a feature of Harder Mode.

### Reproduction steps

In Hard Mode: Connect any machine to a higher tier of voltage than the machine

**Comment by Mindstyler** [comment]
Not a bug. Connecting a lower voltage machine to a higher voltage power source / cable ALWAYS makes the machine explode, even in normal mode.

Harder mode adds the feature that machines explode when exposed to rain.
