### ISSUE TITLE
[Bug]: 缺少UHV以及更高级别的电池箱合成表 Missing UHV and higher tier battery box recipes

### ISSUE THREAD

**Issue by UU6934** [ThePansmith/Monifactory#562]
### Issue Summary

A bug happened!缺少UHV以及更高级别的电池箱合成表 

Missing UHV and higher tier battery box recipes

### Reproduction steps

缺少UHV以及更高级别的电池箱合成表 ,我需要这些机器来帮助我完成自动化

Missing UHV and higher tier battery box recipes,I need these machines to help me automate

**Comment by WithersChat** [comment]
Those battery boxes won't be any use to you since there isn't any battery to put in there.
