### ISSUE TITLE
Update GTm to 1.4

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#563]
Work has been started on the 1.4-prep branch, work off of there.

**Comment by JuiceyBeans** [comment]
To do:
- [ ] Change fluid registry declarations to new syntax
- [ ] Quests about new stuff (ME hatches, etc.)
- [ ] Other misc crashes

**Comment by JuiceyBeans** [comment]
- [ ] Fix broken rock crusher recipe in https://github.com/ThePansmith/Monifactory/blob/main/kubejs/server_scripts/mods/optionalCompats/create.js
![image](https://github.com/user-attachments/assets/41a5343e-dc7a-447a-b8f9-4cab15fc1189)
