### ISSUE TITLE
Can't Change Mode to Hard/Harder [Bug]: 

### ISSUE THREAD

**Issue by ArcWielder** [ThePansmith/Monifactory#570]
### Issue Summary

I'm using MultiMC, and I followed all the steps on the github to change the mode to harder, ran the file in Mac Terminal, and it just says:

Could not find `config-overrides` directory! 
Make sure you are in the `/minecraft` directory of your instance! (The one containing `/config`)
Otherwise, if you are in the `/minecraft` directory, please try reinstalling the pack.

I have the pack-mode-switcher.sh file in the .minecraft file so I'm not sure whats going on.

Note: The modpack runs as normal in normal mode, it's just the pack-mode-switcher file that isn't working correctly.

### Reproduction steps

1. Install the Monifactory 0.7.9 beta modpack on the FTB Installer
2. Open MultiMC, and create a new instance
3. Use the FTB App Import option to port the Monifactory modpack
4. Copy the pack-mode-switcher.sh file from the github into the .minecraft folder
5. Run the file in Mac Terminal
6. Get the error message

**Comment by ArcWielder** [comment]
![Screenshot 2024-08-23 at 5 11 20 PM](https://github.com/user-attachments/assets/f761cc39-3b52-4ac3-85cc-5e1a56918439)

If it helps, here is a screenshot of my .minecraft folder for the MMC instance

**Comment by ArcWielder** [comment]
Nvm! looks like this was just user error lol

**Comment by Jax1366** [comment]
What was the user error I also can't figure it out.

**Comment by ArcWielder** [comment]
Terminal wasn’t directed to the folder with the pack-mode-switcher file, so it couldn’t find it which is why it gave that error.
