### ISSUE TITLE
[Bug]: Ender IO Conduits do not behave as expected with GT machines.

### ISSUE THREAD

**Issue by sebimon3** [ThePansmith/Monifactory#576]
### Issue Summary

Title. Either that or GT machine behavior has changed significantly in 1.20.
Using Monifactory b0.7.9 on both the client and server. Issue happens in both single- and multiplayer.

I am unsure if this is the right place to post this issue as i doubt the Issue has anything to do with the Pack as a whole, however i don't know if the issue is on the GT side or eIO side. Please advise on where to post if this is the wrong place.

### Reproduction steps

Hard to reproduce as eIO Conduits seem to randomly stop working. Happens more frequently when two or more eIO Conduits of any kind are used on a GT machine.

Here are some Screenshots of a NaOH
 loop to generate hydrogen and oxygen. You would expect the bottom fluid conduit to move Salt Water from the Mixer into the Electrolyzer, but it does not.
1. View of Mixer and Electrolyzer connected with a conduit:
![javaw_vsQdS1uOv3](https://github.com/user-attachments/assets/309a4537-cefe-4821-a636-39920de4dba5)

2. View of Mixer UI
![javaw_vWBRP6bzaU](https://github.com/user-attachments/assets/02f7ed46-04fb-40eb-a393-d40aa1c30b9a)

3. View of Conduit UI on Mixer
![javaw_Ilc3axqyxy](https://github.com/user-attachments/assets/4b5df134-06b4-48af-be2a-d844b025fa14)

4. View of Conduit UI on Electrolyzer
![javaw_zmoJd3bx03](https://github.com/user-attachments/assets/d3c90481-91b7-401d-b25a-2928a3399a68)

5. View of Electrolyzer UI.
![javaw_flRH2dspS5](https://github.com/user-attachments/assets/2cf0b3dc-1db5-45ec-9da8-b16d0fcbdf3d)

Note how the Salt water does not move from the Mixer to the Electrolyzer.

If this is expected behavior and i am simply mistaken on how this is supposed to work, please let me know! Thank you.

**Comment by ThePansmith** [comment]
Report to EIO or GTm devs
