### ISSUE TITLE
[Bug]: Server crashes when opening any Gregtech machine because LDLib isn't present

### ISSUE THREAD

**Issue by Jaymus3** [ThePansmith/Monifactory#58]
### Issue Summary

See [this](https://github.com/Low-Drag-MC/LDLib-Architectury/issues/22) issue for details.  I had this exact crash.  Installing LDLib in client and server resolved the issue.

### Reproduction steps

1. Try to open any Gregtech machine while connected to a server.
2. Server instantly crashes.

### Relevant log output

```shell
See the linked issue if you want the log output.
```

**Comment by LetterN** [comment]
update gregtech to latest

**Comment by Jaymus3** [comment]
This issue is still present in pack version 0.1.1, but the stacktrace is different.  Nevertheless, adding the latest version of LDLib to server and client resolves the issue.

**Comment by Jaymus3** [comment]
Resolved in 0.2.0
