### ISSUE TITLE
[Bug]: Ender IO Fluid tank issues

### ISSUE THREAD

**Issue by carter-ho** [ThePansmith/Monifactory#581]
### Issue Summary

The fluid tank from Ender IO seems to have at least two bugs:
1.  If you put a fluid in a fluid tank from the output slots of a machine using the Inventory/GUI, when it is placed down, it becomes a regular fluid tank (Tested with Water and Oxygen). If picked up it is still an empty fluid tank and there is nothing to input into any machine.
2. If you pump a fluid out from a machine into an Ender IO fluid tank, it transfers successfully, but in your inventory it appears as empty, but when placed down all the fluid is still in the fluid tank. However, as it displays as empty, you cannot add it into a machine through the GUI. It is possible to pump the fluid into a machine.

### Reproduction steps

Bug 1:
1. Have Ender IO fluid tank
2. Interact (Right-click) with machine GUI
3. Pick up (Left-click) Ender IO fluid tank 
4. Remove (Left-click) fluid output from machine (Fluid tank should no longer be empty)
5. Exit machine GUI
6. Place down (right-click) Fluid tank on placeable block
7. Fluid tank is empty (and you can put a new fluid into the tank)

Bug 2:
1. Have Ender IO fluid tank and any machine capable of pumping out a fluid (into another block)
2. Pump fluid into Ender IO fluid tank.
3. Break Ender IO fluid tank in order to pick it up (It should appear to be empty)
4. Place (right-click) Ender IO fluid tank down, it should still have its fluid content.

### Relevant log output

N/A

**Comment by ThePansmith** [comment]
Does this happen specifically in moni or is it a general bug with enderio?

**Comment by carter-ho** [comment]
> Does this happen specifically in moni or is it a general bug with enderio?

I specifically encountered this while playing Monifactory. I have not done any testing with Ender IO by itself and did not find any mention of a similar issue on the Ender IO page.

**Comment by ThePansmith** [comment]
Try testing with just GT and EIO

**Comment by JuiceyBeans** [comment]
Had this in ATM9 TTS, report to EIO but don't expect much lmao
