### ISSUE TITLE
HM/EM item that requires all the coins

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#591]
why? funny

The number of coins in each mode can be determined with [this script](https://discord.com/channels/914926812948234260/1229929078547550238/1268417799265718272).

**Comment by Eterxity** [comment]
what if we counted every monicoin in harder/hard mode and have put em in like an uiv assembler for a token (flex)

**Comment by ThePansmith** [comment]
![Image](https://github.com/user-attachments/assets/6562abf5-71fd-4eed-87c6-d719d307fe63)
Currently being worked on by Jamiscus.
