### ISSUE TITLE
[Bug]: There are many missing recipes and items related to high-tier dynamos and energy hatches

### ISSUE THREAD

**Issue by MeiTianyou** [ThePansmith/Monifactory#609]
### Issue Summary

Many of these are asking for items which have not been generated, like europium and platinum springs. Sometimes, for example the UHV 4A transformer, the recipe is missing entirely.

### Reproduction steps

Try to craft uhv and higher multiamps, cry

**Comment by ThePansmith** [comment]
Artifact of GTm adding its own recipes for these items in 1.4.0, will be fixed in a patch

**Comment by hgjensen** [comment]
Every transformer UHV and up is uncraftable
