### ISSUE TITLE
[Feature]: Add to AT Launcher

### ISSUE THREAD

**Issue by gamma-gamer** [ThePansmith/Monifactory#610]
### Suggestion

Is there a possibility to add Monifactory to the AT Launcher? Or can we add it manually somehow?

**Comment by glektarssza** [comment]
You can add it yourself via the current version of ATLauncher. See the below screenshot.

![image](https://github.com/user-attachments/assets/cfd4faa7-44a7-478a-8f90-9e660edf804e)
