### ISSUE TITLE
[Bug]: Simulation Supercomputer outputs weird matter

### ISSUE THREAD

**Issue by MeiTianyou** [ThePansmith/Monifactory#611]
### Issue Summary

It seems that the DML multis are not working correctly.

### Reproduction steps

1. Try to use the simulation multi
2. Receive this: 
![image](https://github.com/user-attachments/assets/f78beafd-bc06-4022-8d13-592c39388fc4)

**Comment by JuiceyBeans** [comment]
Which recipe were you running?

**Comment by JuiceyBeans** [comment]
Caused by https://github.com/GregTechCEu/GregTech-Modern/issues/1829

**Comment by ThePansmith** [comment]
As stated above, GTm issue
