### ISSUE TITLE
[Bug]: Producing Budding Certus Quartz is currently impossible

### ISSUE THREAD

**Issue by Jaymus3** [ThePansmith/Monifactory#63]
### Issue Summary

Budding certus quartz requires an in-world transformation with charged certus quartz and a certus quartz block.  The certus quartz block is dictionary filtering correctly but the charged certus quartz is not, and ae2 charged certus quartz is unobtainable since the charger produces Gregtech certus quartz.
![CleanShot 2024-04-20 at 06 22 44](https://github.com/ThePansmith/Monifactory/assets/1351081/801cffa1-2185-45a8-8c4e-a6aa33a93e13)

### Reproduction steps

1. Try to craft budding certus quartz
2. It is not craftable without using cheats to swap the charged certus quartz from Gregtech to AE2

**Comment by WithersChat** [comment]
I'll look into it.
