### ISSUE TITLE
[Bug]: Shift-Clicking a recipe into a crafting station simply deletes the excess materials

### ISSUE THREAD

**Issue by Sammy-Jpeg** [ThePansmith/Monifactory#64]
### Issue Summary

when shift-clicking recipes to the crafting station with an attached inventory deletes the excess materials
i.e recipe requires X and in the connected inventory theres 32X's (example ammount), shift-click recipe and now theres only 1X in the crafting grid and the other 31X's is gone

### Reproduction steps

1. have a crafting stion connected to an inventory
2. have the ingredients of the recipe in the connected inventory
3. shift-click the recipe from EMI

**Comment by JuiceyBeans** [comment]
Couldn't reproduce

**Comment by alexanderpederson** [comment]
if there is a connected storage the extra is moved to that storage.
