### ISSUE TITLE
[Bug]: Game frequently crashes when setting ender io fluid filter with bucket

### ISSUE THREAD

**Issue by Bunnyshing1** [ThePansmith/Monifactory#642]
### Issue Summary

when setting an ender io fluid conduit filter with a bucket (the only thing i've tried to set the filter with) the world crashes and saves. 

This is what happened after trying to set a filter with an oxygen gas bucket
![Base Profile Screenshot 2024 08 31 - 23 38 05 62](https://github.com/user-attachments/assets/eed00856-3ec4-44dd-9e02-eaaab6ff066c)

Should be noted that this only happens SOMETIMES, and for me, can happen with any fluid bucket.

And the crash report says that FPS reducer could be the cause. Look into that maybe?

The game was open to LAN, I was sometimes running it in the background

### Reproduction steps

1. Get a bucket filled with any fluid, and an ender io fluid filter
2. set the filter of any slot of the ender io fluid filter with the bucket.
3. try around 10 times because this does not crash the game always.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Embeddium instance tainted by mods: [gtceu, oculus, bocchium]
// Please do not reach out for Embeddium support without removing these mods first.
// -------
// Daisy, daisy...

Time: 2024-08-31 23:56:52
Description: mouseReleased event handler

	Crash Report UUID: b0c69744-9a9c-4893-b200-f3866769c7b5
	FML: 47.2
	Forge: net.minecraftforge:47.2.21
	Flywheel Backend: Off
	Suspected Mods: None

sorry the whole crash report was too long to submit. i thought these were the important bits
```

**Comment by bfleischhacker** [comment]
[crash-2024-09-03_01.00.36-client.txt](https://github.com/user-attachments/files/16843674/crash-2024-09-03_01.00.36-client.txt)

heres a full crash log

**Comment by ThePansmith** [comment]
Enderio Issue, report to them
