### ISSUE TITLE
[Feature]: Improve Fluid Conduits Export

### ISSUE THREAD

**Issue by dadsarefuny** [ThePansmith/Monifactory#645]
### Suggestion

Two ender fluid conduits with tier 4 upgrades can hardly keep with with a consumption of 100 mb per tick. I don't know if perhaps Ender IO has had some major overhaul but they desperately need buffs.

**Comment by JuiceyBeans** [comment]
Report to EIO devs but don't expect a response, 1.20.1 has limited support
https://github.com/Team-EnderIO/EnderIO

**Comment by dadsarefuny** [comment]
> Report to EIO devs but don't expect a response, 1.20.1 has limited support https://github.com/Team-EnderIO/EnderIO

Is there no way to go into the source code directly and change it just for the modpack specifically? Also, the IO devs don't exactly have a good reputation of listening to feedback...

**Comment by JuiceyBeans** [comment]
> > Report to EIO devs but don't expect a response, 1.20.1 has limited support https://github.com/Team-EnderIO/EnderIO
> 
> Is there no way to go into the source code directly and change it just for the modpack specifically? Also, the IO devs don't exactly have a good reputation of listening to feedback...

EIO Unofficial used to do some stuff like this, until it was discontinued because EIO devs picked up support for 1.20.1 temporarily because of Moni

**Comment by ThePansmith** [comment]
Report to EIO
