### ISSUE TITLE
[Bug]: Extraterrestrial matter is way too good.

### ISSUE THREAD

**Issue by dadsarefuny** [ThePansmith/Monifactory#646]
### Issue Summary

Consuming only one Extraterrestrial matter gives 46 levels from zero levels. If you have more than 46 levels and consume it, it will give you the standard amount. However, combine with with an obelisk and you get infinite experience at little to no cost.

### Reproduction steps

1. Consume extraterrestrial matter with you levels being below 46

**Comment by yakla** [comment]
i know why its like that. i had the same bug and i checked why its like it it looks to add 10 expirence not to your expirence levels but to a different value that it saves . this is why its alaways return to a certain level. i think its might be all the expirence that you have gather and not all the expirance thats on you but im not sure

**Comment by dadsarefuny** [comment]
> i know why its like that. i had the same bug and i checked why its like it it looks to add 10 expirence not to your expirence levels but to a different value that it saves . this is why its alaways return to a certain level. i think its might be all the expirence that you have gather and not all the expirance thats on you but im not sure

Yeah, as I progressed, it kept giving me more and more experience. I'm at 60 levels per matter right now lol.

**Comment by dadsarefuny** [comment]
It seems to have been patched out
