### ISSUE TITLE
[Bug]: crash while hovering over fluids in emi (only in the search thing on the right)

### ISSUE THREAD

**Issue by kads-e** [ThePansmith/Monifactory#649]
### Issue Summary

happened to me since updating to 0.8.1 from I believe 0.7.2, stuff I have pinned and in recipes work fine, only searching crashes me

I use prism on windows 11

### Reproduction steps

1. open minecraft
2. let emi load in
3. hover over fluid
4. *saving world* into crash

### Relevant log output

```shell
https://paste.gg/p/anonymous/5a5d2127a4fe4f25a93ce6e569888e83
```

**Comment by JuiceyBeans** [comment]
Report to EMI

**Comment by kads-e** [comment]
turns out the problem was one of my EMI settings
it was either append mod ID or  append item mod ID (would assume the first one, but whatever) (also dont really feel like crashing my game 50 times again)
this problem also seems to only be with newer versions, on another instance that is on harder that I hadnt updated it works fine

**Comment by kads-e** [comment]
both settings need to be on btw, not off
