### ISSUE TITLE
[Bug]: Nimismatic Power Quest on Hardmode 0.8.1

### ISSUE THREAD

**Issue by DoughnutDev** [ThePansmith/Monifactory#659]
### Issue Summary

I am playing on hardmode and I noticed that the quest line in early game called Numismatic Power calls to use Deep Mob Evolution setup to generate diamonds for the dynamos, but in hardmode Deep Mob Evolution is disabled. Not sure if this is a bug or just a quest that wasn't removed when switching to hardmode. 

### Reproduction steps

Open Quest Book
Go to Early Game
Go to bottom right where the dynamo is

![image](https://github.com/user-attachments/assets/53421382-e61d-4eea-9e0b-dfc608799734)

**Comment by Xefyr0** [comment]
Fixed as of 0.9.8, but it's suggested you update to 0.9.10 or later to take advantage of the hotfixes.
