### ISSUE TITLE
[Bug]: HNN Data Models can be made (wrongly) by right-clicking a mob

### ISSUE THREAD

**Issue by SirWoofie** [ThePansmith/Monifactory#662]
### Issue Summary

Hostile Neural Networks' only method of training Data Models is to place them in the Simulation Chamber. However, when creating a Data Model by right-clicking a mob, you get a Faulty Data Model which can't be trained in the Simulation Chamber. If a Data Model is crafted using the recipes (ie. Zombie by adding a Data Model to rotten flesh) it is a Basic Data Model, which can be trained in the Simulation Chamber.

Expected behavior is to have the right-click feature disabled so only crafting the Data Models is possible. Alternatively, enable the in-world training by killing mobs to allow the Faulty tier to be upgraded to Basic.

### Reproduction steps

1. Obtain a Model Framework.
2. Right-click a (supported) mob with it.
3. See the Faulty tier.
4. Place in Simulator and be told it's too low tier.
5. Obtain a second Model Framework.
6. Craft it with a Zombie Flesh to get a Zombie Data Model.
7. See the Basic tier.
8. Place in Simulator and see it work.

**Comment by JuiceyBeans** [comment]
Right clicking is not the intended way to use this. Peaceful mode is the intended playstyle and as such, mobs don't spawn and you're supposed to craft it instead

**Comment by JuiceyBeans** [comment]
Could add a conversion recipe to turn it back into a blank data model though

**Comment by SirWoofie** [comment]
Yes, a recipe to reset a data model would be good too
