### ISSUE TITLE
[Bug]: Questbook needs to mention early nether quarts production

### ISSUE THREAD

**Issue by jeytee84** [ThePansmith/Monifactory#664]
![2024-09-03_16-39-34_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/60c994a1-e886-4288-8cad-1c3a0b946fef)
The boilers and turbines quest requires quartz for the steam pipe (fused quartz)
![2024-09-03_16-39-39_java_Monifactory_(BETA)](https://github.com/user-attachments/assets/37654d38-4b9a-48c0-afa2-553d65e8a1a0)
even though the nether is quite far from this stage.
It should be mentioned that the nether is not required to achive it but it can be electrolized from glass.

**Comment by JuiceyBeans** [comment]
Quartz can be bought in normal mode using Monicoins, and you can also just. Destroy buildings made out of them
