### ISSUE TITLE
[Feature]: Redstone wiring for automation

### ISSUE THREAD

**Issue by Reemuson** [ThePansmith/Monifactory#665]
### Suggestion

Been loving the pack so far playing in the Harder mode. However when it comes to automating machines with covers. Connecting machines with redstone dust just isn't ideal. The EnderIO redstone conduits do not connect to machine covers and there is no alternative from what I've seen so far.

A BuildCraft style bundled cable/covered cable and red alloy wire would be a very useful addition. With single block redstone logic gates as well.

An additional change would be to enable the redstone parts from the Create mod in the Harder mode

**Comment by DannyDan4** [comment]
I would like to formally put in a request for projectred to go with this, as it is updated for 1.20.1

**Comment by hgjensen** [comment]
I would recommend Redstone Pen instead. Very light weight mod and also adds programmable redstone and a couple of usefull components.

**Comment by Xefyr0** [comment]
ProjectRed has been added as an optional compat.
If you have an issue with Conduits not connecting to machine covers, make an issue on the EnderIO repository:
https://github.com/Team-EnderIO/EnderIO/issues
