### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BranDynamite** [ThePansmith/Monifactory#670]
### Issue Summary

Ender fluid conduits does not extract from chemical reactors when their input buffers contain fluids

### Reproduction steps

1. Place down 2 mv chemical reactors
2. Fill in the input and output fluid buffers of the first chemical reactor
3. connect the 2 reactors with ender fluid conduits
4. The second reactor will not fill up with any fluids

**Comment by ThePansmith** [comment]
Report to EIO
