### ISSUE TITLE
[Bug]: Extraction Speed Upgrades do not work on ender fluid conduits.

### ISSUE THREAD

**Issue by dadsarefuny** [ThePansmith/Monifactory#671]
### Issue Summary

I have a tier 4 extraction speed upgrade on an ender fluid conduit, running from one barrel to another. I was experimenting to see exactly why fluid conduits have been so terrible and this told me exactly why. You get the exact same through put as a completely normal fluid conduit as a fully upgraded one.

### Reproduction steps

1. Have two drums with a ender conduit leading into each of them
2. Put an extract speed upgrade on the conduit 
3. Compare the conduit to one without an upgrade

**Comment by ThePansmith** [comment]
Report to EIO
