### ISSUE TITLE
[Bug]: Effortless Building Muscles Dupe

### ISSUE THREAD

**Issue by ThePinkPotato** [ThePansmith/Monifactory#682]
### Issue Summary

The muscles from the effortless building mod get duplicated.

### Reproduction steps

Open chest with muscles in it.
Take muscles out
Right click to use 
open chest again - muscles should appear in hotbar
Repeat

**Comment by ThePinkPotato** [comment]
Might only work for lootr chests. my minecraft crashed before i could try

**Comment by Yokoharu** [comment]
Duplicate of #514. Known issue with the mod itself.
