### ISSUE TITLE
[Bug]: Text sticks out of the Simulation Chamber GUI

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#692]
### Issue Summary

![2024-09-14_19 20 10](https://github.com/user-attachments/assets/67e152c4-e281-4e7e-a249-bd2df68bf02c)

### Reproduction steps

Put a data model inside a Simulation Chamber and power it but don't put any Pulsating Prediction Matrix
Open the Simumation Chamber GUI

**Comment by ThePansmith** [comment]
Report to HNN devs
