### ISSUE TITLE
[Bug]: No LV recipe for electrolyzing aluminium on hard mode?

### ISSUE THREAD

**Issue by Boyownik** [ThePansmith/Monifactory#700]
### Issue Summary

I am currently playing this pack in Hard mode (0.8.5 version) and just crafted a basic electrolyzer to get silicone and aluminum, but to my surprise, the recipe says it has to be MV voltage. Is there any other way to make aluminum, or am I missing something?

### Reproduction steps

1. Throw some clay dust into Basic electrolyzer. 2. Not working :(

**Comment by Yokoharu** [comment]
At LV you need Green or Blue Sapphire to get aluminium dust on Hard Mode. If you check recipes for aluminium dust you can see that they are 20+ recipes in electrolyzer, you just need to cycle through them to find ones that work at LV
