### ISSUE TITLE
[Bug]: EnderIO energy conduits have no recipes

### ISSUE THREAD

**Issue by ExpLog** [ThePansmith/Monifactory#706]
### Issue Summary

I updated today from 0.8.1 to 0.8.6 and now none of the EnderIO energy conduits have recipes available. There's now one `Energy Conduit` that has no tooltip saying `Max Output X RF/t` that is craftable with the conductive iron recipe that has infinite throughput.

I'm not sure what kind of evidence I can provide for the no recipe issue.

Here's an screenshot of the unlimited conduit:
![image](https://github.com/user-attachments/assets/fe926560-bc2f-4a49-88f2-5ed9ad2d43a8)

### Reproduction steps

1. Try to check the recipe for any of the energy conduit the pack provides.
2. No recipe is available.

**Comment by ThePansmith** [comment]
Provide a Kubejs log

**Comment by ExpLog** [comment]
Here are the KubeJS logs. Wasn't sure which one you needed:

[server.log](https://github.com/user-attachments/files/17031787/server.log)
[startup.log](https://github.com/user-attachments/files/17031788/startup.log)
[client.log](https://github.com/user-attachments/files/17031789/client.log)

**Comment by ExpLog** [comment]
I'm digging a bit more around, and the bug might have happened due to upgrading the modpack due to GDLauncher. I'm going to try a clean install and I'll report back in a bit.

**Comment by ExpLog** [comment]
The problem was solved upon a clean install. Sorry for wasting your time.

The issue was that when updating the modpack through GDLauncher, it downloaded the new version of the mods and did not delete the older versions.
