### ISSUE TITLE
[Bug]: Smelting Gregtech silver dust produces Nuclearcraft Neotoric silver ingot with no uses

### ISSUE THREAD

**Issue by HESN** [ThePansmith/Monifactory#71]
### Issue Summary

Instead of receiving GT silver ingot I receive Nuclearcraft silver ingot that cant be used in recipes.

### Reproduction steps

Smelt GT silver dust in normal furnace
Makes unusable silver ingot

**Comment by JuiceyBeans** [comment]
Can't reproduce, are you sure you're on latest?

**Comment by Deepacat** [comment]
Also cannot reproduce on fresh install

**Comment by HESN** [comment]
Weird, I just tested today again to confirm. I macerated silver ingot to produce GT silver dust, smelt the dust in diamond furnace got Nuclearcraft Silver ingot. I'm on Moni 0.1.0 (first release). I'm playing on a server with same release.

**Comment by JuiceyBeans** [comment]
It's been fixed since then I suppose, doesn't persist on latest commit

**Comment by JuiceyBeans** [comment]
It's been fixed since then I suppose, doesn't persist on latest commit

**Comment by Deepacat** [comment]
Don't make bug reports for the first release lol everything is being changed constantly

**Comment by HESN** [comment]
> Don't make bug reports for the first release lol everything is being changed constantly

Alright will close then. Thanks.
