### ISSUE TITLE
[Feature]: Mystical Agriculture (Gregified & only outputs Raw Ores)

### ISSUE THREAD

**Issue by PlayfulPiano** [ThePansmith/Monifactory#729]
### Suggestion

This might be better off as a compact mod addon with config changes preloaded, but either way my suggestion is to include the Mystical Agriculture mod & change its config such that:
- Essence can only convert into raw ores
- Seeds are locked behind required voltage progression (no titanium seed before HV, no aluminium seed before MV, etc.)
- No alloy seeds or similar, only ore seeds (so no stainless steel seed, no redstone alloy seed, etc.)
- Possibly allow direct crafting methods for early game ore vein types (to potentially allow for a skyblock / gog styled challenge run of monifactory)
- Potentially set up custom GT machines for the purpose of processing MA contents

**Comment by ThePansmith** [comment]
Appreciate the effort put into the suggestion, but no. Mystical Agriculture inherently isn't interesting as a mod, and the player already has options for infinite ores.
