### ISSUE TITLE
[Question]: Is there a specific reason for the removal of Draconic Evolution

### ISSUE THREAD

**Issue by nohax955** [ThePansmith/Monifactory#736]
Is there a reason other than it not existing on 1.20.1 (which it does exist for said version)
Is it just too op or does it not fit in?
If you have said the reason already somewhere then i couldnt find it
you arent forced to reply to this comment

**Comment by ThePansmith** [comment]
In short, when the pack was first being developed, DE didn't exist on 1.20.1, so alternative mechanics were implemented in it's place. By the time DE did get ported, we already had progression laid out.
