### ISSUE TITLE
[Bug]: Naquadah Reactor II wont start after upgrading to 0.9

### ISSUE THREAD

**Issue by hgjensen** [ThePansmith/Monifactory#742]
### Issue Summary

Worked perfectly before. Tried /reload. Tried both encriched naquadah bolts and naquadria bolts.
Multi is formed and everything looks fine. Machine just says "Idling."

### Reproduction steps

Make Naquadah Reactor II.
I'm using ULV input and output bus with a UV 4A Dynamo Hatch.
Put Naquadria Bolts in the input bus. Watch as nothing happens.

**Comment by ThePansmith** [comment]
fixed in #761
