### ISSUE TITLE
[Feature]: change inventory highlight color to make it more visible. 

### ISSUE THREAD

**Issue by isnottree** [ThePansmith/Monifactory#746]
### Suggestion

Double clicking the EMI search bar causes it to highlight searched items in an inventory.  Currently, when using darkmode the highlight isn't "different" enough, which makes it barely better than normal at finding items. I did a brief search through EMI settings and didn't see any settings related to that, is that a setting a pack/user can configure?

**Comment by Xefyr0** [comment]
Dark Mode Everywhere's default preset has been changed to Toasted Light Mode - this should help significantly.
If this change does not occur on your end, then you can change it yourself with the "Dark Mode" button on the bottom-left corner of your inventory.
