### ISSUE TITLE
Logistic Cleanup

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#772]
With enderio getting patches, the point of this issue has changed.

## EnderIO
- [x] Note the throughput on fluid conduits via tooltip (EIO devs are doing this)
- [x] Update EnderIO, eio kjs

## LaserIO 
- [x] Unlocked in LV instead of MV
- [x] Move applicable quest

## Sophisticated storage 
- [x] Note hopper upgrades, etc. Maybe could give some in the applicable quest?

## Gregtech 
- [ ] Update to 1.4.5 (once it happens)

**Comment by guimas** [comment]
If I could suggest... make LaserIO cheaper for the LV and MV ages, i think it would reduce the grind a little in the beginning of the pack.

**Comment by ajbrink88** [comment]
Shouldn't this be fixed with the bugfixes from EIO?

**Comment by abculatter2** [comment]
While I know redstone signals aren't the biggest priority with EnderIO's conduits, it would be nice to have a redstone wire mod in the pack to replace the redstone conduits. More Red in particular could be good.

**Comment by ajbrink88** [comment]
Created https://github.com/ThePansmith/Monifactory/pull/825 to make laserio accessible in lv.
