### ISSUE TITLE
[Bug]: Top half of vanilla chests is glitched

### ISSUE THREAD

**Issue by Radk6** [ThePansmith/Monifactory#785]
### Issue Summary

Top part of vanilla chests is rendered incorrectly. Modded chests work fine

![2024-09-26_23 11 56](https://github.com/user-attachments/assets/22d68884-b32a-44ef-b840-a36f0bde90ef)

### Reproduction steps

1. Enter a world
2. Place a bunch of chests 

### Relevant log output

Latest.log: https://mclo.gs/1Yp2WyK

**Comment by OE100** [comment]
I'd suspect embeddium and try to mess around with some of it's settings to see if it fixes things

**Comment by Radk6** [comment]
> I'd suspect embeddium and try to mess around with some of it's settings to see if it fixes things.
> 
> maybe try to remove embeddium and it's related mods and see if it still happens, then you can report it to them if that solves it.

I updated from Beta 0.9.2 to 0.9.3, tried without Embeddium (and its' addons), ImmediatelyFast, BadOptimizations and ModernFix but the issue still happens.

**Comment by Radk6** [comment]
I did some digging and found a similar issue on reddit. Running the command `/flywheel backend batching` fixes the issue
