### ISSUE TITLE
[Bug]: the fluid tank in ender io voids fluids

### ISSUE THREAD

**Issue by yakla** [ThePansmith/Monifactory#799]
### Issue Summary

the bug is that for some reason the tank fluid is different for the inventory and the physical tank => what it means is that if i fill the tank from the inventory if i place it there is no fluid and the opposite. 

### Reproduction steps

1 craft ender io fluid tank
2 fill it with a certain fluid from the ui of one of the machins 
3 place it on the ground
4 pick up the tank and theres no fluid

**Comment by klaborda** [comment]
Question! Should this be submitted to enderio's github since this sounds like it might be enderio specific? https://github.com/Team-EnderIO/EnderIO/issues
