### ISSUE TITLE
[Bug]: Maintenage hatch not crafting in assembling machine

### ISSUE THREAD

**Issue by ivanthenerd** [ThePansmith/Monifactory#808]
### Issue Summary

When trying to make a maintenage hatch in the assembling machine, it just don't.

### Reproduction steps

1. Try making a maintenage hatch at an assembling machine with an LV hull and a programmed circuit 8
2. Just doesn't make it
![image_2024-09-28_123437558](https://github.com/user-attachments/assets/02c5be3f-950a-4908-b3df-45ff1e2ef847)

**Comment by Xefyr0** [comment]
Fixed in #793
