### ISSUE TITLE
[EM Feature]: Disable snad in Harder Mode

### ISSUE THREAD

**Issue by ZSusskind** [ThePansmith/Monifactory#810]
### Suggestion

With a little bit of one-time setup, snad effectively trivializes solid fuel production during late LV and MV, and can potentially even scale into HV. Snad also goes against the trend in Harder of encouraging native GregTech solutions to problems (by for instance disabling RF to EU conversion and EnderIO conduits). In particular, it currently overshadows alternate forms of early power generation including:
- LV oil processing: while players will generally set up oil processing eventually, it's completely possible to rush in LV using single-block pumps and distilleries plus long distance fluid pipelines.
- Pyrolyse ovens: With the greenhouse + pyrolyse oven, charcoal and coal gas are both solid sources of early power. This is a bit painful due to the need for five MV circuits in the greenhouse recipe, but a single greenhouse feeding two cupronickel pyrolyse ovens without any overclocking can easily yield over 1A HV _net_.

Overall, it feels like snad takes an interesting engineering problem and turns it into "spam moar sugar canes". I'd like to suggest it be removed from harder mode for this reason.

**Comment by Cosmoros-git** [comment]
Maybe instead of this make so boilers don't accept sugarcane as fuel. Getting XP in hard mode is annoying enough already.

**Comment by Xefyr0** [comment]
[Approved by Pansmith](https://discord.com/channels/914926812948234260/1229929078547550238/1290750143032983583)
Implemented in d5e747ec58b946762edc3cf9f628d14ce6bd004b

**Comment by Cosmoros-git** [comment]
Could sugarcane generally be nerfed as a fuel source? The burning time in the boiler is 0.15 seconds, while coal has 1/seconds at maximum power.
