### ISSUE TITLE
[Bug]: Fluid Tank placing voids content

### ISSUE THREAD

**Issue by LCoolJT** [ThePansmith/Monifactory#813]
### Issue Summary

When placing the enderio Fluid Tank it sometime voids its content

### Reproduction steps

1. fill Fluid Tank with fluid(thermal steam)
2. place fluid tank on the ground, check if fluid is voided
3. repeat

**Comment by ThePansmith** [comment]
Report to enderio

**Comment by LCoolJT** [comment]
https://github.com/Team-EnderIO/EnderIO/issues/832:
"Please update Ender IO to 6.1.10-beta or later and try again, as this issue should be resolved. Thanks!"
