### ISSUE TITLE
[Bug]: Ender IO Vacuum Chest Can't Hold a Filter

### ISSUE THREAD

**Issue by rrenode** [ThePansmith/Monifactory#815]
### Issue Summary

There is visually a slot to place to Ender IO filters in the vacuum chest, however they cannot be placed there.

Not sure if this is simialar to the known issue regarding Ender IO fluid conduits.

### Reproduction steps

1. Place a vacuum chest
2. Try to place a filter into it (Click the filter in your inventory and attempt to move it to visual filter slot)

**Comment by ThePansmith** [comment]
Report to enderio
