### ISSUE TITLE
[Bug]: Output resets for Basic Electric Furnace

### ISSUE THREAD

**Issue by Macomar** [ThePansmith/Monifactory#818]
### Issue Summary

The output setting resets after every relog in the world.
![image_2024-09-30_101324420](https://github.com/user-attachments/assets/c372c8cd-7380-48ba-9973-4e9435a694e4)

### Reproduction steps

1.Setup the output face of the Electric Furnace (LV is the only one tested)
2.Exit the world
3.Open the world back
4.The faces will be reset

**Comment by Xefyr0** [comment]
Known issue with Gregtech: Modern. Will be fixed the next time the mod updates.
