### ISSUE TITLE
[Bug]: Quests complete without meeting requirements

### ISSUE THREAD

**Issue by LCoolJT** [ThePansmith/Monifactory#820]
### Issue Summary

Some quests/items get recognised by the questbook without having the right item
warden data and the bromine quest got completed/checked without having the items in my inventory

### Reproduction steps

Idk, i didnt notice when they got completed

**Comment by esmenard** [comment]
I think it happened as soon as Monifactory was launched in 0.9.3, probably has to do with #771 replacing a "nothing" quest (which is completed without requirements) by the Bromine quest

**Comment by Xefyr0** [comment]
Can confirm that the bromine quest completion is a side effect of #771.
"Warden Data" is not a requirement for any quest, although it is possible that with all of the Sculk content rewrites that it went through a similar event.
