### ISSUE TITLE
[Bug]: Questbook loadingtime

### ISSUE THREAD

**Issue by Ercument5038** [ThePansmith/Monifactory#827]
### Issue Summary

It takes a extra time when opening the Questbook the first time after loading into the game. After the first time it opens up instantly

### Reproduction steps

1. Load into the Game
2. Open the Questbook
3. See that it takes longer to show up then normally

**Comment by Xefyr0** [comment]
This is due to the combination of Minecraft's internal changes and the optimization mods we added - more of the loading time was moved from immediately after you launch the pack to the time you load into the world for the first time, including FTBQuests reading its files.
