### ISSUE TITLE
[Bug]: Conveyor disappears upon entering the world

### ISSUE THREAD

**Issue by RRhuman2004** [ThePansmith/Monifactory#828]
### Issue Summary

Conveyor disappears upon entering the world

### Reproduction steps

Automated electric furnace at LV to pull from barrel, used Lv Conveyor for it but everytime i relog in the world the coveyor attached to it is gone and I have to re add it. In hard mode.

**Comment by Yokoharu** [comment]
What furnace are you using? The ones from more furnaces have automatic output.

**Comment by ThePansmith** [comment]
Report to GTm
