### ISSUE TITLE
[Bug]: maintenance hatch recipe conflict with dark steel hull/ iron jetpack thrusters NBT data messed up

### ISSUE THREAD

**Issue by Canbinlol** [ThePansmith/Monifactory#830]
### Issue Summary

1. The maintenance hatch and dark steel hull shares lv hull and circuit 8 and the maintenance recipe is not working. Changing the dark steel hull circuit to 4 should work. 

2. AE is very confused about the NBT of iron jetpack thrusters. They seem to be very inconsistent when crafted and shows one of the 3 results randomly(even if the pattern only shows one of them) that is:  {Id: "ironjetpacks:conductive_iron"}, {Id:"ironjetpacks:conductive_iron", Throttle: 1.0d} and {Throttle: 1.0d, Id: "ironjetpacks:conductive_iron"}. AE really does not like the NBT randomness.

### Reproduction steps

1. put lv hull into assembler with circuit 8. 

2. try to code with crafting pattern and craft a higher level jetpack with ae, like the angel ring.

**Comment by Canbinlol** [comment]
Also I used the "update" modpack function in PolyMC launcher and I do not know how it replace the older files so it might be PolyMC not updating the newer kubejs script, though I do currently play on the newest version that is beta 0.9.3.

**Comment by ThePansmith** [comment]
First one has been fixed, but not the second.

**Comment by Xefyr0** [comment]
@Canbinlol You shouldn't do multiple issues in the same thread or it gets harder to organize and search for them.

Issues 1 & 2 have been fixed as of 0.10.3, but any issue you may have with PolyMC not updating Monifactory properly is an issue with PolyMC. Prism and Curseforge launchers do it properly if they're updated to the latest version.
