### ISSUE TITLE
Starter item dupe.

### ISSUE THREAD

**Issue by ThaSilentOne** [ThePansmith/Monifactory#839]
### Issue Summary

Upon booting up the newest update of monifactory (9.3) in my save that is well into MV, I found that the starter item quests had been re-completed. I believe it has to do with the latest update, perhaps the quest had been re-enabled.
![2024-10-03_08 00 27](https://github.com/user-attachments/assets/ac86e78a-419e-4467-95c2-eae7ae4f9192)

### Reproduction steps

All I did was boot up a save that already had a completed starter items quest in the latest modpack version. (9.3)
However I failed to get a ss prior.

**Comment by JuiceyBeans** [comment]
Can reproduce, although I think this shouldn't persist across updates. Can be closed I think
