### ISSUE TITLE
[Bug]: Energy Converter does not transfers FE to EnderIO Conduit

### ISSUE THREAD

**Issue by Fladort** [ThePansmith/Monifactory#844]
### Issue Summary

Got an issue with the gregtech energy converter. It doesn't push it's energy into any conduit from enderIO.

Got this issue in 9.3 and updated to 9.5 but the issue still persists.

Here's an example of a simple setup using creative GT Energy on two converters. One facing a capacitor bank and the other on a conduit. Both are set up to do EU to FE.
![2024-10-03_19 14 15](https://github.com/user-attachments/assets/b759a97c-696a-4c02-91f1-f7f4ce5b1e6b)

Note that the capacitor bank uses "uI" and the conduit "RF". Seems the conversion from "FE" to "uI" work, but FE to RF don't work. (Normally should not be an issue, but I don't know enough tell if it is)

### Reproduction steps

1. Place an energy Converter
2. Use a soft mallet to change from "RF to EU" to "EU to RF"
3. Power the converter with appropriate EU power on the correct side
4. Use any EnderIO conduit to take power to anything that can receive RF/uI/FE

**Comment by ThePansmith** [comment]
Report to EnderIO or GTm
