### ISSUE TITLE
[Feature]: Rename Harder Mode to Expert Mode

### ISSUE THREAD

**Issue by inigmatus** [ThePansmith/Monifactory#846]
### Suggestion

For the sake of sanity. There is consensus driven agreement too on this. You even have the word "harder" listed in places where hard mode is the context. Making for absolute confusion when trying to modify the pack.  There are 29 mentions of Harder in the pack. Maybe a few file names. But only Pansmith could prob pipe this all properly to make sure things don't break. I highly recommend this change though before 1.0 release.

**Comment by DreamThorn** [comment]
I agree.
Even in the mode swap batch file you have to press 'E' to get harder mode; I thought it stood for "even harder", but I think "expert" fits better.
