### ISSUE TITLE
[Bug]: Usability: confusing text on enable/disable input buttons

### ISSUE THREAD

**Issue by Spongman** [ThePansmith/Monifactory#847]
### Issue Summary

![image](https://github.com/user-attachments/assets/0c5dccda-75e5-4ab5-926f-101f62ae01c2)

this hover text is ambiguous/confusing, it could be read in two conflicting ways:
- it could be read that "disable" is the verb that clicking the button will perform. ie. click the button to disable items from entering the output side.
- it could also be read as that the current state of this feature is that item input is disabled.

better text would be:
- "input items from output side: enabled"
- "input items from output side: disabled"

### Reproduction steps

open the side UI. hover the button

**Comment by ThePansmith** [comment]
Report to gtm
