### ISSUE TITLE
[Bug]: Update to Snad 3.0.0

### ISSUE THREAD

**Issue by Leclowndu93150** [ThePansmith/Monifactory#848]
### Issue Summary

Fixes Snad blocks not Falling, and sometimes weird redstone detection

it's basicaly a rewrite

### Reproduction steps

.

**Comment by circuitgamer77** [comment]
I want to add to this, I encountered a crash with this version of Snad if you try to grow kelp with it (the crash when the mod is isolated shows that the mod can't find the "age" attribute for kelp), but it's fixed in 3.0.0.  I'm going to try just manually updating the mod for now though.

**Comment by Leclowndu93150** [comment]
i didn't know this was for Monifactory. Thanks for the report anyways

**Comment by Xefyr0** [comment]
Done in commit 83eace48f5f90fb72a4f2ae39c67d1705947cebd
