### ISSUE TITLE
[Bug]: Sophisticated Storage Barrel duping automatically

### ISSUE THREAD

**Issue by DreamThorn** [ThePansmith/Monifactory#849]
### Issue Summary

I crafted the "spruce" barrel for the quest in the starting chapter, but when I placed it, it was invisible in world until I clicked it, but it stayed in my inventory.  When I clicked the in-world barrel it became visible, and it was made of acacia wood.

### Reproduction steps

1. Play on Harder Mode.
2. Craft three minecraft barrels from acacia planks and slabs, with an iron saw.
3. Combine them with six iron ingots to make the Sophisticated Storage Spruce Barrel.
4. Right click to place it.
5. Now you have an invisible acacia barrel in world and you still have the spruce barrel in your inventory.
6. It might also be invisible in your inventory (I can't quite remember), but if you sort your inventory or click on its slot you should find it.

**Comment by DreamThorn** [comment]
It hasn't happened again yet, so it might have been fixed in the new version.

**Comment by Xefyr0** [comment]
You likely pressed the Alt key, which enables Effortless building.
As a result of this bug and others, Effortless Building has been removed in dev: https://github.com/ThePansmith/Monifactory/pull/1056
