### ISSUE TITLE
[Bug]: Gregtech fluid Pipe duplication with effortless building

### ISSUE THREAD

**Issue by vsn4ke** [ThePansmith/Monifactory#856]
### Issue Summary

I was putting potin pipe down with effortless building active and i realized that pipes in my inventory was not used.
the duplication seems to appear when you place a pipe next to an other pipe (so not the first one)

after testing, item pipes don't seem to be affected 

pack version: 0.9.5
hard mode

### Reproduction steps

1. active effortless building
2. place gregtech fluid pipe next to each other
3. pipes are not used

**Comment by Xefyr0** [comment]
As a result of this bug and others, Effortless Building has been removed in dev: https://github.com/ThePansmith/Monifactory/pull/1056
