### ISSUE TITLE
[Feature]: Add missing elements to Periodic Table

### ISSUE THREAD

**Issue by NordicRest** [ThePansmith/Monifactory#863]
### Suggestion

I really love the Periodic Table that this pack, among others, do. However, there are a few elements which are in the modpack but aren't on the table. They are:

1. Bismuth. Obtainable from cassiterite ore (not cassiterite _sand_ ore, as I discovered), and used in Red Steel.
2. Iodine. Obtainable from brine processing, used in RadAway.
3. Radium. Kind of obtainable, as Radium Salt from T2 Microminers, though it's Rock Salt and Radon, the later of which is a different element entirely.
4. Holmium. Obtainable from Alien Scrap processing, and used as the UIV superconductor.

I'd love to see these added as further quests.

**Comment by WithersChat** [comment]
The table's purpose is to keep track of Omnium, so it makes no sense to have the named elements as part of the table.
