### ISSUE TITLE
Nuclearcraft stuffs

### ISSUE THREAD

**Issue by ThePansmith** [ThePansmith/Monifactory#865]
## Nuclearcraft 
Now that EnderIO is back online, the only real sticking point of the pack left is NC:N.
- [x] Get crashlog of NC:N crashing on servers w/ newer patches of the mod, report it to the dev
- [x] Fix or Remove HP steam and relevent quest
- [ ] Buff Reactors

If NC:N cannot be fixed, look into alternative options, perhaps a standalone backport of the MI Reactor? idk

**Comment by ThePansmith** [comment]
Issue has been reported in https://github.com/igentuman/NuclearCraft-Neoteric/issues/123

**Comment by PineappleCat22** [comment]
Cannot reproduce crashes, but I have found that one of your KubeJS scripts (/unification/tags.js) prevents players from joining a server. If you send crash logs I'd take a look at them as well (as the log provided in https://github.com/igentuman/NuclearCraft-Neoteric/issues/123 does not point to any NC:N code).
