### ISSUE TITLE
[Bug]: Visual bugs with Chipped glass and water

### ISSUE THREAD

**Issue by esmenard** [ThePansmith/Monifactory#866]
### Issue Summary

Water is not rendered behind some faces of Clear Leaded Glass from Chipped. I was not able to reproduce the issue with Chipped alone, so it must come from the interaction with some other mod from this modpack.
![2024-10-06_23 26 14](https://github.com/user-attachments/assets/56a0fe02-29fb-4fb6-b877-11ccbd8c7411)

### Reproduction steps

Build a pool of water surrounded by Clear Leaded Glass
Look at it from each side
The water will render correctly from some sides and not from others

**Comment by yakla** [comment]
i think you need to report this to the chipped mod repo and not to the moni modpack

**Comment by ThePansmith** [comment]
Try testing with various optimization mods on and off to see which it could be
