### ISSUE TITLE
[Feature]: Add wrenches as a valid tool for moni custom blocks

### ISSUE THREAD

**Issue by ayejayyy** [ThePansmith/Monifactory#867]
### Suggestion

![image](https://github.com/user-attachments/assets/4887f817-692d-4a38-bdc8-867f099cecee)
moni custom blocks, e.g. omnic matrix casings, don't have a wrench tagged as a valid tool - considering it is a 'machine casing', I think it will be a qol improvement to add the block tags

**Comment by Xefyr0** [comment]
Fixed in 30d526855e348fb7649c19baed58c6a05a76a876
