### ISSUE TITLE
[Bug]: Harder mode cannot reach UIV and UXV, but assembly line recipes require

### ISSUE THREAD

**Issue by XNFu233233233** [ThePansmith/Monifactory#870]
### Issue Summary

I'm making a Helical Fusion Reactor but it requires UIV.
The highest 4a uhv in the energy input hatch can only reach UEV
Can't make 16a because the transformer has no recipe
UEV UIV energy input hatch has no recipe
MAX processors require UXV
But there is no way to achieve UXV
The corresponding enetgy output hatch also lacks a recipe
Monium Ingot also requires UIV voltage, please fix it as soon as possible.
### Reproduction steps

none

**Comment by ayejayyy** [comment]
![image](https://github.com/user-attachments/assets/6fdd2a38-f956-4e3b-ae6e-7bb6f25d7035)
hev energy hatch exists, maybe reload the pack?

**Comment by XNFu233233233** [comment]
> ![图像](https://private-user-images.githubusercontent.com/88769206/374119940-b0e405d0-93b6-4307-aebe-f40d37446e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTg0NDEsIm5iZiI6MTcyODI5ODE0MSwicGF0aCI6Ii84ODc2OTIwNi8zNzQxMTk5NDAtYjBlNDA1ZDAtOTNiNi00MzA3LWFlYmUtZjQwZDM3NDQ2ZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEwNDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTY0ZTNkYTIyNTMxNjI5ZTNiOTk3ZjE1ZTg0NWY4ZmM5OGIwNjZiMTAzZTI5ZTI5Zjc2YjY0MDM1NjczMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zre2BlYrJRhoZMZLnrTGB1yCnygHyxCCx7SuDf0Ve_0)
> 
> uev 能量舱口存在，也许重新加载包？

This problem exists in harder mode. I don't know if it is intentional, but this way you cannot make a MAX processor.
Neither normal nor hard have this problem
