### ISSUE TITLE
[Feature]: Add Apotheosis and fully disable villager trading.

### ISSUE THREAD

**Issue by Cosmoros-git** [ThePansmith/Monifactory#881]
### Suggestion

Due to my love of finding a way to do less and get more, I have got to the results that tell this:
A: Villagers are freaking busted. 
B: You can skip a lot of progression with villagers. 
C: They sell almost every single enchant book.
D: Enchantment ngl is useless or forgotten. 

Adding Apotheosis makes enchantments last for longer and be more enjoyable. And if done well will fit great in the early game. It also changed enchanting from levels to XP making Expert Mode enchant table more viable.

**Comment by Cosmoros-git** [comment]
Secondary addition, FTB Ranks. Allows for much simpler management of permissions for servers by rank.

**Comment by Cosmoros-git** [comment]
While testing things out, it appears that easy anvils do not function correctly with Apotheosis. Created an issue on the apotheosis part.

**Comment by Xefyr0** [comment]
Apotheosis is so out-of-place thematically that it's safe to say that it will not be added - even Ensorcellation was almost entirely disabled except QoL enchantments.

If you want Apotheosis while playing Monifactory, you can add it to your own instance of the modpack (as you have already been doing)
