### ISSUE TITLE
[Bug]: Pyrolyse Oven duplicate recipes

### ISSUE THREAD

**Issue by KePiadina** [ThePansmith/Monifactory#882]
### Issue Summary

Pyrolyse Oven multiblock has duplicate recipes:
Circuit 1 + 16 Log -> 20 Charcoal + Creosote
overwrites
Circuit 1 + 16 Log -> 20 Charcoal + Wood Vinegar

### Reproduction steps

1. Insert 16 Logs into Pyrolyse oven
2. Set programmable circuit to 1
3. Creosote comes out instead of Wood Vinegar (or viceversa)

**Comment by WithersChat** [comment]
Not the case on latest (wood vinegar recipe uses circuit 7)
