### ISSUE TITLE
[Bug]: Cant open Iron Door

### ISSUE THREAD

**Issue by luisestrada115** [ThePansmith/Monifactory#885]
### Issue Summary

I cant open Iron Doors? the ones that spawn in cities and crafted ones like the one for the clean room

### Reproduction steps

craft a door, place it, and it wont open?

**Comment by Possseidon** [comment]
Iron doors (and trapdoors) can only be opened via redstone, e.g. a lever on a block next to the door. That's a [vanilla mechanic](https://minecraft.wiki/w/Iron_Door#Usage).

**Comment by luisestrada115** [comment]
Thanks, first time in omni/moni factory style packs. Cleanroom was suggested to use Iron Door, so I couldn't get in :).

Discord suggested to use any door, which worked.
