### ISSUE TITLE
[Bug]: Barrel assembler recipe (no circuit) taking priority over wooden drum recipe (circuit  2)

### ISSUE THREAD

**Issue by FabricioTrude** [ThePansmith/Monifactory#886]
### Issue Summary

if I try to craft a wooden drum (wooden barrel) it crafts wooden barrel :(

### Reproduction steps

put  more than 4 wood in assembler with circuit  2, it will craft barrel insteead.
![image](https://github.com/user-attachments/assets/5f3c1d56-9fa8-4ae2-987b-e0229bf6116a)
![image](https://github.com/user-attachments/assets/f64ec92f-fc79-4a2c-a2e5-7f62e232480c)

### Relevant log output

```shell
this is avoidable with a robo arm with keep exact, if there is less than 7 it wont craft the vanilla barrel.
```

**Comment by Cosmoros-git** [comment]
This is an issue with all wood recipes because of that. Wasn't it supposed to have been fixed? I reported it in almost every update.

**Comment by ThePansmith** [comment]
GTm issue, suppose we could just slap down a temp recipe

**Comment by Xefyr0** [comment]
Resolved by a GregTech CEu: Modern update in or before latest release.
