### ISSUE TITLE
[Bug]: Cakes don't tell you what they're refilled with

### ISSUE THREAD

**Issue by Niki4tap** [ThePansmith/Monifactory#893]
### Issue Summary

(Harder mode, moni version 0.8.1)

![quest](https://github.com/user-attachments/assets/e16146a9-cb14-4093-82b9-aeb657b77be7)

The quest about teleporting cakes tells you they show what they're refilled with in their tooltips, which is not true.

![tooltip](https://github.com/user-attachments/assets/32266bdd-cbf0-4e55-b730-1e3c84e4c0a2)

Wasn't sure if it's a mod misconfig, broken mod, or just a lie in the quest description, so submitted as a separate bug

### Reproduction steps

1) Look at the cake tooltip
2) See nothing about how to refill

**Comment by Xefyr0** [comment]
Tooltips added as described in 2809facbdb970c6297947636e198b46293d5325e
