### ISSUE TITLE
[Bug]: "Pyrolyse Oven" quest tasks are insufficient

### ISSUE THREAD

**Issue by Spongman** [ThePansmith/Monifactory#895]
### Issue Summary

![image](https://github.com/user-attachments/assets/572a7111-9864-4736-9abd-9a9a9581a6d8)

The Task for this quest calls for 33 blocks, which is insufficient for a Pyrolyse Oven multiblock.

### Reproduction steps

open the Pyrolyse Oven quest

**Comment by Xefyr0** [comment]
Fixed in 0.10.0.
