### ISSUE TITLE
[Bug]: Snad recipe

### ISSUE THREAD

**Issue by tturlin** [ThePansmith/Monifactory#905]
### Issue Summary

There is a problem with the yellow snad recipe, it still got the normal recipe with two block of sand
![image](https://github.com/user-attachments/assets/8fa90f55-8971-4947-ab0a-aebcd6f53b13)
when the red snad doesn't
![image](https://github.com/user-attachments/assets/d0db5549-9c53-47a8-810b-8f744af7712d)

I think there is a problem with the recipe removing in kubejs

### Reproduction steps

1. Put two sand in the crafting table
2. get a snad

3. put two red sand in the crafting table
4. dont get red snad

**Comment by Canbinlol** [comment]
I think this is fixed in the newest version which is 0.9.5.

**Comment by Xefyr0** [comment]
Yes, this has been fixed.
