### ISSUE TITLE
[Bug]: Can't craft Molybdenum Ore

### ISSUE THREAD

**Issue by NordicRest** [ThePansmith/Monifactory#915]
### Issue Summary

Molybdenum Ore can't be crafted, as the recipe overlaps with the shapeless Moniquarter -> Moninickel recipe. This is the only recipe affected by this bug, as it's the only one that uses a single Moniquarter.

EMI recipe for Molybdenum Ore:
![image](https://github.com/user-attachments/assets/ee991751-5866-4d32-ad13-52bfdf1c2254)

Result in an actual crafting table:
![image](https://github.com/user-attachments/assets/42181851-ff87-4400-a2f0-9a303848ba3f)

### Reproduction steps

1. Place a Moniquarter in the centre-right square of the crafting grid, as indicated by its recipe in EMI.
2. Result is 5 Moninickels appearing in the product square.

**Comment by Shragdhar** [comment]
Have you tried pressing the (+) button right next to the recipe? I've noticed that sometimes the only way to craft the recipe is by pressing the (+) button.

**Comment by NordicRest** [comment]
> Have you tried pressing the (+) button right next to the recipe? I've noticed that sometimes the only way to craft the recipe is by pressing the (+) button.

This didn't work. Using the (+) results in the coin going in the top right square, which also results in Moninickel output.
