### ISSUE TITLE
[Bug]: Crash upon opening ME pattern encoder and holding SHIFT

### ISSUE THREAD

**Issue by kaweepatinn1** [ThePansmith/Monifactory#917]
### Issue Summary

Crash anytime I open the pattern encoder, was using it to make some patterns and then it crashed once and is now permanently bricked, breaking and placing does not solve the problem.

### Reproduction steps

Open pattern encoding terminal
Press shift
Crash

### Relevant log output

```shell
https://pastebin.com/MG85jatf
```

**Comment by ThePansmith** [comment]
Is this a moni issue?

**Comment by kaweepatinn1** [comment]
sorry, im not really too  knowledgeable on where to report things - it's about conflicting mods (fancy menu x ae2), would that be reported here or both of their mod pages?

**Comment by ThePansmith** [comment]
To the applicable devs. We dont maintain fancy menu or ae2, nor do their devs check here.
