### ISSUE TITLE
[Bug]: Powered Spawner and Broken Spawner cannot be combined in an Anvil

### ISSUE THREAD

**Issue by Giovanni-NL** [ThePansmith/Monifactory#926]
### Issue Summary

![image](https://github.com/user-attachments/assets/83c18463-5285-4163-ba04-a247accd941d)
When trying to combine a freshly crafted Powered Spawner with any kind of Broken Spawner (looted or changed via Soul Binder), the Anvil does not accept the recipe.  
The result should be a Powered Spawner set to the mob type of the Broken Spawner.
I am using pack version 0.9.5
![image](https://github.com/user-attachments/assets/9410b697-7684-4c40-befe-ec296d84a28a)

### Reproduction steps

Place a Powered Spawner and a Broken Spawner in an Anvil

### Relevant log output

```shell
Nothing in the logs. Other than placing the items in the Anvil, nothing happens.
```

**Comment by ThePansmith** [comment]
Report to EnderIO

**Comment by Giovanni-NL** [comment]
Issue created here https://github.com/Team-EnderIO/EnderIO/issues/860

**Comment by Giovanni-NL** [comment]
So the solution seems to be to not use an Anvil at all. You need to first change a broken spawner into a spawner of the desired mob in a Soul Binder, and then use _that_ broken spawner to craft a powered spawner. 
![image](https://github.com/user-attachments/assets/7a6cf14e-8bdb-458e-bfae-37007b53653f)

However, the quest book still mentions using an anvil. I'll see if I can improve that text and submit a pull request.
![image](https://github.com/user-attachments/assets/3590c035-1177-4e9d-92b2-b73e1eafa87a)
