### ISSUE TITLE
[Bug]: gt axe durability glitch

### ISSUE THREAD

**Issue by lolypoop** [ThePansmith/Monifactory#934]
### Issue Summary

If you drop an axe while autochop is happening durability will stop decreasing

### Reproduction steps

1. Chop any tree
2. Drop an axe

**Comment by Xefyr0** [comment]
Known issue with Gregtech: Modern.
[https://github.com/GregTechCEu/GregTech-Modern/issues/1722](https://github.com/GregTechCEu/GregTech-Modern/issues/1722)
