### ISSUE TITLE
[Feature]: make item tag filters great again!

### ISSUE THREAD

**Issue by ivanthenerd** [ThePansmith/Monifactory#940]
### Suggestion

Put white and black list configs for the Item Tag Filter for easier filtering in stuff like ore processing chains, and some confirmation slots to make sure the item filtered does filter.
![image_2024-10-14_191959181](https://github.com/user-attachments/assets/b1b6b58c-9fbe-45f7-bd08-00bb93690f6d)
(make them like this old relic)

**Comment by Xefyr0** [comment]
Not something we have control over, sadly.
Re-make this issue on the page for the mod that adds the filter - they'll be able to help out.
