### ISSUE TITLE
[Bug]: Unable to join my self hosted server after pack update

### ISSUE THREAD

**Issue by Boyownik** [ThePansmith/Monifactory#943]
### Issue Summary

After updating pack from 0.9.5 to 0.9.6 yesterday (and to 0.9.7 today) I am unable to join my server by mods mismatch as seen below.
I've tried clean reinstall both client & server and still same error occurs.

![image](https://github.com/user-attachments/assets/1f280c59-4cd9-4472-8ab8-70309a96041d)

### Reproduction steps

1. Update server following instructions from FAQ.
2. Update client (Prism Launcher).
3. Try to connect to server

**Comment by MightyPiggie** [comment]
Do you have access to the server console? If so whats the output on that side?

**Comment by Boyownik** [comment]
@MightyPiggie Nothing special there, I think. It looks just like I am getting insta disconnected
![image](https://github.com/user-attachments/assets/93201467-eab4-42b8-a665-e5a511142586)

**Comment by MightyPiggie** [comment]
Mmmh weird. I thought in case of mod incompatibility it should also notify you in the console? Another weird thing, although probably unrelated is that the server seems to be lagging while no one is online.

**Comment by Boyownik** [comment]
That warn is pretty common right after server starts. Am using ARM Oracle VPS so, yeah. For me it is plenty and for free :D

**Comment by MightyPiggie** [comment]
Ah yeah then it does make sense for such hardware :P. I got no clue because you already tried a clean reinstall.

I assume you also didn't make any config changes after the clean reinstall?

**Comment by Boyownik** [comment]
No config changes. The only thing that I did beside clean install is that I have copied over my world save folder, server.properties and eula.txt

**Comment by Boyownik** [comment]
Okay I am dumb dumb....
Continuing my previous comment. The issues was that every time I've tried clean reinstall I forgot every time to change pack mode using script from this repo BOTH  on client and server (which I forgot about to do on client side)... 

Issue resolved
