### ISSUE TITLE
[Bug]: chlorine triflouride recipie is wrong and allows infinite duping of chlorine and flourine

### ISSUE THREAD

**Issue by elsxf** [ThePansmith/Monifactory#945]
### Issue Summary

chlorine trifluoride recipe takes 3B fluorine and 1B chlorine to make 2B CLF3. Instead, it should create 1B CLF3. The electrolysis recipe is correct, turning 1B CLF3 into 1B Chlorine and 3B fluorine. electrolysing and chemical reacting in a loop produce free chlorine and fluorine

### Reproduction steps

make CLF3 in a chemical reactor

**Comment by ramseyspace** [comment]
Seems to be fixed on newer versions (0.9.7) here. The electrolyzing recipe still remains the same
![image](https://github.com/user-attachments/assets/2143a986-d9e0-4f11-823f-f48feaf3f75b)

**Comment by Xefyr0** [comment]
Can confirm, this has been resolved.
