### ISSUE TITLE
[Bug]: Rocket Scanner bug

### ISSUE THREAD

**Issue by nutellabrot155** [ThePansmith/Monifactory#952]
### Issue Summary

![Screenshot 2024-10-16 131808](https://github.com/user-attachments/assets/73a87fa7-7447-4ab7-b896-d2f68bb4649d)
-Version 0.9.7
-Added Flux Networks to both my server and client

### Reproduction steps

1.Build the Rocket Scanner
2.Left click the scanner

**Comment by Xefyr0** [comment]
Issue with Gregtech: Modern, not Monifactory.
