### ISSUE TITLE
[Bug]: Dense ores missing item tags

### ISSUE THREAD

**Issue by AlAtEX** [ThePansmith/Monifactory#961]
### Issue Summary

Dense ores have all the proper tags in their block tags, but are missing all of the tags in their item tags. This means that they cannot be sorted by tag, making the dense ore tag useless.

### Reproduction steps

Press F3 + H, get dense iron ore and press ctrl. Only item tags are balm:ore and forge:ore.

**Comment by MightyPiggie** [comment]
This bug should be fixed once there is a new release. #1006
