### ISSUE TITLE
[Feature]: Make Universal Circuit Default Used When Have Them in AE

### ISSUE THREAD

**Issue by Canbinlol** [ThePansmith/Monifactory#963]
### Suggestion

Currently when coding recipes the AE tend to use normal GT circuit instead of universal ones, even if you have recipe coded for the universal circuits(UC for short in the followings) or have them in the system, which makes the UCs hard to use. I assume the UCs are used to make circuit tier transition easier by only needing to recode the atom recontructor recipe, this issue here makes them even harder to code into recipes in the first place.

**Comment by WithersChat** [comment]
This is sadly not an issue we can have any effect on as pack developers, and comes from how AE2's JEI integration handles autofill.
