### ISSUE TITLE
[Bug]: Free oil cracker overclock 

### ISSUE THREAD

**Issue by lolypoop** [ThePansmith/Monifactory#964]
### Issue Summary

Oil cracker second energy hatch doesnt need energy to overclock(its HV recipe btw)
![2024-10-17_18 34 06](https://github.com/user-attachments/assets/28ff3e0e-4352-4e87-bfb1-049a8b764e2b)

### Reproduction steps

1. Build oil cracking unit
2. Add 2 energy hatches
3. Free overclock

**Comment by ThePansmith** [comment]
GTm issue
