### ISSUE TITLE
[Feature]: assembler recipe for resin boards

### ISSUE THREAD

**Issue by bigchunges402960402** [ThePansmith/Monifactory#966]
### Suggestion

making resin boards for early mv is kinda dumb and goofy i want a assembler which uses glue (the liquid form of the rubber resin) with wooden planks from gt to make the resin boards it would be amazing recipe  which would make making more circuit boards less tedious

**Comment by hollowcrystal** [comment]
the resin printed circuit boards have the recipe with planks, copper foil, and glue

**Comment by bigchunges402960402** [comment]
no i mean the normal ones for making mv circuits the boards that the phenolic boards use there isnt a better recipe for that

**Comment by bigchunges402960402** [comment]
honestly a recipe same as phenolic boards would just be great but uses glue instead of resin
