### ISSUE TITLE
[Bug]: 0.9.8 broke ReHooked

### ISSUE THREAD

**Issue by AveryAndCompany** [ThePansmith/Monifactory#976]
### Issue Summary

Hotkey for Fire Hook no longer functions with Ender Hook in Hook Slot, there are no keybind conflicts.

### Reproduction steps

1. Equip Ender Hook in Hook Slot
2. Attempt to use the hotkey
3. :(

**Comment by OE100** [comment]
it's fixed with ReHooked version 1.6.2, my bad
