### ISSUE TITLE
[Bug]: 0.9.8 Crafting Station + large inventories odd behaviour.

### ISSUE THREAD

**Issue by AveryAndCompany** [ThePansmith/Monifactory#978]
### Issue Summary

With 0.9.8 Crafting Station UI is bugged when paired with large inventories. Additionally EMI can no longer pull items that are not visible in the crafting station UI when this was previously possible.

### Reproduction steps

Clicking the chest Icon in the top left _somewhat_ fixes the UI
![Broken UI](https://github.com/user-attachments/assets/eda4d5ff-da42-4551-9132-722872d9e716)
![Leather Not Visible EMI](https://github.com/user-attachments/assets/7bed8ae5-f5f0-464f-89a7-921204516ba0)
![Leather Not Visible](https://github.com/user-attachments/assets/ff491fce-220b-48b5-aa9c-a1b3119b15a3)
![Leather Visible EMI](https://github.com/user-attachments/assets/4d3740ee-22d3-4e73-96b1-0c5e6717f7dd)
![Leather Visible](https://github.com/user-attachments/assets/b3b7dd1d-dd8c-49ef-a531-b408f5461e82)

**Comment by AveryAndCompany** [comment]
Additionally it seems crafting stations can no longer craft items in this circumstance?

**Comment by Xefyr0** [comment]
Reverted the Crafting Stations update in 0.9.9
