### ISSUE TITLE
[Bug]: EnderIO Fluid Conduits sometimes do not extract fluid from some machines

### ISSUE THREAD

**Issue by tillvit** [ThePansmith/Monifactory#984]
### Issue Summary

See attached video. Extracting worked from an LV fluid solidifier and LV centrifuge, but didn't work for MV Chemical Reactor and MV Electrolyzer.

Occurs with no fluid covers attached; also tried to extract from top/bottom/side

https://github.com/user-attachments/assets/c9c67fc0-621c-4178-aaf1-c70517846790

### Reproduction steps

1. Produce any fluid with a Chemical Reactor
2. Try to extract the fluid using an Ender Fluid Conduit
3. fail

**Comment by ThePansmith** [comment]
Report to enderio
