### ISSUE TITLE
[Bug]: my fluid rig seems like not working.

### ISSUE THREAD

**Issue by Kabandiz** [ThePansmith/Monifactory#987]
### Issue Summary

Fluid rig multiblock not working. Tested on steel and titanium tier.

### Reproduction steps

I built the oil rig yesterday and tried to build it for an hour, but I couldn't. I tried different configurations of the entrance hatches, in different chunks, in different dimensions, I placed the multiblock so that it did not cross the boundaries of chunks, but it seems to me that the problem is somewhere else. The main block indicates that the multiblock is built correctly.
I tried and built the multiblock in a new world, I still couldn't do it.
![image](https://github.com/user-attachments/assets/d6aa629c-f04c-424d-a0c7-c54cff4f32ba)
![image](https://github.com/user-attachments/assets/50b3e030-caa1-4561-9d7c-757fce94a86a)
![image](https://github.com/user-attachments/assets/65bfa2dd-88ea-42a2-b8d5-3ec8cc88975d)
![image](https://github.com/user-attachments/assets/aee981bc-de82-4f5a-b226-546c020696db)
The screenshots show that the structure is assembled, but the liquid is not extracted and the process does not start.

![image](https://github.com/user-attachments/assets/eb2aa6ab-3ef2-4d77-8b9f-11b7a8748288)
In a search for a problem on this topic, I found an old message where a person assembled a fluid rig of a higher tier and it worked for him, which I decided to check too, but it turned out that it does not work either. I observe. the same problems - the structure is assembled, there is energy, the process does not go. I think that this bug appeared in the latest updates, and is associated only with the fluid rig, my Large Blast Furnace works 100%.

**Comment by hollowcrystal** [comment]
had a similar problem and found a fix online, pretty sure its because they can only use one energy hatch, not two

**Comment by Xefyr0** [comment]
The issue is that you are using two energy hatches.
Older versions of Gregtech Modern had a bug where trying to use more than one energy hatch would prevent the machine from working.
Use only one energy hatch or update to the latest version.

**Comment by Kabandiz** [comment]
Then, it is worth changing the preview in EMI and adding this information to the quest book. I have also seen information in known issues related to multiblocks, it should also be updated. Thank you.
