### ISSUE TITLE
[Bug]: Maintenance Hatch Assembler Recipe not working

### ISSUE THREAD

**Issue by OnionMan2002** [ThePansmith/Monifactory#997]
### Issue Summary

EMI Recipe states that Maintenance Hatch requires an LV Machine Hull on Circuit 8 in an Assembler at LV or higher, when placing the LV Machine Hull into an Assembler on Circuit 8, no crafting sequence starts.

This has been reproduced on several Assemblers
This issue has also been reproduced on Assemblers of different Voltage Tiers
![Capture1](https://github.com/user-attachments/assets/dd55f2f9-2134-45c9-8b34-bd5f8ac7fc3d)
![Capture 2](https://github.com/user-attachments/assets/2edf8d0b-f4c3-4963-ad8b-86c64bfe5e73)
![Capture3](https://github.com/user-attachments/assets/fe7aa4b9-48d6-4c53-96ad-6345c087441c)
![Capture4](https://github.com/user-attachments/assets/1bd38ea6-94d3-4865-a0be-4789cebb2b6c)

### Reproduction steps

1. Place MV Assembler, Provide power and Configure to Circuit 8
2. Place LV Machine Hull into powered, LV or higher Assembler

**Comment by Echoloquate** [comment]
What pack version are you on? This was fixed with the last GregTech: Modern update

**Comment by Xefyr0** [comment]
This was already fixed as of the latest release.
Update your modpack.

**Comment by OnionMan2002** [comment]
Issue resolved by updating from version 0.9.0 to 0.9.10

Thank you (:
