### ISSUE TITLE
[Bug]: Rocket Scanner UI bugged

### ISSUE THREAD

**Issue by DominikDeptula** [ThePansmith/Monifactory#998]
### Issue Summary

When I open the UI of Rocket Scanner, the text is cut off and I can't use it.

![image](https://github.com/user-attachments/assets/687c7897-06cc-4fc5-b35e-a3dc9df151fe)

### Reproduction steps

1. Place down a Rocket Scanner
2. Try to use it (right click)

**Comment by Xefyr0** [comment]
Issue with GTM:
https://github.com/GregTechCEu/GregTech-Modern/issues/2234
